### ISSUE TITLE
Modify `.realpython` blank command to embed a url to the site

### ISSUE THREAD

**Issue by brad90four** [python-discord/sir-lancebot#1001]
## Description

When no input is used in the command, the embed sent should have the url to the website. 

## Reasoning

Currently a blank `.realpython` command raises an error, but it could be helpful to have a link to the Real Python homepage instead.

## Proposed Implementation

I have an idea for how this could work, but this can be a good first issue for someone starting out. 

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [X] Anyone can implement this feature

**Comment by Krish-bhardwaj** [comment]
Hi i can i contribute to your project , i am a fresher and looking for contributing to open source
can you assign me this issue

**Comment by Krish-bhardwaj** [comment]
yes i have forked it and joined the discord server , as i am new to all this can me expain me on a meet if possible

**Comment by MaskDuck** [comment]
hi there!
is anyone is still working on the project?
if no i have a fork fixed, can i be assigned? thanks.

**Comment by MarkKoz** [comment]
@Krish-bhardwaj Pinging you to make sure you see the above. Are you still working on this?

**Comment by Krish-bhardwaj** [comment]
![image](https://user-images.githubusercontent.com/72294477/154120006-483cabca-46b9-4467-97db-00ad7e96c983.png)
i guess this is your expected output

**Comment by MarkKoz** [comment]
@Krish-bhardwaj You were the first to ask, so you have the right to work on the issue if you want. You have some code ready, so you can go ahead an open a pull request. Then someone will review it.

**Comment by Krish-bhardwaj** [comment]
> ave the right to work on th

i have opened one PR i have a error in than can you please guide me

**Comment by nodausenis** [comment]
Gracias
