### ISSUE TITLE
Quiz question missing one of the correct answers

### ISSUE THREAD

**Issue by JosiahWI** [python-discord/sir-lancebot#1007]
## Description
The following quiz question is missing "substitution" as a valid answer:

`A ____________ reaction is the one wherein an atom or a set of atoms is/are replaced by another atom or a set of atoms`

The accepted answers are "displacement" and "exchange" according to the bot, but "substitution" is also a correct answer. See this excerpt from Wikipedia:

"A substitution reaction (also known as single displacement reaction or single substitution reaction) is a chemical reaction during which one functional group in a chemical compound is replaced by another functional group. ... A good example of a substitution reaction is halogenation."

You can read the full page at https://en.wikipedia.org/wiki/Substitution_reaction

## Would you like to implement a fix?
***Note: For high-priority or critical bugs, fixes may be implemented by staff.***
- [x] Anyone can implement the bug fix

**Comment by Reverend-Toady** [comment]
hello can i fix this issue? that is if it has not already been fixed yet

**Comment by wookie184** [comment]
> hello can i fix this issue? that is if it has not already been fixed yet

If you're still interested in fixing this feel free to open a PR

**Comment by DivyanshuBist** [comment]
May I fix this issue?
I think only [this](https://github.com/python-discord/sir-lancebot/blob/210a97a4eee9a4babc26366f71d13edcd21b6f9c/bot/resources/fun/trivia_quiz.json#L481)  need to be updated!!

**Comment by wookie184** [comment]
> May I fix this issue? I think only [this](https://github.com/python-discord/sir-lancebot/blob/210a97a4eee9a4babc26366f71d13edcd21b6f9c/bot/resources/fun/trivia_quiz.json#L481) need to be updated!!

Sounds good, i've assigned you 👍

**Comment by JosiahWI** [comment]
Thanks for fixing this!
