### ISSUE TITLE
Latex Command Revamped

### ISSUE THREAD

**Issue by ShakyaMajumdar** [python-discord/sir-lancebot#1009]
## Description
A slightly different implementation of the .latex command, hopefully with no memory leaks this time.
see also: #663 #668

## Proposed Implementation
Previously, we were using matplotlib to render the latex, which seemed to hold references to the data even after we were done with it if the input contained invalid latex. This led to an increase in memory usage every time there was malformed input, and ultimately the bot would come crashing down because of memory limits on the process. The only way to mitigate it was with manual calls to `gc.collect` and `del`s, which was error-prone and hacky.

This time around, I propose that we keep a separate python script for the latex logic, and call into that with `asyncio.subprocess`. That way, memory usage should return to normal after every invocation, since a new process is created each time. Each process would load matplotlib, render latex, save the output in a cache directory, and die.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by MarkKoz** [comment]
> save the output in a cache directory, and die.

Sadder words have never been written.

Yes, this sounds like a feasible approach. You'd need to find out what the memory footprint is of the process, and what the limit on concurrent subprocesses should be.
