### ISSUE TITLE
Suggestion: Joke command

### ISSUE THREAD

**Issue by ghost** [python-discord/sir-lancebot#1023]
## Description

A .joke command, using the <a href = "https://pypi.org/project/pyjokes/"> pyjokes library .</a> Most of the jokes are programming based.

## Reasoning

It would be another fun command for sir lancebot, and as I said earlier, the jokes are programming based, which the community will find relatable.

## Proposed Implementation

I haven't implemented this in a discord bot yet, but I plan on doing so soon. This 
 is how it works (I tested it in a normal python program)
 
![image](https://user-images.githubusercontent.com/95855603/152668444-5cd3f1fa-59ce-49e8-9f77-387a00cf9b88.png)

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by DMFriends** [comment]
I love that idea!

**Comment by cheesemaafia** [comment]
I'd like to work on this! I'm very new to open-source contributions, can someone please assign this to me and guide me a little?

**Comment by MaskDuck** [comment]
hi id wanna work on this!

**Comment by jb3** [comment]
Hey @cheesemaafia, looks like we missed your comment sorry about that! If you are still interested join us on discord and let us know your name and we can help guide you!

**Comment by Diabolical5777** [comment]
Could I be assigned to this issue please?

**Comment by HassanAbouelela** [comment]
Assigned
