### ISSUE TITLE
allow the source command in dev contrib

### ISSUE THREAD

**Issue by onerandomusername** [python-discord/sir-lancebot#1032]
## Description

allow the source command in dev contrib
## Reasoning

its a dev contribution channel, we should be able to run the source command because of its relevance to the channel

## Proposed Implementation

add dev contrib to the source command whitelist

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by Xithrius** [comment]
I approve of this message.
