### ISSUE TITLE
Add more / make changes to the topics for the `.topic` command

### ISSUE THREAD

**Issue by DMFriends** [python-discord/sir-lancebot#1056]
## Description

I think it would make sense to review the current questions we have in the [`py_topics.yaml`](https://github.com/python-discord/sir-lancebot/blob/main/bot/resources/utilities/py_topics.yaml) file and make appropriate additions/corrections.

## Reasoning

I think that the `.topic` command is really cool and engages members more in the topical channels as well as py-gen. I don't check those channels often, but from what I've seen, `.topic` is used quite frequently so I think it makes sense to keep it that way.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

(If you have any ideas for making changes to the topics, please post a comment on this issue and I will consider them!)

**Comment by minalike** [comment]
You're welcome to make suggestions for new topics. Let's keep them on the issue and discuss, and once semi-finalized a PR can be raised?

**Comment by DMFriends** [comment]
Yep, that sounds like a good idea. 👍

**Comment by DMFriends** [comment]
Let's start with the ones that don't already have topics.

For #algos-and-data-structs:
- What is a good algorithm that you know in Python? (might need to be reworded, that sounds a bit weird)
- What are some advantages of NumPy arrays over Python lists?
- What do you know and/or understand about inheritance in Python?
- What are some benefits of modules in Python?

For #c-extenstions:
- What is a good C extension you would recommend?
- How would you go about coding your own C extension in Python?

For #software-design:
- What is a cool software design you know and/or created yourself that you would recommend?

For #type-hinting:
- What are the pros and cons of type hinting in Python?
- How can you tell when you need to type hint in your own code?

For #unit-testing:
- How often do you run unit tests on your projects? Do you think they are necessary? Why or why not?
- How do you write a unit test in Python?
- What are the best Python unit testing frameworks?
- What are some best practices for Python unit testing?
- What is the difference between Pytest and Unittest?

That's all I have for now. The other channel that doesn't have any topics currently is #data-science-and-ai. If anyone comes up with any topic ideas for that channel, please post them on this issue!

**Comment by DMFriends** [comment]
@minalike Would it be ok with you if I started a PR with the above changes? This issue has been around for quite a bit now and nobody else has suggested anything.

**Comment by minalike** [comment]
I am of the impression that the .topic command best serves its purpose in python-general and the off-topic channels. I think for the topical questions adding more questions wouldn't be of much use. But that's going but my gut, I haven't actually searched for invocations of the command.

**Comment by minalike** [comment]
After gathering some internal feedback, we feel the usage of the topic command outside of python-general, off-topic, and occasionally discord-bots is not high enough to require additional topics. While there is no harm in adding more, the current suggestions aren't compelling enough to add to the current list.

We do have interest however, in boosting the current topic questions for our more traffic-heavy channels where the command is invoked frequently making the existing topics very repetitive. Users can make suggestions here: https://forms.gle/oMDNk98oZ8GJoF6XA
