### ISSUE TITLE
Add amsmath support

### ISSUE THREAD

**Issue by PH-KDX** [python-discord/sir-lancebot#1057]
## Description
I'd like amsmath to be included in the LaTeX command for Sir Lancebot.

## Reasoning
Amsmath is a widely used package for things such as including text in equations or aligning multiple equations. Its absence has long been a thorn in my side, and an extremely annoying one at times.

## Proposed Implementation
The amsmath package should be included in the default template, so it gets imported for every LaTeX command run.
This can be done by including the following text on a new line after the first line:
`\usepackage{amsmath}`

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by ShakyaMajumdar** [comment]
While we're at it, I think `amssymb` could be useful too.
