### ISSUE TITLE
Help: subcommand aliases have a redundant space between the parent command name and the subcommand alias

### ISSUE THREAD

**Issue by ichard26** [python-discord/sir-lancebot#1065]
## Description

See title or screenshot below.

## Steps to Reproduce

1. Run `.help aoc about` in #bot-commands

2. See the double space in the "Can also use: " line

## Expected Behaviour

![image](https://user-images.githubusercontent.com/63936253/175797156-a4426b4d-f13a-48d8-8c42-e3ff445ac3ac.png)

## Actual Behaviour

![image](https://user-images.githubusercontent.com/63936253/175797076-1fc7548a-757b-4424-b7c4-e60d507fd1dc.png)

## Known Impacted Platforms

- [x] Web
- [x] Desktop
- [x] Android App
- [x] iOS App

## Possible Solutions

https://github.com/python-discord/sir-lancebot/commit/53a5b3234d085e6527fdb5df75b3ef94ac1c3879 on https://github.com/python-discord/sir-lancebot/tree/ichard26/remove-redundant-space-in-alias-help

## Additional Details

Noticed this while reviewing GH-1049.

## Would you like to implement a fix?

- [x] I'd like to implement the bug fix
- [ ] Anyone can implement the bug fix

**Comment by wookie184** [comment]
Go ahead! This seems to only be an issue on sir-lancebot and not bot.
