### ISSUE TITLE
Add message replies support for `.uwu`

### ISSUE THREAD

**Issue by janine9vn** [python-discord/sir-lancebot#1069]
## Description
I think it would be great that if you replied to a message with `.uwu` and no other text, that lancebot would uwu-ify the replied-to message. Alternatively, add support for `.uwu` in a context menu!

## Reasoning
We must allow `.uwu` in all its forms. But I think it would be a fun feature to implement and a good way to get familiar with our code base.

## Proposed Implementation
If there is no message content, check if there is a message that has been replied to, and if there has use the text from *that* message as the text to uwu-ify.

Or context menu, but I have no idea how context menus work in d.py

- [ ] I'd like to implement this feature myself
- [X] Anyone can implement this feature

**Comment by HassanAbouelela** [comment]
Issue approved. I’ll leave whichever implementation method desired up to the PR author. I don’t think context menus are great for discoverability but it might not hurt to have them.
