### ISSUE TITLE
.uwu command incorrectly transforms emojis in their raw text form

### ISSUE THREAD

**Issue by ionite34** [python-discord/sir-lancebot#1072]
## Description
The current .uwu feature does not handle or preserve external emojis

### Example 1
![Example](https://cdn.ionite.io/img/yAlmKo.jpg)

### Example 2
![Example_2](https://cdn.ionite.io/img/aw7gyW.jpg)

## Expected Behaviour
Either ignoring external emojis, preserving them in place (may not be possible), or transforming them into emoticons instead of the normal text-transform rules. In my opinion, the emoticon replacement is most suitable.

## Possible Solutions
- Detect external emojis by checking for the emoji ID within the bot's known emoji list. 
- For custom emojis, the bot would not be able to send the emojis back, such, escape this from text-transform rules, and instead replacing the custom emoji with a random emoticon from the emoticon list.

## Would you like to implement a fix?

- [x] I'd like to implement the bug fix
- [ ] Anyone can implement the bug fix

**Comment by MarkKoz** [comment]
> instead replacing the custom emoji with a random emoticon from the emoticon list.

Since this command is just for fun, I think this approach is fine.

**Comment by D0rs4n** [comment]
Couldn't we make use of the `emojis` library, that is already a dependency? 
https://github.com/alexandrevicenzi/emojis

**Comment by ionite34** [comment]
> Couldn't we make use of the `emojis` library, that is already a dependency? [alexandrevicenzi/emojis](https://github.com/alexandrevicenzi/emojis)

Well, built-in emojis *do* work right now. And third-party emojis (such as those in python-discord) would work if the bot is in the server. 

However third-party emojis wouldn't be able to be sent since SirLanceBot isn't in those servers, and as such doesn't have access to post those emojis. This is what this issue is for.
