### ISSUE TITLE
Use replied message as argument to `.randomcase` when text isn't provided.

### ISSUE THREAD

**Issue by TizzySaurus** [python-discord/sir-lancebot#1074]
## Description

Allow `.randomcase` to work on replied messages whenever no text argument is provided.

## Reasoning

Pretty self-explanatory; means you can just reply to a message instead of having to manually copy-paste the content as the command argument.

## Proposed Implementation

A simple if statement checking whether a text argument was provided, and if not whether a message was replied to.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by ChrisLovering** [comment]
AFAIK this already exists?

**Comment by TizzySaurus** [comment]
> AFAIK this already exists?

Sorry, I said the wrong command. I meant `.randomcase` 😰

**Comment by ChrisLovering** [comment]
Ah I see now.

Since this in a few places now, I think we should make a custom converter that has the behavior, rather than duplicating code

**Comment by TizzySaurus** [comment]
> Since this in a few places now, I think we should make a custom converter that has the behavior, rather than duplicating code

Yeah, I'd agree with that. Should I replace the existing implementations too? 

What would be a good converter name? Perhaps something along the lines of `TextOrReply`?

**Comment by ChrisLovering** [comment]
Yea, we should replace existing implementations of this.

maybe TextOrReplyCleaned, to indicate we run clean_content over it too, but that sounds good.

**Comment by TizzySaurus** [comment]
Would this be better in bot-core so that we can use it in bot too? (Does bot even need this?)

**Comment by ChrisLovering** [comment]
Yea, that could work. We should start adding converters to bot core more often.

**Comment by TizzySaurus** [comment]
NB: This is stalled by python-discord/bot-core#100

**Comment by TizzySaurus** [comment]
python-discord/bot-core#101 has just been merged so I'll be working on this soon:tm:

**Comment by TizzySaurus** [comment]
It seems I forgot about this issue, but it's now back on my radar and will hopefully have a PR ready over the next week or two.

**Comment by TizzySaurus** [comment]
Managed to get it done in my spare time this morning -- #1129.
