### ISSUE TITLE
`.uwu` doesn't work when replying to an embed.

### ISSUE THREAD

**Issue by AbooMinister25** [python-discord/sir-lancebot#1075]
## Description
Using `.uwu` when replying to an embed doesn't work (returns a plain `>>>`), but it does work if you pass a message link to an embed.

## Steps to Reproduce
Run `.uwu` while replying to an embed.

![image](https://user-images.githubusercontent.com/67297584/178603051-31a963d0-6afa-4132-a644-e991e70e243d.png)

## Expected Behaviour
Return an embed with its contents uwuified.

![image](https://user-images.githubusercontent.com/67297584/178603139-5a026e53-f7ae-40fa-bc87-b360e9990efe.png)

## Possible Solutions
Implementing a check for whether a replied message contains an embed
```py
text = text or getattr(ctx.message.reference, "resolved", None)
if isinstance(text, discord.Message):
    text = text.content
# check suggested
if isinstance(text, discord.Embed):
    do_something()
```
## Would you like to implement a fix?

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [x] I'd like to implement the bug fix
- [x] Anyone can implement the bug fix

**Comment by D0rs4n** [comment]
@AbooMinister25 Would you like me to assign you, or do you wish to wait for someone else first?

**Comment by AbooMinister25** [comment]
I'd like to be assigned
