### ISSUE TITLE
Embeds for multiple GitHub issues don't maintain ordering

### ISSUE THREAD

**Issue by shenanigansd** [python-discord/sir-lancebot#1076]
## Description
When Sir Lancebot creates an embed listing multiple GitHub issues, the issues are not in the same order that they were in in the orginal message

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by Numerlor** [comment]
seems to be a duplicate of #743

**Comment by shenanigansd** [comment]
> seems to be a duplicate of #743

My mistake, closing in favor of #743
