### ISSUE TITLE
.latex command preamble update

### ISSUE THREAD

**Issue by 3ddP** [python-discord/sir-lancebot#1086]
## Description
The latex preamble determines which packages/commands are available to the user when writing .tex input for .latex command. The proposal is to include more packages in the preamble, which appears to be in sir-lancebot/bot/resources/fun/latex_template.txt. In particular, the proposed libraries extend the user-friendliness when writing maths by allowing bold symbols, calligraphic numbers, and creation of TikZ figures.

## Reasoning
This update would put more of the commonly employed latex packages at the disposal of users. The bold and calligraphic symbols lend themselves to linear algebra, while TikZ makes nice diagrams. 

## Proposed Implementation
The proposed implementation is to replace the current header with this one:

\usepackage{amsmath,amsthm,amssymb,amsfonts} %this one extends the current one
\usepackage{bm} %nice bold symbols for matrices and vectors
\usepackage{bbm} %bold and calligraphic numbers
\usepackage[binary-units=true]{siunitx} %SI unit handling
\usepackage{tikz} %from here on, to make nice diagrams with tikz
\usepackage{ifthen}
\usetikzlibrary{patterns}
\usetikzlibrary{shapes, arrows, chains, fit, positioning, calc, decorations.pathreplacing}

where the % comments roughly describe what the packages do, for further reference

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by wookie184** [comment]
I'm not a latex expert but this sounds fine to me if nobody is against this.

**Comment by ShakyaMajumdar** [comment]
I would like to be assigned to this
