### ISSUE TITLE
1D Cellular Automaton Generator 

### ISSUE THREAD

**Issue by Sas2k** [python-discord/sir-lancebot#1098]
## Description
Hello, the feature I would like to propose is a cellular automaton generator.
like if someone types;
`.simulate <rule-number> <position: left|center|right|random> <initial-condition random|impulse>(startes with 1 cell)`

> Rule-Number:  A rule consists of deciding, for each pattern, whether the cell will be a 1 or a 0 in the next generation. There are then 28 = 256 possible rules.
> postion: the place where the starting cells are placed
> initial-conditon: random - randomly place cells | impulse - starts with only 1 cell

and it would send a picture of the output.

## Reasoning

For fun! and education purpose of course(https://www.techtarget.com/searchenterprisedesktop/definition/cellular-automaton)

## Proposed Implementation
the code for the simulation is already implemented in one of my own bots and it's fully functional
[Link-To-Gitub-Repo-of-the-existing-code](https://github.com/Sas2k/PokeStrike-Utility-Bot/blob/main/Cogs/Fun.py#L19-L72)

![image](https://user-images.githubusercontent.com/91795267/190667530-d4c17e28-c697-4293-b813-174c4e2ed907.png)

## Additional Details

Wikipedia On Cellular Automata -> https://en.wikipedia.org/wiki/Cellular_automaton
wolfram -> https://mathworld.wolfram.com/CellularAutomaton.html

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself

**Comment by mbaruh** [comment]
Sorry, I'm not really sure what this is or what to do with that

**Comment by Sas2k** [comment]
> Sorry, I'm not really sure what this is or what to do with that
Have you ever heard of cellular automaton

**Comment by mbaruh** [comment]
I think this is a fun standalone project to implement if you're interested in the algorithm, but honestly I don't think it fits the bot. It's not informational or interactive, and I don't see people using it.

**Comment by Sas2k** [comment]
ok, thanks for reviewing it @mbaruh
