### ISSUE TITLE
Enhance spoopy reactions for Halloween

### ISSUE THREAD

**Issue by Preocts** [python-discord/sir-lancebot#1142]
## Description

I would propose increasing the pattern match for "spooky" in the Halloween reacts to include such fun alternatives as "spoopy", "spookier", "spoopiest", and such.

## Reasoning

Following the spirit of the best season; "spoopy" is time honored meme'ry, ripe historic use. It seems a shame to ignore such valuable potential and, indeed, causes me to feel a pang of sadness when a happy little ghost fails to appear whilst I am being spoopy.

![image](https://user-images.githubusercontent.com/13407322/200195447-56b6c09f-7655-4b05-af2a-fbfdd7bd621c.png)

## Proposed Implementation

Implementation would involve a simple adjustment of the existing regex pattern with no further logic or changes required.

https://github.com/python-discord/sir-lancebot/blob/737faeda624f639d7ab9978457855fd12cc8f98b/bot/exts/holidays/halloween/spookyreact.py#L14

`\bspo{2,}[k|p][i|y](er|est)?\b` will suffice. It captures the following combinations:

```
spooky
spoooky
spoopy
spoooopy
spookier
spookiest
spoooopiest
spoooopier
```

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by wookie184** [comment]
proposed regex sounds good, go ahead!
