### ISSUE TITLE
Fixes for challenge command

### ISSUE THREAD

**Issue by wookie184** [python-discord/sir-lancebot#1170]
Running the `.challenge` command. the following issues occur:
-  Interactions edit the message but still show as failed
![image](https://user-images.githubusercontent.com/22353562/207935734-60980c6a-a254-4a61-b8fc-8a294b2e8a79.png)
- The same challenge seems to be shown every time for a given query, where it should be random.

## Possible Solutions

I think the failed interaction thing should be fairly simple to fix, I haven't looked at the code though.

The same challenge being shown could be due to a change in the behaviour of the codewars search. It seems there's a "random sample" option on the page 
![image](https://user-images.githubusercontent.com/22353562/207936512-03ea869a-2597-48eb-a3c9-61fd005201ed.png)
so we may need to use `sample=true` in the query? I haven't tested this.

## Would you like to implement a fix?

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [ ] I'd like to implement the bug fix
- [x] Anyone can implement the bug fix

**Comment by henri-climber** [comment]
Hello,
I'd be interested in working on this issue.

**Comment by wookie184** [comment]
> Hello, I'd be interested in working on this issue. The first problem seems easy to fix. However, I am not sure yet if I can solve the second problem, but I would like to try.

Sounds good, i'll assign you to the issue. If you're not sure about the second issue it's fine to just open a PR for the first.
