### ISSUE TITLE
DeepL API calls with Lancebot

### ISSUE THREAD

**Issue by 3ddP** [python-discord/sir-lancebot#1177]
## Description
The proposed feature is to enable Lancebot to make queries to DeepL. This is an AI-powered translator that, although limited to few languages, performs quite well with the supported ones and vastly outperforms Google translate.

## Reasoning
It would be cool, for one. Additionally, it could help some users whose English is not so great (either by allowing others to translate their messages into English, or backwards).

## Proposed Implementation
I have none in mind, but DeepL does have an API that appears to be free: https://www.deepl.com/docs-api

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by Robin5605** [comment]
The actual implementation is up for debate (e.g which service we use)
But as an overall I'm in favor of this translation feature because it's not uncommon we have folks who have difficulty with English and it would widen up our audience a lot.

**Comment by AbooMinister25** [comment]
> The actual implementation is up for debate (e.g which service we use) But as an overall I'm in favor of this translation feature because it's not uncommon we have folks who have difficulty with English and it would widen up our audience a lot.

I don't think it'd be the ideal move to try and open the server up to more languages, there would be burden on moderation to actively trans

**Comment by wookie184** [comment]
Slightly unsure, as we only allow english on the server, and this feature requires using another language, and I'm not sure if having a conversation through lancebot commands is ideal even if we want that.

**Comment by ChrisLovering** [comment]
Yea, I don't think we want this feature.
