### ISSUE TITLE
Bookmark command registers success even when DMs are blocked

### ISSUE THREAD

**Issue by Preocts** [python-discord/sir-lancebot#1179]
## Description

When using the bookmark command, if your DMs are closed the bot warns you to enable DMs to receive the bookmark. However, you are still registered as having received the bookmark afterward.

## Steps to Reproduce

- Block Lancebot (or close DMs)
- Run the `.bm` command for a reply
- *warning embed is displayed*
- Unblock Lancebot (or open DMs)
- Click the "Receive Bookmark" button
- *private notice is displayed that you have already received a bookmark to that message*

## Expected Behaviour

If the bot fails to provide the bookmark the transaction should not be registered as successful, allowing a retry on the user's side.

## Actual Behaviour

If the bot fails to provide the bookmark the "Receive Bookmark" button for that transaction is now useless to the user and the command must be run again.

![image](https://user-images.githubusercontent.com/13407322/209585553-633dd211-4818-4724-aeae-128867341835.png)

## Known Impacted Platforms

- [x] Web
- [x] Desktop
- [ ] Android App
- [ ] iOS App

## Possible Solutions

The error during sending the DM is captured in the method below. Perhaps a return boolean of success could be added to avoid storing the transaction as successful downstream.

https://github.com/python-discord/sir-lancebot/blob/9f239fed5f3d4d24bbec6154cac76d1b1e53b2bf/bot/exts/utilities/bookmark.py#L99-L107

https://github.com/python-discord/sir-lancebot/blob/9f239fed5f3d4d24bbec6154cac76d1b1e53b2bf/bot/exts/utilities/bookmark.py#L114-L116

## Would you like to implement a fix?

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [ ] I'd like to implement the bug fix
- [x] Anyone can implement the bug fix

**Comment by TizzySaurus** [comment]
@Preocts were you wanting to implement this?

If not, I'd like to do this, so can I please be assigned?

**Comment by Preocts** [comment]
It's all yours @TizzySaurus !

**Comment by TizzySaurus** [comment]
For reference, this is currently stalled by #1223.

**Comment by Robin5605** [comment]
This issue should be fixed in #1223
