### ISSUE TITLE
Bring back .bookmark text command

### ISSUE THREAD

**Issue by minalike** [python-discord/sir-lancebot#1219]
Can we undeprecate the text command? The context menu/app command seems to inexplicably disappear from clients for some users, and when it does work, it also has the limitation of not working in read-only channels. I also think the original UX of the original `.bm` command was pretty nice, especially when replying to messages.

Relevant PR: #1211

**Comment by DMFriends** [comment]
I agree with Arl's suggestion to make this a slash command rather than text. [](https://discord.com/channels/267624335836053506/635950537262759947/1079503236291117177)

**Comment by onerandomusername** [comment]
> > and when it does work, it also has the limitation of not working in read-only channels.
> 
> Either way, you wouldn't be able to bookmark messages in read-only channels because you can't send text/slash commands there anyway.

the original text command would take any link as input. there is no way to provide input with a link in the current form.

**Comment by Preocts** [comment]
> I agree with Arl's suggestion to make this a slash command rather than text. [Discord Link](https://discord.com/channels/267624335836053506/635950537262759947/1079503236291117177)

Is https://github.com/python-discord/sir-lancebot/pull/1211 in a state that a revert could be done until the work for a slash command is ready?

It's likely only the vocal few who used the command on a regular; however the lack of a reliable bookmark feature is missed.

**Comment by ChrisLovering** [comment]
Approved, anyone who wants to pick this up feel free to comment here.

The PR can't be directly reverted as it came with a number of refactor commits too.

**Comment by Robin5605** [comment]
I can take this.
Just to be clear, we just want the same `.bm` implementation from before, without any changes?
