### ISSUE TITLE
Add a timer that tracks how long it takes for someone to mention "ChatGPT" or "Mojo" in #python-general

### ISSUE THREAD

**Issue by SwiftNathalie** [python-discord/sir-lancebot#1271]
## Description
On Pygen, we love to joke about how often ChatGPT and Mojo come up in conversation. In fact, we've even started keeping track of how long we can go without mentioning them!
My suggestion is to add a timer to track how long we can last without mentioning them. The timer would let us know when someone finally brings them up again, and it would announce the new record for the longest time Pygen has gone without them coming up on the conversation.

## Reasoning
The addition of a timer to track how long we can go without mentioning ChatGPT and Mojo would be a fun and engaging activity for the Pygen community. It would allow us to approach conversations in a lighthearted and humorous way, and I think it would add a great deal of entertainment to the community's interactions.

## Proposed Implementation
The bot will initialize by fetching the current datetime and storing it. When a user mentions "ChatGPT" or "Mojo", the bot will retrieve the new datetime and calculate the timedelta between it and the stored datetime.

The bot will compare this timedelta with the current record. If it's larger than the current record, the bot will announce the new record and store it. If it's not larger, the bot will use the new datetime as the reference point for future comparisons without making an announcement.

## Additional Details

🔹 To prevent inconvenience, the feature will make minimal announcements without pinging anyone and delete messages after 5 minutes.

🔹 To avoid spam, announcements will have a 1-hour cooldown. The bot will still store new records, but skip announcement messages.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by mbaruh** [comment]
Thanks for the suggestion. How is this better than searching the channel for those words? It gives all the information while involving only the person interested in it. Making it a feature of the already chaotic python-general chat doesn't seem desirable.

**Comment by SwiftNathalie** [comment]
> Thanks for the suggestion. How is this better than searching the channel for those words? It gives all the information while involving only the person interested in it. Making it a feature of the already chaotic python-general chat doesn't seem desirable, not to mention the possible implication of potentially making the person who mentioned those words feel they're being made fun of.


Thanks for the feedback!
While it is true that one could manually search through the channel to track the standing record, that is not the primary purpose of the feature. Instead, the aim of the feature is to add an element of fun and engagement to the #python-general channel by providing a lighthearted and enjoyable way for community members to participate. The act of keeping track of the record is part of what makes the feature appealing to users, but isn't it's focus.
As for your concerns of the feature possibly disrupting the channels, that's something that I've given some thought and come up with the following solution; 

• Make the announcement message concise by stating only the new record and deleting itself after 5 minutes.

• Have safeguards in place to avoid it possibly cluttering the channels, such as cooldowns.

Regarding your concern about the possibility of someone feeling like they're being made fun of, I appreciate you bringing that up. However, I believe that the Python community is a friendly and welcoming group, and I don't think anyone would feel targeted by this feature. Plus, it adds a fun and lighthearted aspect to our conversations.

**Comment by n0Oo0Oo0b** [comment]
Another potential solution to avoid cluttering the channels is by sending the timer resets to a separate channel (maybe a thread in ot0?) to avoid clutter in #python-general itself
