### ISSUE TITLE
Fix Type Annotations

### ISSUE THREAD

**Issue by rtk-rnjn** [python-discord/sir-lancebot#1309]
## Description
Incorrect Type Annotations, in following lines:
- https://github.com/python-discord/sir-lancebot/blob/main/bot/utils/halloween/spookifications.py#L9
- https://github.com/python-discord/sir-lancebot/blob/main/bot/utils/halloween/spookifications.py#L20
- https://github.com/python-discord/sir-lancebot/blob/main/bot/utils/halloween/spookifications.py#L30
- https://github.com/python-discord/sir-lancebot/blob/main/bot/utils/halloween/spookifications.py#L52
- https://github.com/python-discord/sir-lancebot/blob/main/bot/exts/utilities/colour.py#L185 (in return type)
- https://github.com/python-discord/sir-lancebot/blob/main/bot/exts/utilities/epoch.py#L121 (in return type)

## Steps to Reproduce
NA

## Expected Behaviour
NA

## Actual Behaviour
NA

## Known Impacted Platforms

- [ ] Web
- [ ] Desktop
- [ ] Android App
- [ ] iOS App

## Possible Solutions
Fix type hint

## Would you like to implement a fix?

- [ ] I'd like to implement the bug fix
- [x] Anyone can implement the bug fix

**Comment by ChrisLovering** [comment]
If you wanted to raise a PR for this feel free to do so.

**Comment by rtk-rnjn** [comment]
thanks.

**Comment by wookie184** [comment]
What are the issues with the first four links you gave?

**Comment by rtk-rnjn** [comment]
```py
from PIL import Image
...

def inversion(im: Image) -> Image:
    ...
```

`Image` is module here. The actual function is `Image.Image`

---

The correct annotation should be:-
```py
from PIL import Image
...

def inversion(im: Image.Image) -> Image.Image:
    ...
```
