### ISSUE TITLE
Add a `.rfc` command

### ISSUE THREAD

**Issue by SomeHybrid** [python-discord/sir-lancebot#1342]
## Description

Add a `.rfc` command with an RFC ID parameter that would respond with some information regarding the relevant RFC.

## Reasoning

This command would be useful in a situation where a relevant RFC would help contribute to the current conversation.

## Proposed Implementation

A possible implementation of this would get the plaintext representation of the RFC, from `https://www.rfc-editor.org/rfc/rfc{id}.txt`, and some basic information about the RFC, such as the category, name, and first few sentences of the linked RFC. An example implementation of this is shown in the below picture.
<img width="331" alt="Screenshot 2023-08-07 at 12 43 57" src="https://github.com/python-discord/sir-lancebot/assets/91648368/7789935f-6de1-486a-afde-1a1c1fa63a84">

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by wookie184** [comment]
This sounds alright to me if you'd like to work on this.

I think the embed could be improved a bit from the example you posted, generally RFCs have an "abstract" section so it would be good if we could extract that section to include in the embed rather than just the start of the document which might not be that useful.

How would you plan on getting the metadata (e.g. authors, publish date, title)? Would you just parse them from the document? If so, is the format consistent enough for this to always work? Is there any sort of API that you can get info in a more machine readable format from?

**Comment by SomeHybrid** [comment]
> I think the embed could be improved a bit from the example you posted, generally RFCs have an "abstract" section so it would be good if we could extract that section to include in the embed rather than just the start of the document which might not be that useful.

Some RFCs, such as RFC-1, do not have an abstract section. A possible fix to this would be to check for the existence of the abstract section and send the first few lines of the RFC if it isn't found.

> How would you plan on getting the metadata (e.g. authors, publish date, title)? Would you just parse them from the document? If so, is the format consistent enough for this to always work? Is there any sort of API that you can get info in a more machine readable format from?

Getting the metadata might seem difficult to do, however the title can be extracted from the title of the page. More machine-readable RFCs can be retrieved through the URL `https://www.rfc-editor.org/rfc/rfc{id}.txt`, which returns the RFC as a plaintext file, where `{id}` is the id of the specified RFC.

**Comment by SomeHybrid** [comment]
It seems like there's an API for RFCs at https://datatracker.ietf.org/api/, which could make this easier

**Comment by SomeHybrid** [comment]
`https://datatracker.ietf.org/doc/rfc{id}/doc.json` returns JSON data of the RFC.
