### ISSUE TITLE
Let the `.rfc` command be usable in other channels.

### ISSUE THREAD

**Issue by SomeHybrid** [python-discord/sir-lancebot#1353]
## Description

Change the `.rfc` command to work in channels like `#python-discussion`

## Reasoning

Currently, the `.rfc` command only works in `#sir-lancebot-playground`. However, the `.rfc` command should also be able to be used in other relevant channels like `#python-discussion`

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by wookie184** [comment]
Sounds fine to me, feel free to open a PR

**Comment by shtlrs** [comment]
@SomeHybrid Please let us know if you want to implement this yourself so that we assign it to you.

**Comment by SomeHybrid** [comment]
> @SomeHybrid Please let us know if you want to implement this yourself so that we assign it to you.
👍
