### ISSUE TITLE
Using `imsosorry` for uwuification

### ISSUE THREAD

**Issue by SomeHybrid** [python-discord/sir-lancebot#1373]
## Description

This proposal seeks to use the [`imsosorry`](https://pypi.org/project/imsosorry) package for uwuification instead of the current in-built one.

## Reasoning

This proposal would benefit the community as there have been several (8 as I can count) issues for uwuification. However, using an external package for this would move issues relating to uwuification to that package and would add some new additions.

## Additional Details

The [`imsosorry`](https://pypi.org/project/imsosorry) package is derived from the Sir Lancebot's `uwu.py` file with some extra additions and being discord.py-agnostic. This would mean the `_ext_emoji_replace` function would still have to be in Sir Lancebot.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by ChrisLovering** [comment]
This repository is a learning tool for our community.

Installing a 3rd party package and having the bot be a thin command wrapper around it does not reach this goal.

Anyone is welcome to pickup the outstanding issues around the `uwu` command if they want to lean about discord bots, regex, or contributing to github repositories themselves.
