### ISSUE TITLE
addition of .hsp command to lancebot

### ISSUE THREAD

**Issue by 3ddP** [python-discord/sir-lancebot#1391]
## Description
The .hsp [text] command would take the provided text, split it into 3 roughly equal sized chunks, and append each of the chunks to []aha []tinky []oop in the places indicated by the brackets. Then, the resulting text would be posted on pydis. 

Examples:
.hsp RFC (expected output: Raha Ftinky Coop)
.hsp Edd (expected output: Eaha Dtinky Doop (or Eaha Dinky Doop; see additional details))
.hsp intoxicant (expected output: intaha oxitinky cantoop)

* Edit: as an additional detail, it would be nice if the command could work by replying to a message, much in the same way as the .uwu command

## Reasoning
We often play around with this phrase due to the rich, deep lore surrounding the username "hsp". Having a bot command would make this much easier. Although this is largely a joke, I think it also makes for a nice "first project".

## Additional Details
Note that in some cases, there is no unique way of splitting text into 3 "equal sized chunks". Additionally, we sometimes use []inky instead of []tinky, or otherwise replace different amounts of letters from each component of the base "haha stinky poop". A possibility would be for the command to take several parameters indicating how to slice the given text, and how many letters to replace from each word in "haha stinky poop". A default behavior replacing only the first letter of each word would be reasonable if no extra parameters are given. Finally, this whole project makes no sense and will probably be rejected, but I thought we might as well try and put it in the pipeline.

## Would you like to implement this yourself?
- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by ShakyaMajumdar** [comment]
vetoed.
