### ISSUE TITLE
Randomize colour of hearts for Valentines reactions

### ISSUE THREAD

**Issue by Preocts** [python-discord/sir-lancebot#1447]
## Description

I'd like to propose that the heart emoticon currently used for Valentines be expanded to include the many other colourful hearts available.

## Reasoning

Fun and a thrilling sense of risk; never knowing which heart will be used.

## Proposed Implementation

It looks like the random selection of an emoticon is already implemented in the logic. This change would include simply adding the additional choices to the list.

https://github.com/python-discord/sir-lancebot/blob/1b09322f8be46530e01ffb6f5a80c14e786c5411/bot/exts/holidays/holidayreact.py#L31-L34

```py
heart_emoticons = (
    "\ud83d\udc9c",  # purple_heart
    "\ud83d\udc9f",  # heart_decoration
    "\u2665\ufe0f",  # hearts
    "\ud83d\udda4",  # black_heart
    "\ud83d\udc99",  # blue_heart
    "\ud83e\udd0e",  # brown_heart
    "\ud83d\udc9d",  # gift_heart
    "\ud83d\udc9a",  # green_heart
    "\ud83e\ude76",  # grey_heart
    "\ud83e\ude75",  # light_blue_heart
    "\ud83e\udde1",  # orange_heart
    "\ud83e\ude77",  # yellow_heart
    "\ud83d\udc9e",  # revolving_hearts
    "\ud83d\udc96",  # sparkling_heart
    "\ud83e\udd0d",  # white_heart
    "\ud83d\udc9b",  # yellow_heart
    "\u2764\ufe0f",  # heart
    "\ud83d\udc97",  # heartpulse
)
```

## Additional Details

Given the standard Discord client has two primary themes, dark and light, it should be considered if any exclusions are needed. This is a visual of the hearts on the two primary themes. I did a brief preview of Nitro themes which do not appear to change the contrast dramatically on comparison to the base themes.

![image](https://github.com/python-discord/sir-lancebot/assets/13407322/17a427b0-0bf0-4d12-adb9-2f326cc63013)

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by ChrisLovering** [comment]
Sounds good to me!
