### ISSUE TITLE
Display word on hangman timeout

### ISSUE THREAD

**Issue by wookie184** [python-discord/sir-lancebot#1497]
Currently when the hangman command times out it doesn't tell you what the word was:
![image](https://github.com/python-discord/sir-lancebot/assets/22353562/782b5783-a3aa-4c52-a64c-c7556b1fe8ec)

This is annoying if you were still playing but were just slow thinking of a letter or got stuck and wanted to wait for it to be revealed.

Instead, it should *reply* to the original message saying that you lost, the game timed out, and what the word was.

The code is here: https://github.com/python-discord/sir-lancebot/blob/a1041e76cb19a92707ebc3cd7859631e2457f55d/bot/exts/fun/hangman.py#L117

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by l-melon** [comment]
Hello, I would like to work on this issue.

**Comment by l-melon** [comment]
#1561

**Comment by wookie184** [comment]
Thanks for fixing this @l-melon!
