### ISSUE TITLE
Trivia question 423 is wrong

### ISSUE THREAD

**Issue by L3viathan** [python-discord/sir-lancebot#1501]
## Description

Trivia question 423 is "What is the name for unicode codepoints that do not fit into 16 bits?", with the supposedly correct answer being "surrogates". This is wrong.

At some point in the past what is now UTF-16 was occasionally called "Unicode", especially in the Windows and Java world. To encode codepoints outside the [Basic Multilingual Plane](https://en.wikipedia.org/wiki/Plane_(Unicode)#Basic_Multilingual_Plane) UTF-16 uses surrogate characters, which are part of Unicode, but are _below_ 16 bits (otherwise they couldn't be used in UTF-16).

## Steps to Reproduce
Play `.quiz cs` for a long time until you get this question, then get confused.

## Possible Solutions
Remove or drastically rephrase this question.

## Would you like to implement a fix?

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [x] I'd like to implement the bug fix
- [x] Anyone can implement the bug fix

(either is fine with me)

**Comment by wookie184** [comment]
Sounds good. Removing it is fine, unless you can think of a good way to rephrase it. Feel free to open a PR
