### ISSUE TITLE
Improve formatting of `.quiz help`

### ISSUE THREAD

**Issue by n0Oo0Oo0b** [python-discord/sir-lancebot#1502]
In the embed for `.quiz help`, the spacing between categories is smaller than the spacing between each category name and description:

![image](https://github.com/python-discord/sir-lancebot/assets/84215197/17af1130-4100-4752-933a-37d8dcf749a4)

It would make more sense to put the category name and description closer together, which may come in the form of changing the display format entirely.

Relevant code is here: https://github.com/python-discord/sir-lancebot/blob/a1041e76cb19a92707ebc3cd7859631e2457f55d/bot/exts/fun/trivia_quiz.py#L616

## Additional info

I suspect this is a side effect of Discord supporting markdown (since we're only adding single newlines in the embed), so only adjusting the spacing may be impossible.

## Would you like to implement a fix?

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [ ] I'd like to implement the bug fix
- [x] Anyone can implement the bug fix

**Comment by wookie184** [comment]
Agreed, it is pretty ugly currently. We could even put the category name on the same line as the description.

Whoever wants to PR can play around and see what looks good.

**Comment by hedyhli** [comment]
Hello @n0Oo0Oo0b I noticed this today too, I've opened a PR at #1500 already 😄

**Comment by n0Oo0Oo0b** [comment]
> Hello @n0Oo0Oo0b I noticed this today too, I've opened a PR at https://github.com/python-discord/sir-lancebot/pull/1500 earlier today 😄

My bad, I only checked issues for duplicates. I'll make sure to check PRs as well in the future :+1:

**Comment by hedyhli** [comment]
No worries, it's good to have an issue to link.
