### ISSUE TITLE
Earth Photos

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/sir-lancebot#174]
`.earth_photo` should should make the bot post a random beautiful earth / environment photograph. 

These must be licensed as public domain or CC. Either add a selection of appropriately licensed photos to this repository that the feature can draw from, use hotlinks to a page that allows it (like imgur or similar), or use an appropriate API. 

See https://github.com/python-discord/seasonalbot/pull/141 for a relevant discussion about image sourcing.

Adding some information about Earth Day into this would also be fine.

Please note that you have quite a lot of freedom in how you choose to complete this, so use your creativity and come up with a fun solution.

**Comment by quizzicaltrains** [comment]
I am interested in implementing this by using the Unsplash API.

**Comment by Aaryan-K** [comment]
I'm interested in trying to do this

**Comment by Aaryan-K** [comment]
This seems to be beyond my ability - if it can be unassigned I can look for an issue that's more my level of experience to contribute to.

**Comment by ncDevMan** [comment]
This sounds like fun. I could take a look at this if you would like.

**Comment by ikuyarihS** [comment]
Sure thing, I've assigned the issue to you @ncDevMan

**Comment by Kronifer** [comment]
This sounds like something I'm interested in, only problem is I've never worked with cogs...

**Comment by Xithrius** [comment]
@ncDevMan are you still planning on working on this feature?

**Comment by ncDevMan** [comment]
If @Kronifer would like to take this, he may. I tested a few API's- one around NASA. But I did not get very far.

**Comment by Kronifer** [comment]
@ncDevMan I'd love to! I'm gonna go over cogs and get started.

**Comment by Kronifer** [comment]
@Xithrius the command file should go in the bot/exts/Easter folder, right?

**Comment by Xithrius** [comment]
> @Xithrius the command file should go in the bot/exts/Easter folder, right?

Yep!

**Comment by Kronifer** [comment]
Alright, perfect! I'll get started on that soon.

**Comment by Kronifer** [comment]
Hey @Xithrius , I'm trying to do this with the unsplash API. Is there somewhere we can store secret keys for the bot?

**Comment by HassanAbouelela** [comment]
Hey checkout:
https://github.com/python-discord/sir-lancebot/blob/a3bd208580ff223cd0120d0c4b5a1bf3c28d03e5/bot/constants.py#L264-L266

Basically, you add an environment variable to this list, and we'll set it up on our end before we merge the feature. Just be sure to leave a note asking us to do so in the pull request.

**Comment by Kronifer** [comment]
@HassanAbouelela so when it's ready, should I email one of you guys the keys?

**Comment by HassanAbouelela** [comment]
No, we'll create our own app, and I see they have a process for requesting a production token, which we will have to go through.

**Comment by HassanAbouelela** [comment]
I'm having a quick look through the API, please note that:
> All applications must follow the API Guidelines, including properly providing attribution for the photographer and Unsplash.

\- [Unsplash Documentation](https://unsplash.com/documentation#registering-your-application)

This is something you'll have to keep in mind with your implementation, as well as all their other rules.

**Comment by Kronifer** [comment]
@HassanAbouelela thanks for clarifying! I'll make my own for testing purposes then. I'll be sure to keep in line with the rules 🙂
