### ISSUE TITLE
Tech Leaders Pride

### ISSUE THREAD

**Issue by MadisonMcdonald** [python-discord/sir-lancebot#208]
A bot a command that would return a random Tech leader in the LGBTQ community, with a picture of them, a small write up of who they are, what they do, and how they represent the community. possible bot command could be !techlgbtq

**Comment by scragly** [comment]
Adding a command to showcase notable LGBTQ+ community leaders active in the tech industry sounds good.

I would recommend though simplifying the command name. Most of the pride commands should be trying to have a similar command name structure to keep things easy to remember, so using the currently approved `.prideavatar` command as a basis, `.prideleaders` or similar would be better.

**Comment by lemonsaurus** [comment]
`.pridehero` or `.prideleader` seems good. plural strikes me as odd.

**Comment by SebastiaanZ** [comment]
@MadisonMcdonald said she's going to work on this one.

**Comment by SebastiaanZ** [comment]
@MadisonMcdonald Hey Madi, how are you doing on this issue?

**Comment by Anubhav1603** [comment]
I wnt to work on this :)

**Comment by scragly** [comment]
I've assigned you @Anubhav1603.

Feel free to ask any clarification questions if needed, and since it'll likely involve a decent amount of prose-like information, be sure to have at least another set of eyes go over the text for spell-checks/grammar to avoid needing to do so during code review.

**Comment by Shivansh-007** [comment]
I will take over PR #485. Thanks
