### ISSUE TITLE
[Feature Request] Pride Movie Generator

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/sir-lancebot#213]
What a SeasonalBot event without a movie generator? There are plenty of movies out there that showcase, celebrate, or are otherwise associated with the LGBTQI+ community. For this feature, it's your job to write a command that suggests such a movie to the user.

## Implementation details

Instead of suggesting a random movie, it would be nice if the suggestion was based on the movie preferences of the user. So, use your creativity and come up with a system to suggest movies to the user in desperate use of a movie. You could think of having the user provide a movie genre, an interactive yes/no/choices question/decision tree ("Scary? yes/no", "Romcom or Action"...) or any other method you think of.

- [ ] Think of a unique command name (suggestion: `.pridemovie`)
- [ ] Make some sort of static resource with movies
- [ ] Code the command following the contributors docs
- [ ] Make a Pull Request detailing your implementation, preferably including screenshots as well 

## Additional information

- Keep us updated on your progress by leaving comments!
- Make sure to give you commits a descriptive commit message
- Please note the style guide and conventions listed in the various contrib documents
- There have been other movie generators for previous events, so feel free to check to out for inspiration
- If you want to include graphics, make sure they have a permissive license

**Comment by RohanJnr** [comment]
This can be merged with generalized movie command #345

**Comment by Akarys42** [comment]
Closed by #350
