### ISSUE TITLE
[Feature Request] Pride Anthems

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/sir-lancebot#219]
Almost every Pride event involves music, so why not ours? This commands picks a random song out of a list of Pride Anthems and embeds a YouTube-video of it in the channel it was issued in. 

## Implementation details

- [ ] Research Pride Anthems and create a static resource of anthems with YouTube-urls
- [ ] Code a command (e.g., `.prideanthem`) that embeds a random song of the list
- [ ] Think of a method that prevents the bot from repeating a song too quickly*
- [ ] Make a Pull Request showcasing your feature! 

*) The method that prevents the bot from repeating a song too quickly doesn't have to persist across restarts/redeployments of the bot. It's a nice feature, but not a mission-critical one.

## Additional information

- Keep us updated on your progress by leaving comments!
- Make sure to give you commits a descriptive commit message
- Please note the style guide and conventions listed in the various contrib documents
- If you want to include graphics, make sure they have a permissive license

**Comment by AvianAnalyst** [comment]
I think I'd like to try to tackle this one, if that's ok!

**Comment by SebastiaanZ** [comment]
@AvianAnalyst Sure! I'll mark it as in progress.

**Comment by AvianAnalyst** [comment]
What do you guys think about optional parameters to selection genres and/or decades to select from?

**Comment by SebastiaanZ** [comment]
Sounds like a great idea to me!

**Comment by AvianAnalyst** [comment]
Awesome, also are there guidelines on anthems in other languages? I was thinking since it's an English only server, keep it to English songs, but also I don't want to exclude others?

**Comment by Suhail6inkling** [comment]
I'd say leave them to English songs but if you find really good foreign songs, make "foreign" or "Spanish" parameters for different languages?

**Comment by AvianAnalyst** [comment]
Ok cool, I like that idea, thank you!

**Comment by AvianAnalyst** [comment]
What about explicit songs? Cursing seems to be allowed in the surver, so I'm not sure if I should mark it at all or not? Maybe leave it for a future feature to implement.

**Comment by SebastiaanZ** [comment]
That's a good question. I think it depends a bit on what kind of "explicit" material it is. In general, everything on our server must be SFW. That's not only our policy, but also the policy laid out in the Discord Partnership Code of Conduct.

We're not too pedantic about cursing that's not inherently discriminatory/offensive/derogatory or directed at another member. We don't moderate "fuck", unless it's meant as an insult for another member (but then it's the intent that matters).

The best approach is probably to err on the side of caution. If you think something may not be considered SFW, then don't include it. However, I'm less worried about a couple of swear words in a song.

**Comment by SebastiaanZ** [comment]
@AvianAnalyst Did you get anywhere with this?

**Comment by AvianAnalyst** [comment]
I have a decent list of songs compiled. (I do need to go through them and take out a few that are explicit.) But I've been struggling with implementing it as far as understanding how the bot works at all, and how to implement a command.

**Comment by SebastiaanZ** [comment]
@AvianAnalyst Maybe we can look into it together, although I'm not if our time zones match. Mention me in the seasonalbot channel on Discord and we can talk about it.

**Comment by AvianAnalyst** [comment]
Ok, thank you! I'm UTC-04:00 right now, but I tend to be up around noonish to 3ish am my time. So I'm going to sleep tonight. but Ill try to catch you tomorrow!

**Comment by AvianAnalyst** [comment]
Alright, I've finished with this, just waiting to get mod approval on a couple songs  before opening a PR. 

I was wondering, do you think it'd be useful to have an argument to add a pride anthem from discord, that's maybe role locked? Or better to just add them manually through the source?

**Comment by Xithrius** [comment]
@AvianAnalyst Greetings! I hope you're doing well.

I know this is 2 years later, but are you still interested in making a PR? I'd like to see this get implemented.

**Comment by AvianAnalyst** [comment]
Hey! This actually got implemented in PR #227, there's certainly room to implement feature additions, but it's in there! It's just only active during June iirc. You can search for 'prideanthem' to find examples of it being used!

**Comment by Xithrius** [comment]
Thanks for the quick response! Have a good one!
