### ISSUE TITLE
[Feature Request] Make prideavatar support specifying image URLs in addition to avatars

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/sir-lancebot#224]
Why limit the command to avatars only? It can be easily adapted to work with any image!

## Implementation details

- [ ] Create a `.prideavatar image` subcommand which accepts an image URL as the first argument. The rest of the arguments should be identical to the base `.prideavatar` command.
- [ ] Properly account for invalid URLs, invalid images, or images which otherwise fail to be retrieved.
- [ ] Come up with an implementation that re-uses code between the two commands rather than duplicating the code with minor tweaks.

## Additional information

It's probably best to wait until #223 is merged before beginning work on this.

**Comment by JackyFWong** [comment]
Hi, can I work on this?

**Comment by MarkKoz** [comment]
@JackyFWong sure

**Comment by WillDaSilva** [comment]
If @JackyFWong is not opposed, I'd like to implement this.

**Comment by JackyFWong** [comment]
Hi @WillDaSilva, I think it's completely fine if you would like to implement this. To be honest, with university going online and 2 jobs, I've forgotten about this. Sorry to the seasonalbot folks about ignoring this!

**Comment by Den4200** [comment]
No problem @JackyFWong, I hope your studies are going well!

@WillDaSilva, I've assigned you.
