### ISSUE TITLE
[Feature Request] Connect Four!

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/sir-lancebot#244]
![Connect Four](https://user-images.githubusercontent.com/33516116/62415879-5196c980-b631-11e9-9648-f727fa792d50.jpg)

When it comes to tabletop-style games, you can't go more retro than [Connect Four](https://boardgamegeek.com/boardgame/2719/connect-four)! In this game, you drop disks in your color into a grid hoping to get four of your disks in a row before your opponent manages to do just that.

For this feature, program a Connect Four game for our bot in which two players can compete with each other. The user interface should consist of reactions that lets the player indicate in which row they want to drop a disk. Make sure that it all works with one embed that gets updated instead of generating a new embed for each turn.

Example of what it could look like:

![Connect Four example embed](https://user-images.githubusercontent.com/33516116/62415997-46449d80-b633-11e9-9881-a8853d5fa903.png)

## Implementation details

- [ ] Write a command that starts a game, allowing a second user to join;
- [ ] Find a nice way to display the current state of the grid;
- [ ] Implement the game logic with a reaction interface and make sure it checks for winners;
- [ ] (Optional) Add a feature to allow a player to play against the bot (simple AI).

Make sure that you use a single embed for each game by editing it instead of creating a new embed for each turn. In addition, if you want to implement an AI for the game and want an example, there are implementations available online. Try to create your own version of it, but don't make it "perfect"/unbeatable.

## Additional information

- **Add your feature to the [__evergreen__](/python-discord/seasonalbot/tree/master/bot/seasons/evergreen) season.**
- Keep us updated on your progress by leaving comments!
- Make sure to give you commits a descriptive commit message
- Please note the style guide and conventions listed in the various contrib documents
- If you want to include graphics, make sure they have a permissive license

**Comment by Suhail6inkling** [comment]
I wanna work on this if that's okay

**Comment by spyoungtech** [comment]
I have a simple ConnectFour implementation I made a few years back: https://github.com/spyoungtech/connectfour

The `Board.show` method and prints could be changed to send the same in discord messages.

**Comment by SebastiaanZ** [comment]
@Suhail6inkling Sounds good to me. Decide for yourself if you want to use (parts) of @spyoungtech's code or take inspiration from it. Programming it yourself from scratch may be part of the fun, but inspiration can't hurt either.

**Comment by MarkKoz** [comment]
Hi @Suhail6inkling, can you give us an update on your progress with this?

**Comment by Suhail6inkling** [comment]
Adding the finishing touches on this and should be all done! hopefully will PR within the week

**Comment by martinwjwilson** [comment]
If this hasn't been done yet I'm happy to do it

**Comment by Suhail6inkling** [comment]
Hey! I know I'm a bit late to this (and I'm sorry for not replying) but I actually did almost finish the code for this so is it okay if I still work on this?

**Comment by ks129** [comment]
I'm gonna work with it.
