### ISSUE TITLE
[Feature Request] Spook Name Rate Game

### ISSUE THREAD

**Issue by kosayoda** [python-discord/sir-lancebot#277]
It's the Spook Name Rate Game! Try saying that multiple times in a row...
The bot will generate a random first+last name from a database/list of names, and the players will have to come up with a halloweenified version of that name! After a certain period of time, the bot will gather up all the entries and put up a poll! Winner gets a hearty congrats and a pat on the back!

## Implementation details

- [ ] Randomly pick first and last name
- [ ] Announce the name to spookify
- [ ] Players will enter their spookified name using a command
- [ ] After X amount of entries or X amount of time, list out the entries in a new message
- [ ] Players can then vote using the reactions given
- [ ] After X amount of time or X amount of votes on one entry, the winner is announced

## Additional information
- One entry per player
- One game at a time in a channel
- Make sure there are enough reactions for the number of entries
- Make a minimum number of reactions for the game to continue
- Optional: Store a leaderboard
- Optional: Store the winning entries and implement a command to list them

**Comment by Greenfoot5** [comment]
Would it be better to use a wait_for and then their next message in that channel, is their entry. Rather than command?

**Comment by Greenfoot5** [comment]
I'd like to work on this one.

**Comment by RohanJnr** [comment]
just wondering if we could make this like a global event rather than channel wise.
The bot sends the name in the off topic and event channels at once and people can come up with a halloweenified version of it.

**Comment by Greenfoot5** [comment]
Would you then put that on a timer, so it triggers every hour say?

**Comment by RohanJnr** [comment]
Kinda, let's see what others think of this

**Comment by MarkKoz** [comment]
@Greenfoot5 Are you still interested in this issue? If so, feel free to start working on it and let us know so you can be assigned to the issue.

**Comment by Greenfoot5** [comment]
I am, yes. I've done a little. I'll make sure to finish it and add it in.

**Comment by Vthechamp22** [comment]
If no one wants to do this any more, can I get assigned to this?

**Comment by Senjan21** [comment]
I have assigned you, feel free to work on it @Vthechamp22

**Comment by Vthechamp22** [comment]
Thanks @Senjan21 !

**Comment by Vthechamp22** [comment]
> Would you then put that on a timer, so it triggers every hour say?

In about how much much time should the event trigger? Every day? Twice every day? Every two hours?

> just wondering if we could make this like a global event rather than channel wise.
The bot sends the name in the off topic and event channels at once and people can come up with a halloweenified version of it.

I was thinking it could be a thing only for the `#seasonalbot-commands` channel?

**Comment by Vthechamp22** [comment]
and, I made the command as `.ratethespook`, is it fine?

**Comment by Vthechamp22** [comment]
> Would it be better to use a wait_for and then their next message in that channel, is their entry. Rather than command?

I added a command for adding a spookified entry, since the user may not be wanting to make an entry, or may want to discuss about something else in that channel
