### ISSUE TITLE
Update Candy Collection Cog for Persistent Storage

### ISSUE THREAD

**Issue by sco1** [python-discord/sir-lancebot#284]
PR #273 introduced persistent storage for our cogs, allowing for things like leaderboards to remain in between bot restarts. The [candy collection cog](https://github.com/python-discord/seasonalbot/blob/master/bot/seasons/halloween/candy_collection.py) needs to be updated to utilize this functionality.

The utility code itself can be found here: https://github.com/python-discord/seasonalbot/blob/master/bot/utils/persist.py

With Hacktoberstats as an example:

https://github.com/python-discord/seasonalbot/blob/526dbc465c2d458c893c72b614282937d15190d7/bot/seasons/halloween/hacktoberstats.py#L24-L26

**Comment by Niladri24dutta** [comment]
@sco1 Can I work on this? it seems we need to add a new class member like `link_json` to replace the `json_location` being used in this code https://github.com/python-discord/seasonalbot/blob/master/bot/seasons/halloween/candy_collection.py#L15 and use the utility for persistent storage. Let me know if my understanding is correct.

**Comment by scragly** [comment]
Sounds about right.

Are you a member of the discord server? If so, can you please let us know your in-server username. Thanks.

**Comment by Niladri24dutta** [comment]
@scragly I have not signed up in discord till now , I will send you my username once done.

**Comment by scragly** [comment]
@Niladri24dutta Sure, just keep in mind it's a requirement for any of our community repositories (seasonalbot, bot and site), so this will have to be kept available for others until that time. Hope to see you in the server sometime soon!

**Comment by Niladri24dutta** [comment]
@scragly  thanks in the mean time can you please assign this issue to me?

**Comment by Niladri24dutta** [comment]
> 
> 
> @Niladri24dutta Sure, just keep in mind it's a requirement for our seasonalbot repository, so this will have to be kept available for others until that time. Hope to see you in the server sometime soon!

I have joined the discord server and posted in the channel #event-hacktoberfest-2019. My username is nil2441139

**Comment by sco1** [comment]
@Niladri24dutta any luck?

**Comment by Daemo00** [comment]
Hi all, I found this looking for a 'good first issue' (this is the only one).
After some research, I found out that maybe this can be closed because of https://github.com/python-discord/sir-lancebot/commit/5e249bc2e0a944d0683ba35a2e1ee459d60668ce ?

**Comment by HassanAbouelela** [comment]
Yeah, this no longer seems to be an issue. I'm sorry there wasn't an issue marked to work on, but if you are still interested, drop into the [dev-contrib channel](https://discord.com/channels/267624335836053506/635950537262759947/807392255768789013) on the discord server, and we could look for issues you can work on 😄.
