### ISSUE TITLE
Tic-Tac-Toe command

### ISSUE THREAD

**Issue by nekitdev** [python-discord/sir-lancebot#300]
`.ttt` or `.tictactoe` command lets users play tic-tac-toe using reactions, either player vs player or player vs AI-like program.

## Implementation details

List the changes required for the implementation here.

- [ ] Write the bot command (a new cog)
- [x] Draw beautiful x, o emojis
- [x] Add required emojis
- [ ] Add the command to our README.md

## Additional information

Emojis have been created:

```
:empty_square: - 632278399296995361
:x_square - 632278427260682281
:o_square - 632278452413661214
```

![x](https://user-images.githubusercontent.com/43587167/66564376-8743bb80-eb68-11e9-95a1-c91e3921831f.png)
![o](https://user-images.githubusercontent.com/43587167/66564383-8ad74280-eb68-11e9-9337-7327d031f425.png)

**Comment by RohanJnr** [comment]
Should be an awesome feature

**Comment by RohanJnr** [comment]
Perfect addition

**Comment by NeKitDS** [comment]
I am really busy irl, so really unsure when I can finish the cog :/

**Comment by NeKitDS** [comment]
Sadly unable to finish this. Sorry.

**Comment by NeKitDS** [comment]
Sure thing. Good luck to anyone working on this!

**Comment by ks129** [comment]
Can I work on this?

**Comment by kwzrd** [comment]
This looks like a fun feature, but what is the proposed control scheme?

Given a 3x3 board, how will users select which field they would like to place their mark on? The issue mentions `using reactions` - the bot could populate the board with the `1`, `2`, ... emojis, and slowly replace them with Xs and Os as they are placed, but then I'm consufed about the `:empty_square:` emoji.

Adding an optional AI player for this would be pretty cool, too!

**Comment by NeKitDS** [comment]
Hey everyone! Glad someone came to working on this. The idea of `:empty_square:` is to fill the spaces which don't have `X` or `O` at their places yet. Originally I thought about using `1-9` for controls, but arrow emojis also seem like a way to go. Good luck on this one! <3

**Comment by ks129** [comment]
My idea was use messages for controlling, like `1 1` will use top left. These messages will be deleted.

**Comment by NeKitDS** [comment]
Well, that also works, but imho reactions would be better.

**Comment by kwzrd** [comment]
> @ks129: My idea was use messages for controlling, like 1 1 will use top left.

I prefer @NeKitDS 's approach, I cannot imagine this being very user-friendly. You'd have to explain whether indices begin at 0 or 1, and whether origin is bottom-left or top-left. With arrows, most will instantly understand what to do, so it'll lead to much better UX.

Discord provides the full set of arrows necessary, including diagonal (e.g. `:arrow_lower_left:`), so with NeKit's `X`'s and `O`'s we're almost good to go: just need to figure out what to use for the middle field.

My idea was to have the board setup as follows:
```
1 | 2 | 3
4 | 5 | 6
7 | 8 | 9
```
The bot then adds reactions `1` through `9`, and awaits a response. User `X` clicks `4`, and the board gets updated:
```
1 | 2 | 3
X | 5 | 6
7 | 8 | 9
```
The next set of reactions will no longer include a `4`.

NeKit's approach is, however, fine too. I will assign you now. Please pick either NeKit's approach with arrows or this one with numbers.
