### ISSUE TITLE
AoC: Leaderboard per star

### ISSUE THREAD

**Issue by Skaft** [python-discord/sir-lancebot#321]
We currently show two types of statistics for the participants of Advent of Code:

- The leaderboard; a cumulative rundown of each players' progress
- The number and percentage of users who has completed each star

Some more granular statistics would be cool to see. I suggest an alternative leaderboard, which shows scores for a specific star only, and times instead of score (like the [daily breakdown of the global leaderboard](https://adventofcode.com/2019/leaderboard/day/1)). 

For example, `.aoc leaderboard 2-1` to get a top-10 (or optionally a different length) list for the 2nd day's 1st star:

> Top 5 solvers for star 1, day 2:
06:02 Ikusaba-san
07:44 WillDaSilva
08:46 smartspot2
09:50 Sedsarq
10:11 salt-die

The timestamps per user and star is stored in the [JSON](https://adventofcode.com/2019/leaderboard/private/view/631135.json) we grab from the site, but it looks like we're currently not using them.

I'll refrain from providing implementation details, being the rookie that I am - don't want to make bad suggestions!

**Comment by janine9vn** [comment]
@Skaft Hey, are you still working on this? It's a great idea and I'd love to have it for AoC this year.

**Comment by Skaft** [comment]
Apologies for abandoning this, after missing the first deadline of having it included in the 2019 event I kinda lost interest =/ I've since lost my progress on it, so I'd be happy for someone else to pick it up.

**Comment by D0rs4n** [comment]
I'd like to grab this issue!
