### ISSUE TITLE
Personal stats with something like !aoc mystats

### ISSUE THREAD

**Issue by LeptoFlare** [python-discord/sir-lancebot#325]
Instead of needing to go on the website to check your stats, you can use the bot!

## Implementation details
- Show your placement in the private leaderboard
- Show the stars you attained
- Show points that you have
- Suggestions?

- [ ] Write the bot command
- [ ] Add the command to our README.md

## Additional information
You can find your own stats here: https://adventofcode.com/2019/leaderboard/private/view/631135
by doing `ctrl-f`. But you can also look at your personal global stats here: https://adventofcode.com/2019/leaderboard/self

There are the best places to look when finding things to put on the embed.

**Comment by Skaft** [comment]
Just checking in if you've gnawed at this one at all? It seems related to #321 which I started on. 

Seeing your issue, I had a thought that the per-star data that I'm setting up could be used to show things like your average time per star, which stars you did best on, maybe a personalized graph of the rankings you got over the days. 

I think it would be cool with data like that, which isn't immediately visible from the site. Although ranking, points and star-count are easy to throw in as well.

**Comment by LeptoSpira** [comment]
Was I supposed to? I was expecting someone else to take care of it

**Comment by sco1** [comment]
It's polite to ask if whoever opens the issue hasn't specified if it's something they would be interested in implmementing, to avoid duplicate work.

**Comment by Xithrius** [comment]
Hello @LeptoFlare, it seems the other user has become inactive. Would you like to take over this?

**Comment by LeptoFlare** [comment]
Hey! I haven't worked with the bot in a while, but I'd to see if I can take a crack 😄

**Comment by Xithrius** [comment]
Alright, cool! Be sure to include features mentioned in https://github.com/python-discord/sir-lancebot/issues/321 as well.

**Comment by LeptoFlare** [comment]
Regarding features in #321, some of them I don't think I'd be able to implement as they seem out of the scope of this issue. I'll try my best though

**Comment by Xithrius** [comment]
@LeptoFlare Will you be able to continue the development of this feature?

**Comment by LeptoFlare** [comment]
I am looking to complete this during October !

**Comment by Xithrius** [comment]
@LeptoFlare Thanks!

**Comment by D0rs4n** [comment]
If the issue is up for grabs, I would like to give it a try.
