### ISSUE TITLE
Allow Users to React to a Bookmark to Recieve a Copy

### ISSUE THREAD

**Issue by sco1** [python-discord/sir-lancebot#341]
Spun off of conversations in https://github.com/python-discord/seasonalbot/issues/338#issuecomment-578322144 and https://github.com/python-discord/seasonalbot/pull/340#pullrequestreview-348784550:

@kwzrd:
> I've also seen a suggestion that the bot could listen for further clicks on its 📨 reaction, and dispatch the bookmark to those who click as well. This would be a super clean way to ask to be given the bm as well, although it may not be very obvious that it does that.

@AG4lyf made a good initial implementation in #340 that exposed some UX concerns:

@sco1:
> Regarding the reaction by others to receive the same bookmark: the implementation details need to be discussed more before the feature is merged.
> 
> I don't think it makes sense from a UX perspective to utilize the same reaction for multiple purposes when one of those purposes silently disappears after a timeout. This is already barely discoverable functionality, and with this implementation a user that does know of its existence doesn't know if it has timed out or if it's broken. A second emoji solves half of the problem, which might be sufficient.

Since this implementation discussion shouldn't block the fix being implemented by #340, it has been removed from the scope of that PR.

Per discussions in Discord, the initial feeling is to provide a separate reaction to expose this functionality & keep it distinct from the bot's feedback that the DM has been sent. :pushpin: or :round_pushpin: have been suggested.

Also to be discussed is whether or not this should be implemented as either:
* A `wait_for` reaction loop, with a timeout that removes the reaction
* An `on_reaction_add` event handler with a persistent cache that links the bookmark invocation message and the target message.

The former is simpler to implement & is what I'm leaning towards. The latter is more generic but will be trickier to implement in a way that prevents the file from growing too large & limit vectors for trolling.

The reaction emoji and reaction handling approach should be decided on prior to work being done.

**Comment by AG4lyf** [comment]
assign me

**Comment by AG4lyf** [comment]
I purpose a timeout system that remove all reaction and then put the incoming_envelope in the end . so that on_reaction does not cluster even if its temp.

**Comment by SebastiaanZ** [comment]
Do you just mean the following?

> - A wait_for reaction loop, with a timeout that removes the reaction

**Comment by AG4lyf** [comment]
> Do you just mean the following?
> 
> > * A wait_for reaction loop, with a timeout that removes the reaction

yes

**Comment by kwzrd** [comment]
Issue is now available if anyone wants to work on it.

Contributions should take into account reviewer feedback from the two PRs:
https://github.com/python-discord/seasonalbot/pull/349
https://github.com/python-discord/seasonalbot/pull/386

**Comment by Akarys42** [comment]
Hi, can I work on this issue and #338? :grin:

**Comment by kwzrd** [comment]
@Akarys42 Sure, go for it. I've assigned you on both.

**Comment by ChrisLovering** [comment]
My thoughts on this is to change the `.dm` command to have the bot output a small embed with the context along the lines of `<user> has bookmarked <message> from <author>. React with 📌 to also bookmark this message.`.

We use redis to store these embed messages linked to the bookmarked messages and a reaction add listener which checks the cache when a pin is added to a message.

**Comment by ChrisLovering** [comment]
An alternative is to use a wait_for to listen for reactions for ~5 mins and then delete the bot's embed.

**Comment by ChrisLovering** [comment]
I'd like to give this a go. Even though this is already approved, I just want to confirm my plans.
- When someone calls `.bm` on a message the bot will:
   - Send a DM as normal (with the same error embed if DMs are disabled)
   - Send 1 sentence embed explaining that you can react to the embed and also get sent a DM with a link
   - Have a 5 min wait for listening for reactions
   - On reaction, the bot will send the bookmark DM to the reactor

**Comment by Kronifer** [comment]
that sounds great! however, i think we could use the reaction that is already added to the command.

**Comment by ChrisLovering** [comment]
My plan is to remove that reaction entirely, since it wouldn't be needed with this idea.

The reason for not using the reaction that's already there is due to it not being an obvious way to interact with this new system.

**Comment by Kronifer** [comment]
Oh! In that case, sounds good!!
