### ISSUE TITLE
Replace requests with aiohttp in Scary Movie Generator

### ISSUE THREAD

**Issue by gables** [python-discord/sir-lancebot#38]
## Description

The scary movie generator cog (PR #23) was written using requests, which can cause blocking with asyncio.  The api calls to TMDb need to be made using aiohttp instead.

Thanks @meooow25 !

**Comment by rgables** [comment]
I'll work on this tomorrow

**Comment by LordHemlock** [comment]
We'll need to make sure that aiohttp is properly added to the pipfile so that it gets installed properly when we deploy the bot.

**Comment by sco1** [comment]
aiohttp is a requirement for d.py

________________________________

**Comment by LordHemlock** [comment]
Doh.  Right.

**Comment by heavysaturn** [comment]
the bot breaks quite spectacularly without this so I don't think we can wait for it.
