### ISSUE TITLE
Logging Level Adjustments

### ISSUE THREAD

**Issue by sco1** [python-discord/sir-lancebot#384]
With the updated definition on logging levels (see: #378), there are a few events that are potentially issuing logs at too high of a level, alerting the DevOps team for things that aren't actionable, or at too low of a level.

Since a lot of things are changing with #329, will defer this until that work is completed.

**Comment by kwzrd** [comment]
I was wondering whether this should be included in #329. But I agree that it's better deferred until that's done, and approached as a separate issue. All new code I'm writing is (hopefully) using sensible log levels.

**Comment by sco1** [comment]
There aren't that many, so there isn't much issue doing it in #329, I just didn't want to do it in the middle of all the other changes

**Comment by ChrisLovering** [comment]
Since #329 is closed now, I presume this can be worked on?

If so, I  don't mind working through all the `logging` calls and making sure they match up to the definitions :)

**Comment by Xithrius** [comment]
@ChrisLovering looks like this can be worked on. Would you like to go ahead?

**Comment by ChrisLovering** [comment]
I don't think this is relevant any more, we change the log levels as needed if we a sentry report come in at a wrong level.

**Comment by Xithrius** [comment]
Alright then. Thanks for the information.
