### ISSUE TITLE
Update help command

### ISSUE THREAD

**Issue by ks129** [python-discord/sir-lancebot#412]
## Description

python-discord/bot#519 got merged some days ago so these changes should get merged to here too.

## Reasoning

Because current help command is basically Python bot help command, just some small changes.

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by scragly** [comment]
This issue has been usurped by #470 due to more recent activity and being more detailed.
