### ISSUE TITLE
Make pridavatar command work correctly with GIF avatars

### ISSUE THREAD

**Issue by doodspav** [python-discord/sir-lancebot#416]
## Description
Right now the `.prideavatar <ring>` command works with all avatar image formats, but only produces PNG images. The proposed change would modify this command to produce GIFs if the avatar format is a GIF. This change could potentially be implemented for other commands that modify the avatar, however I haven't tried any others.

## Reasoning
It would be nice if commands that formatted your avatar worked completely with all avatar formats (especially ones which you need to pay extra to use).

## Proposed Implementation
- Detect if the image is png or gif (to know what to save it as)
- Use ImageSequence to modify image (works with PNG and GIF)

## Additional Details
This may be marginally slower - I have not tested it for performance. Hopefully it shouldn't be an issue.

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [X] Anyone can implement this feature

**Comment by MarkKoz** [comment]
Good suggestion. In fact, I was just thinking about this issue the other day.

**Comment by doodspav** [comment]
I thought I had something that worked, but turns out GIFs in PIL decay to Image as easily as c-arrays decay to pointers :/ (Pretty much any conversion from the original file will turn the GIF into an Image). So this might take me a little longer than I thought.

**Comment by MarkKoz** [comment]
Since you're working on it, I'll assign you to the issue.

**Comment by Xithrius** [comment]
As of #584 getting closed, we can't really work on GIFs given the possibility of them being very long.

CPU usage is also a problem, as this would definitely take up a large portion of it.

Maybe we can do this in the future, but for now we'll have to put it off until we can afford more computations.
