### ISSUE TITLE
Optional user arguments

### ISSUE THREAD

**Issue by slushiegoose** [python-discord/sir-lancebot#425]
## Description
Take optional user arguments for `.8bitify` (#247), `.prideavatar` (#209), `.avatareasterify` (#187) plus any other commands that I am missing, so that the avatars can be made of specific users rather than the message author

Since I created all 3 commands, I would like to work on this one too (since it shouldn't take long)

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by ikuyarihS** [comment]
@slushiegoose do you still want to work on this issue?

**Comment by slushiegoose** [comment]
sure

**Comment by wookie184** [comment]
The spookyavatar/savatar command currently accepts an optional user input, but it doesn't actually seem to use that for the image, using the message author instead anyway, so this could also be fixed. Relevant line: https://github.com/python-discord/seasonalbot/blob/ba6536cf2011dc52d1e103407d75aa699975656b/bot/exts/halloween/spookyavatar.py#L39

I think you can count this as approved and start working on it if you want to.

**Comment by Xithrius** [comment]
@slushiegoose are you still planning on making a PR for this?

**Comment by brad90four** [comment]
Would this change need to be made in [sir-lancebot/bot/exts/evergreen/avatar_modification/avatar_modify.py](bot/exts/evergreen/avatar_modification/avatar_modify.py) ? I would assume the changes would be to the different functions defined there. 

.8bitify : [link](https://github.com/python-discord/sir-lancebot/blob/32b6d0e386350ea12ab9e745e2bede844d289d07/bot/exts/evergreen/avatar_modification/avatar_modify.py#L94)
.prideavater: [link](https://github.com/python-discord/sir-lancebot/blob/32b6d0e386350ea12ab9e745e2bede844d289d07/bot/exts/evergreen/avatar_modification/avatar_modify.py#L208)
.easterify : [link](https://github.com/python-discord/sir-lancebot/blob/32b6d0e386350ea12ab9e745e2bede844d289d07/bot/exts/evergreen/avatar_modification/avatar_modify.py#L123)

**Comment by janine9vn** [comment]
@Xithrius This issue should be closed as we decided to not allow user input for these images anymore.
cc: @ChrisLovering

**Comment by ChrisLovering** [comment]
yes agreed, the parts of commands that allowed this have been thrown into the sun

**Comment by ChrisLovering** [comment]
To expand on this for others: This was a moderation decision that is two-fold.
1. We will no longer allow users to run commands on any other members, unless the other member has opted into it (see the valentines command)
2. We no longer allow arbitrary user inputted images to be rendered and parroted by the bot

**Comment by Xithrius** [comment]
@janine9vn Thank you. I will proceed to throw this issue into the sun.
