### ISSUE TITLE
Statuscat 418 doesn't work

### ISSUE THREAD

**Issue by MrAwesomeRocks** [python-discord/sir-lancebot#428]
## Description
Http code 418 is reported to be invalid, even though its defined [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/418). A [cat](https://http.cat/418.jpg) exists for the status code too.

## Steps to Reproduce
Send `.statuscat 418` to Seasonalbot.

## Expected Behaviour
Sends an embed with [this](https://http.cat/418.jpg) image in it, and a header of `Status: 418`.

## Actual Behaviour
Code not found:
![image](https://user-images.githubusercontent.com/42477863/90422575-b0828180-e080-11ea-862d-0df2e7010b29.png)

## Known Impacted Platforms

- [x] Web
- [x] Desktop
- [x] Android App
- [x] iOS App

## Possible Solutions
Check for status code 418 before checking for the other codes the http library.

## Would you like to implement a fix?

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [x] I'd like to implement the bug fix
- [ ] Anyone can implement the bug fix

**Comment by Numerlor** [comment]
The status codes are verified by looking into the builtin [http](https://docs.python.org/3/library/http.html#http-status-codes) module; I don't think it's worth defining any special behaviour for that and keeping our own database of them as [python 3.9](https://docs.python.org/3.9/whatsnew/3.9.html#http) will update the builtin codes to include 103, 418 and 425

**Comment by MrAwesomeRocks** [comment]
We could just add 103, 418, and 425, or maybe only just the 418 status code. Its just an if/else block for just one code, and if/elif/elif/else if we added all three.

**Comment by MrAwesomeRocks** [comment]
Or it could be done with just one if/else checking if the code is one of the three that haven't been added yet.

**Comment by Akarys42** [comment]
As @Numerlor said, we can just wait for Python 3.9, there isn't really any urge for it right now.

**Comment by quanta-kt** [comment]
`http.cat` urls respond with HTTP status 404 if a cat image does not exist. It could be used instead of checking the status validity using the stdlib.

**Comment by jb3** [comment]
Honestly that doesn't sound that bad. We can do some integer validation, checking that a user isn't looking for dodgy stuff, and otherwise let that handle all the validation. There is no reason why new status codes will not be implemented, and will take longer to get into stdlib than they do http.cat.

**Comment by Den4200** [comment]
That sounds like a good idea to me. Would you still like to implement this
fix @Anubhav1603?

**Comment by ChrisGallardo** [comment]
I mentioned some fixes in #500.

**Comment by ChrisGallardo** [comment]
Maybe you want to check those out too.

**Comment by Anubhav1603** [comment]
@Den4200  sure I would like to implement this feature :)

**Comment by ChrisGallardo** [comment]
> As @Numerlor said, we can just wait for Python 3.9, there isn't really any urge for it right now.

@Akarys42 when will that be?

**Comment by Anubhav1603** [comment]
@ChrisGallardo  i still think my proposed idea can solve this

**Comment by Akarys42** [comment]
We will update to 3.9 when the libraries we are using will be ready and at least one patch of CPython will have been released. Be patient. 🙂

**Comment by scragly** [comment]
This issue has been usurped by #608, and a solution is already in place.
