### ISSUE TITLE
Docstring on 8bitify doesn't match actual code

### ISSUE THREAD

**Issue by nitori** [python-discord/sir-lancebot#431]
https://github.com/python-discord/seasonalbot/blob/d77a2bbc50305d05371197f4cfe3354cfca4c627/bot/exts/evergreen/8bitify.py#L20-L22

A bit nitpicky, but after being curious on how it works, I looked it up and saw this little discrepancy.

Docstring says 256 colors (8-bit), but it actually only uses 32 colors (5 bit?). Either of those should probably be adjusted to match the other?

**Comment by jayson-310801** [comment]
I would like to work on this issue
