### ISSUE TITLE
Bot not able to catch answers typed in bursts

### ISSUE THREAD

**Issue by aaravm4** [python-discord/sir-lancebot#437]
## Description

I was using the `.quiz` command with the Seasonal Bot, and the question was **When did World War I start?** I put a bunch of years between 1910 and 1920 one after another and I had typed the correct answer **1914** but the Bot wasn't able to detect that even though it said the correct answer was **1914**.

## Steps to Reproduce

You can look at the quiz [thread](https://discordapp.com/channels/267624335836053506/607247579608121354/755092200412545084)

I basically just typed a bunch of years one after another.
A screenshot is attached:
![Screenshot](https://user-images.githubusercontent.com/40776764/93136710-fe9b9c80-f6a1-11ea-959f-74f32acf1952.png)

## Expected Behaviour

The expected behaviour would be that it would say I got the correct answer when I had typed 1914.

## Actual Behaviour

The actual behaviour was that it didn't detect my correct answer.

The quiz [thread](https://discordapp.com/channels/267624335836053506/607247579608121354/755092200412545084)

## Known Impacted Platforms

- [ ] Web
- [x] Desktop
- [ ] Android App
- [ ] iOS App

## Would you like to implement a fix?

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [ ] I'd like to implement the bug fix
- [x] Anyone can implement the bug fix

**Comment by ramansrivastava** [comment]
hey i am new here and want to contribute here what should i do?

**Comment by Xithrius** [comment]
@ramansrivastava would you still be willing to work on this? I'm not completely sure if this bug still exists.

**Comment by Xithrius** [comment]
I've seen people spam on purpose and I've tried reproducing myself, the bug no longer seems to exist.
