### ISSUE TITLE
Wikiguess game

### ISSUE THREAD

**Issue by gustavwilliam** [python-discord/sir-lancebot#446]
## Description

A new `.wikiguess` game, where you get points for guessing the correct article name.

This would be a typical game:
- Send `.wikigame` or `.wikigame start` to start a new game.
- Get an embed with instructions about the game (click green reaction tick box to start game)
- X (5?) rounds are done
- The user receives a score

This is how a normal round would look:
- Get the first few sentences from a not too uncommon Wikipedia article
- Get X (10?) seconds to answer what the article is called
- Get result for the round ("was it correct?")

We could *possibly* have a multi player mode as well, where players compete to guess it first.

## Reasoning

This would be a quite fun game to play for people in the community. They may even find some new and interesting topics to check out, since the articles will be linked on the bottom of the pages.

## Proposed Implementation

- Checking if the inputted article is the right one would be done with fuzzy matching, so "Donald Trumpp" would be accepted for "Donald J. Trump" (intended typo)
- The game would probably be played in #seasonalbot-commands. A DM version *could* be available as well, with an option to let moderators choose which one is available, if it gets spammy
- The articles to choose from would be hand picked, in order to keep them free from inappropriate topics
- First sentences may or may not be requested from Wikipedia during the game, or be cached from when they were picked. Preferably live fetching

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

If anyone would like to implement it, though, I'm not strictly against it.

**Comment by Vthechamp22** [comment]
Can I try to implement it? I think I will start with just a single player in #seasonalbot-commands though.

**Comment by gustavwilliam** [comment]
I'd like to implement this command myself. There are plenty of other issues to work on, though 😄

**Comment by Vthechamp22** [comment]
So can I do it? I have already started implementing it, with ability to play with more than one player too.

**Comment by Anubhav1603** [comment]
@Vthechamp22,  @gustavwilliam  have already opted to work on this issue,so sorry

**Comment by Akarys42** [comment]
Hey @Anubhav1603, @gustavwilliam checked the "I'd like to implement this feature myself", besides you didn't even commented on this issue, it is up to vestergurkan to implement it.

**Comment by Anubhav1603** [comment]
> Hey @Anubhav1603, @gustavwilliam checked the "I'd like to implement this feature myself", besides you didn't even commented on this issue, it is up to vestergurkan to implement it.

I am saying same thing to @Vthechamp22, @Akarys42 😅,sorry if I was not clear

**Comment by Akarys42** [comment]
Alright @Anubhav1603, although please leave this job to core devs, thanks.

**Comment by Shivansh-007** [comment]
I will be taking over this issue, had a talk with @gustavwilliam.

**Comment by gustavwilliam** [comment]
I'm too busy to implement this myself, but let's wait for a core dev to assign you, before getting started.
