### ISSUE TITLE
Add cog that shows info about emojis

### ISSUE THREAD

**Issue by AtieP** [python-discord/sir-lancebot#461]
## Description
Add a command that displays relevant info about emojis, like name, ID, created_at, CDN link...

## Reasoning
People could get more information about the server emojis.

## Proposed Implementation
Simple: create a new command called `emoji_info` or something. It will get a second parameter called `emoji` typehinted with `discord.Emoji`. Then, proceed to show relevant info about the emote. discord.py itself will raise an error if the emote doesn't exist.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by gustavwilliam** [comment]
I think #454 could be added as a subcommand to this. It would be `.emoji count` or `.emoji list`, instead of a separate command.

**Comment by AtieP** [comment]
Yeah, I think that's okay. My proposed name for this subcommand is `info`.

**Comment by AtieP** [comment]
I'll work on this when #454 is closed.

**Comment by Anubhav1603** [comment]
I think `emoji count` and `emoji list` command will automatically cover #454  issue

**Comment by gustavwilliam** [comment]
@AtieP no real need to wait. I think it would be equally good — if not better — to work on this one before the other command is even complete.

@Anubhav1603 exactly. That's what I was referring to in my previous comment.

**Comment by AtieP** [comment]
okay time to work
