### ISSUE TITLE
Error traceback when using next/prev arrows with .help cmd

### ISSUE THREAD

**Issue by hedythedev** [python-discord/sir-lancebot#477]
## Description

This error traceback is printed every time I click on a reaction after running the help cmd

```
Ignoring exception in on_reaction_add
Traceback (most recent call last):
  File "/home/hedy/.local/share/virtualenvs/seasonalbot-S5lMGbTO/lib/python3.8/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "/mnt/c/Users/hedyh/codeproj/seasonalbot/bot/utils/decorators.py", line 79, in guarded_listener
    return await listener(*args, **kwargs)
  File "/mnt/c/Users/hedyh/codeproj/seasonalbot/bot/exts/halloween/candy_collection.py", line 76, in on_reaction_add
    if message.id in await self.ten_recent_msg():
  File "/mnt/c/Users/hedyh/codeproj/seasonalbot/bot/exts/halloween/candy_collection.py", line 138, in ten_recent_msg
    msg = await next(channel.history(limit=1, before=o))
TypeError: 'HistoryIterator' object is not an iterator
```

Note that this line `Ignoring exception in on_reaction_add` is because there was an error with loading the 🗑️ emoji. (Another error is printed too, but I ignored that)

## Steps to Reproduce

1. clone code in master in set up environement
2. `pipenv run start`
3. go to discord channel and use `.help`
4. click on ➡️ 

## Expected Behaviour

no trace back

## Actual Behaviour

trace back printed

## Known Impacted Platforms

(not sure about the other platforms because I cant test on those)
- [x] Web
- [ ] Desktop
- [ ] Android App
- [x] iOS App

## Possible Solutions

not sure

## Would you like to implement a fix?

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [x] I'd like to implement the bug fix (**but i don't really know why it's happening yet**)
- [ ] Anyone can implement the bug fix

**Comment by vivax3794** [comment]
The bug looks to be here: https://github.com/python-discord/seasonalbot/blob/master/bot/exts/halloween/candy_collection.py#L138

if I am not mistaken it is since that is the wrong use of `next()`, the traceback went away when the line was switched to: 
```python
msg = await channel.history(limit=1, before=o).next()
```

**Comment by hedythedev** [comment]
@vivax3794 if I do that flake8 tells me:
```
bot/exts/halloween/candy_collection.py:138:25: B305 `.next()` is not a thing on Python 3. Use the `next()` builtin. For Python 2 compatibility, use `six.next()`.
```

**Comment by SebastiaanZ** [comment]
It's a `flake8` false positive. When you call `channel.history`, you get an instance of `discord.iterators.HistoryIterator` back and that class does implement a [`next` method](https://github.com/Rapptz/discord.py/blob/f308f34db1b1c24178fbdb1756838064cd9e4348/discord/iterators.py#L258). You'll need to add an ignore/noqa for flake8 here.
