### ISSUE TITLE
8bitify attached images

### ISSUE THREAD

**Issue by ChrisGallardo** [python-discord/sir-lancebot#480]
## Description

Let the `.8bitify` not just work on avatars, but if the user uploads an image, 8bitify that instead.

## Reasoning

It would let users 8bitify more than just their avatar.

## Proposed Implementation

I think the ideal way to do this is to first check if the user passed any extra arguments to `.8bitify`, and if so, skip the getting the avatar and instead use the image URL they passed.

## Additional Details

Maybe also fix #431 while I'm at it.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by Akarys42** [comment]
We don't want to give the users the option to pass any sort of image to cogs, as it can result in inappropriate content to be used and passed through our bot. 
I'm afraid that's something we aren't going to support.

**Comment by ChrisGallardo** [comment]
Makes sense, I didn't think about that.
