### ISSUE TITLE
httpcat missing codes

### ISSUE THREAD

**Issue by ChrisGallardo** [python-discord/sir-lancebot#500]
## Description

The `.http_cat` command is supposed to send the picture associated with the status code the user enters. To check if the user has entered a valid status code, it checks if it is in the [`HTTPStatus` enum](https://docs.python.org/3/library/http.html#http.HTTPStatus).  The problem with this, is that three of the status codes, `103 EARLY_HINTS`, `418 IM_A_TEAPOT` and `425 TOO_EARLY`, are new to python version 3.9, though they are in [http.cat](https://http.cat/). We should fix it so that these codes can be used.

## Reasoning

More codes for the `.http_cat` command.

## Proposed Implementation

There are two ways I can think of implementing this. 

- Create a list of valid codes from  [http.cat](https://http.cat/).
- Or make a new class deriving from [`HTTPStatus`](https://docs.python.org/3/library/http.html#http.HTTPStatus) with the extra codes.

I think the first way would be easier to implement and maybe even slightly more performant.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by jb3** [comment]
http.cat returns a 404 cat for any code it does not know about, so maybe we should just do that?

We could check the argument is an integer and leave it at that, then we'll leave it up to http.cat to see whether the code is supported.

**Comment by ChrisGallardo** [comment]
I guess we could check if the code returns 404 cat, and if it does, and the code isn't 404 we send something saying the code doesn't exist and show 404 cat.

**Comment by Den4200** [comment]
Related to #428

**Comment by ChrisGallardo** [comment]
I'm closing this as it is a duplicate of #428.
