### ISSUE TITLE
Create rollover cooldown logic for wolfram alpha

### ISSUE THREAD

**Issue by thomaspet** [python-discord/sir-lancebot#513]
## Description

https://github.com/python-discord/seasonalbot/blob/44bc2efb37702758594f7218ae998fd725394773/bot/exts/evergreen/wolfram.py#L28

Keep track of how many uses we've had of the wolfram commands. The max usage should be listed in their documenation, and the daily user & guild cooldown should reflected on how much we have left in total divided by how many days until the next year. 

## Reasoning

Not a critical issue, just lets our users use the command more if we have days without much usage.

## Proposed Implementation

This can be achieved with a simple cache that resets with a bot restart, or a more persistent storage like json/db. (however it should not write to a file everytime the command is called)

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by Xithrius** [comment]
Unfortunately I'm not for this issue as we're usually against "gamifying" commands where a number can go up over time if a user triggers a command.

We only have a limited amount of API calls to Wolfram, and I'd rather not hit the ratelimits of such a powerful command.
