### ISSUE TITLE
Clean up constants.py

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/sir-lancebot#527]
## Description
`constants.py` has quite a bit of mess. There are constants we no longer use, there is a mix of regular classes and NamedTuples, and a lack of documentation. Let's clean it up.

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by Akarys42** [comment]
I think this should wait until the migration to `server-bootstrap`/`smartconfig`; what do you think?

**Comment by lemonsaurus** [comment]
Sure, I don't mind that.

**Comment by Xithrius** [comment]
Given that smartconfig may not be worked on until later this year, @HassanAbouelela would you like to have a crack again at cleaning up constants.py?
