### ISSUE TITLE
Migrate the Reddit channel to sir-lancebot 

### ISSUE THREAD

**Issue by Akarys42** [python-discord/sir-lancebot#530]
## Description
The current code for the [Reddit cog](https://github.com/python-discord/bot/blob/master/bot/exts/info/reddit.py#L257-L260) in the [Python bot](https://git.pydis.com/bot) is taking care of updating the `#reddit` channel. This should be migrated to Sir-Lancebot in order to remove the cog from Python. 

## Reasoning

For quite a while now, we have two `reddit` commands, on both Python and Sir-Lancebot, we shall annihilate Python’s version.

**Comment by RohanJnr** [comment]
I would like to work on this

**Comment by RohanJnr** [comment]
I will also be completing #348 along with this.
