### ISSUE TITLE
.aoc leaderboard show when last updated

### ISSUE THREAD

**Issue by ChrisGallardo** [python-discord/sir-lancebot#534]
## Description

Currently, the `.aoc leaderboard` command says "Here's our current top 9! :christmas_tree::christmas_tree::christmas_tree:". This is confusing because it is actually not the current top 9, because the leaderboard only updates every 30 minutes. This already led to a bit of confusion in the #advent-of-code channel. The leaderboard command should make it clear that it updates every 30 minutes so what it shows may not be accurate.

## Reasoning

Less confusion over the leaderboard.

## Proposed Implementation

Change "Here's our current top 9! :christmas_tree::christmas_tree::christmas_tree:" to "Here's our top 9 as of 30 minutes ago! :christmas_tree::christmas_tree::christmas_tree:"

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

I understand if I don't get to implement this as it is only a small text change and a pr may not be necessary.

**Comment by SebastiaanZ** [comment]
The info embed does already show you the last time the leaderboard has been updated:

![2020-11-30_16-46](https://user-images.githubusercontent.com/33516116/100631017-9321ac80-332b-11eb-8c57-ae96e28afba3.png)

**Comment by ChrisGallardo** [comment]
Oh completely missed that. Closing issue.
