### ISSUE TITLE
music bot

### ISSUE THREAD

**Issue by Dragon-Batch** [python-discord/sir-lancebot#537]
## Description
make a music bot that can play music from any website and any video

## Reasoning
it would be a great addition to python discord server because i know many people that like to listen to msuic while coding

## Proposed Implementation
i give code

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by SebastiaanZ** [comment]
Hello @Dragon-Batch,

Thank you for your interest in contributing to one of our open source projects. Unfortunately, we don't want to add the proposed feature to one of our bots or have such a feature available in our community.

One of the reasons is that most music bots violate both copyright laws as well as the terms of service of the websites/service they use as the source for the music they play. Another reason is that we don't want to have such bots in our voice channels: Our voice channels are typically already quite busy with conversations and we don't want to open more voice channels, as moderating voice channels is a challenge.

My suggestion to you is to play music locally on your computer while you're coding.

Kind regards,

Sebastiaan
