### ISSUE TITLE
Only display channels the user can see for InChannelCheckFailure

### ISSUE THREAD

**Issue by Numerlor** [python-discord/sir-lancebot#539]
When an user invokes a command in a channel seasonal bot doesn't have whitelisted, the bot will dump a list of all the channels the commands is allowed in as a part of the response; with the global whitelist most of those channels are not visible to regular users. The error embed gets deleted after a bit but is still quite large and pushes out the conversations in the channel

When constructing the channels string the bot can get the channels from its cache and check whether the user can see them through `channel.permissions_for` or `member.permissions_in`, filtering out the ones that are not visible to the author
https://github.com/python-discord/sir-lancebot/blob/02c5c7e2b120c055b7db07d2ca9568d1ae25c399/bot/utils/decorators.py#L234-L247
## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [X] Anyone can implement this feature

**Comment by Akarys42** [comment]
Superseded by #556.
