### ISSUE TITLE
Centralized caching of discord guild, channels and roles.

### ISSUE THREAD

**Issue by RohanJnr** [python-discord/sir-lancebot#545]
## Description
Cache guild, channels, and roles during the bot start and before any cog loads in.
This is going to make accessing channels and roles easier in the cogs/code without `getting`/`fetching` them in the cog.
This will also avoid repetitively `getting` or `fetching` the same channel/role in multiple cogs.

By doing this, we can make sure that all required channels and roles are loaded and present.

## Additional
The bot should stop even if one channel/role is found to be `None` or not present with appropriate logging.

## Would you like to implement this yourself?

- [X] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by Numerlor** [comment]
I don't think this is really necessary, with the `wait_until_guild_available` it's almost guaranteed that the get will succeed for channels the bots may use, with the gets being a fairly cheap lookup. When #393's implementation gets merged we'll get the warnings for missing channels, and then the cogs that try to get them can handle failed gets in their own way if necessary

**Comment by RohanJnr** [comment]
Won't it make it more convenient to just use the cached value instead of getting it again? and as I mentioned above, `This will also avoid repetitively getting or fetching the same channel/role in multiple cogs.`

So instead of importing the ID, we would just simply importing the channel/role instance.

**Comment by Akarys42** [comment]
I am going to close this issue since it would require quite a bit of rewrite that will be overwrote when smartconfig will be completed. The current behavior also makes development easier as you don’t need to have every settings pointing to a valid object, you only need what you use.
