### ISSUE TITLE
Investigate an upgrade to Python 3.9.4

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/sir-lancebot#549]
## Description
Python 3.9.1 has been released today (yay!), which means that it's mature enough for us to start looking into upgrading the Python version of sir-lancebot. We'll obviously have to make sure all our dependencies support 3.9 and everything works well, but it would be nice to use the new language features.

## Reasoning
It's better to keep up with Python version, adjusting our code base as required, than making a major leap in major versions with a potential more sizeable migration. Also, Python 3.9 introduces those neat built-in type generics, meaning that those ugly `typing.List[Typing.Dict[str, str]]` annotations can be replaced by `list[dict[str, str]]`. 

## Additional Details
We should not rush the upgrade! Take your time and have a look at our dependencies: Do they support Python 3.9? Are there know issues that are relevant for us? If too man roadblocks appear on the horizon, we can simply wait until they're solved!

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by ks129** [comment]
I will investigate (and when possible, update) Sir Lancebot to 3.9.

**Comment by ks129** [comment]
`discord.py` doesn't officially support 3.9 yet, because it's dependencies doesn't support it too. discord.py 1.6.0 will bring support for 3.9 (at least based on that what is said in server), so we need to wait until this.

**Comment by ChrisLovering** [comment]
Discord py 1.6 was released yesterday, with `Better support for 3.9 by bumping the dependencies`. Probably worth investigating this now.

**Comment by ks129** [comment]
I have already slowly started upgrading Python and discord.py.

**Comment by ks129** [comment]
Everyone is now able to take this issue. I don't have enough time to test every command and feature to ensure they are working after dependency upgrades.

**Comment by Shivansh-007** [comment]
I would be working on this along with @DawnOfMidnight

**Comment by ChrisLovering** [comment]
Can I request that we upgrade to 3.9.4, rather than 3.9.1 as this issue title suggests.

**Comment by dawnofmidnight** [comment]
I'll be working on this along with ToxicKidz and Shivansh-007. Also, I agree that 3.9.4 is better since it's more stable (assuming I understand versioning right).

**Comment by Shivansh-007** [comment]
| Dependency Name  | Upgraded                | Tested                  |   |
|------------------|-------------------------|-------------------------|---|
| aiodns           | <ul><li>- [ ] </li></ul> | <ul><li>- [ ] </li></ul> |   |
| arrow            | <ul><li>- [ ] </li></ul> | <ul><li>- [ ] </li></ul> |   |
| beautifulsoup4   | <ul><li>- [ ] </li></ul> | <ul><li>- [ ] </li></ul> |   |
| fuzzywuzzy       | <ul><li>- [ ] </li></ul> | <ul><li>- [ ] </li></ul> |   |
| pillow           | <ul><li>- [ ] </li></ul> | <ul><li>- [ ] </li></ul> |   |
| pytz             | <ul><li>- [ ] </li></ul> | <ul><li>- [ ] </li></ul> |   |
| PyYAML           | <ul><li>- [ ] </li></ul> | <ul><li>- [ ] </li></ul> |   |
| sentry-sdk       | <ul><li>- [ ] </li></ul> | <ul><li>- [ ] </li></ul> |   |
| PyYAML           | <ul><li>- [ ] </li></ul> | <ul><li>- [ ] </li></ul> |   |
| discord.py       | <ul><li>- [ ] </li></ul> | <ul><li>- [ ] </li></ul> |   |
| async-rediscache | <ul><li>- [ ] </li></ul> | <ul><li>- [ ] </li></ul> |   |
| emojis           | <ul><li>- [ ] </li></ul> | <ul><li>- [ ] </li></ul> |   |
| matplotlib       | <ul><li>- [ ] </li></ul> | <ul><li>- [ ] </li></ul> |   |

**Comment by Shivansh-007** [comment]
This issue can be closed, see #623

**Comment by dawnofmidnight** [comment]
After the update to poetry and python 3.9, this issue can be closed.
