### ISSUE TITLE
Only recommend one channel in “you can’t use it here” embed

### ISSUE THREAD

**Issue by gustavwilliam** [python-discord/sir-lancebot#556]
## Description

When using a command in a non-whitelisted channel, something like the following will appear.
![image](https://user-images.githubusercontent.com/65498475/104727706-12c9d600-5736-11eb-996f-cd34e79281bb.jpeg)

It would be nice to have a single preferred channel for bot commands, instead of listing all available channels.

## Reasoning

The current embed is very long, and users have received embeds like this one in response as well:
![image](https://user-images.githubusercontent.com/65498475/104728013-92f03b80-5736-11eb-8290-5930272a0d4f.jpeg)

It may seem counter intuitive to shoots only one option, but we don’t redirect users to off-topic or voice chat to use bot commands. We do it whenever a person uses the command in a non-whitelisted channel, so redirecting them to an on-topic channel wouldn't make sense. They're only trying to use the bot command, possibly as a part of the current conversation.

The main benefits are that the embed will be more user friendly and avoids the scenario where someone jumps into an on topic channel for bot commands, because the bot told them to.

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by ChrisLovering** [comment]
There is also issue #539 which is similar to this. I see two good options either we send the user to the designated bot channel, or list all of the channels that they have access to post in.

I prefer the former of the two, as I agree this embed is quite big, and with it disappearing after 7.5 seconds we want it to be short so the user has time to read it.

Either implementation we decide on, I'd like to work on this if possible :)

**Comment by Numerlor** [comment]
That sounds good when the default overrides are used, as the channel the users should be trying commands in really is only the bot commands channel; but in case of overrides I think we should display all the allowed channels (or the difference if it's a superset of the default) as there may be other channels intended as the "commands" channel. I don't think there is and will be such a case but the override could also forbid the default bot command channels

**Comment by ChrisLovering** [comment]
Ah yea agreed. If there's an override, we should list all override channels the user has access to. For the case when there aren't any overrides, do we just want to hardcode the bot to always point to `community_bot_commands`?

**Comment by Xithrius** [comment]
I think the first steps in this process was solved by #578, where whitelist overriding was given to a few commands.

Over time we should be able to cover the entire bot.

**Comment by Akarys42** [comment]
I agree with Numerlor proposal, we should only show #sir-lancebot-playground and the override channels. Are you still interested to work on that @ChrisLovering ?

**Comment by ChrisLovering** [comment]
I think I might already have this fix in a branch on my fork. I'll dig it up over the weekend it PR it over here
