### ISSUE TITLE
Porting Command Suggestions from bot

### ISSUE THREAD

**Issue by Shivansh-007** [python-discord/sir-lancebot#561]
## Description
suggest similar command(s) to a miss spelt command

## Proposed Implementation
- Port it over from bot.
- Limit it to #sir-lancebot channel only.
- Add the seasons check, so only the commands of the season are show.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by RohanJnr** [comment]
I don't think we have to port things over from bot, in the help cog, there is code already to handle `HelpQueryNotFound` error. But after a lil testing, it is not being handled properly. the way to fix this is to look at the code and see whats missing from raising the `HelpQueryNotFound` error and handling it

**Comment by Akarys42** [comment]
In a similar way the command suggestion works on Python, I don’t think we should limit it to #sir-lancebot-playground, what do you think?

**Comment by Shivansh-007** [comment]
Right, I will keep it open.

I will open a PR once I get offloaded a bit (4 PRs open as of now).
