### ISSUE TITLE
Improve Wikipedia Command.

### ISSUE THREAD

**Issue by Shivansh-007** [python-discord/sir-lancebot#565]
Currently the `.wiki` command only gives the titles of the options and no description of the topics, so it would be good, if it would a show paginated messaeg containing each topic in the following embed format (Top 10 results)
```
Title.
50 character summary of the topic.
Thumbnail of that wikipedia link.
```

## Would you like to implement this yourself?
- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by RohanJnr** [comment]
How about the have the first-page show all the titles(like the current implementation) and then pagination to show each title with some description and image if possible?

**Comment by Shivansh-007** [comment]
Alright will do that!

**Comment by Shivansh-007** [comment]
Next time please ping me on discord or here. When u assign me, thanks!
