### ISSUE TITLE
Automatically linking issues using repo#number in messages

### ISSUE THREAD

**Issue by Akarys42** [python-discord/sir-lancebot#566]
Actions python-discord/organisation#318

We should make a message listener that would send a link to an issue when the message contains `repo#number`. Here is an example:

![image](https://user-images.githubusercontent.com/44778521/105468724-96844500-5c97-11eb-95d6-e9209634b135.png)

# Specifications
* The bot should match the regex `.+?#\d+` outside of a codeblock.
* If the repo or the issue can't be found, nothing should happen.
* This feature should be limited to the `python-discord` repositories, although that should be configurable.
* This feature should be limited to :
   * the `organisation` channel (551789653284356126)
   * the `development` category (411199786025484308)
   * the `dev-projects` category (787641585624940544)
   * the `media` category (799054581991997460)

**Comment by Shivansh-007** [comment]
Can I work on this issue?

**Comment by Akarys42** [comment]
> Can I work on this issue?

@Shivansh-007 Sure thing!

**Comment by Shivansh-007** [comment]
Will it send all the issues/prs contained in the message or only the first one.
For example:
`Hey folks, can you please check bot#1341 and meta#444`

So basically my question is whether it will send both the issues or only the first one?
