### ISSUE TITLE
Dog status codes

### ISSUE THREAD

**Issue by Shivansh-007** [python-discord/sir-lancebot#568]
## Description
A command such as `.http dogs` would be implemented to visually show what different status codes are, with dogs.

## Reasoning
Another fun way to learn status codes or refer them. And for non-cat people and dog lover ❤️ .

## Proposed Implementation
- Make a group named `http` which would contain `cat` and `dog` nested commands.
- Since dogs have some codes missing, we will use `aiohttp` and `regex` to get the status codes using `commands.task` which will run every 2 hours probably.
- This would implemented in a similar way like `.http_cat`.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by Xithrius** [comment]
> Since dogs have some comes missing, we will use `aiohttp` and `regex` to get the status codes using `commands.task` which will run every 2 hours probably.

Not sure how necessary this is since we can use the `http` module to see if the codes exist.

Besides that, I'd like to see this get implemented.
