### ISSUE TITLE
Python Cheat Sheet Command

### ISSUE THREAD

**Issue by Shivansh-007** [python-discord/sir-lancebot#570]
## Description
This is just like tldr pages. It is a really good resource and I use them regularly either when trying to help others or wanna look up something. 

## Screenshots
![105967971-7e079680-60ac-11eb-8e30-a0e8b7deecf2](https://user-images.githubusercontent.com/69356296/105968820-90360480-60ad-11eb-8042-650b2f5c6c9d.jpg)

## Proposed Implementation

- https://cht.sh/
- It supports a number of languages, so we can default it to python.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by Xithrius** [comment]
@Shivansh-007 I'd like to see this get implemented. Would you like to work on it?
