### ISSUE TITLE
Adding int eval command to Sir Lancebot

### ISSUE THREAD

**Issue by Senjan21** [python-discord/sir-lancebot#573]
## Description

Adding command such as [int eval](https://github.com/python-discord/bot/blob/master/bot/exts/utils/internal.py#L219) to Sir Lancebot

## Reasoning

It often might be useful to have some form of evaluation command to debug certain things that can't necessarily be debug-able via logging or other methods

## Proposed Implementation

Implementation could simply be porting the `Internal` cog of Python bot.

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by Shivansh-007** [comment]
After going through the `int eval` on bot, I think i can work on this issue. Thanks!

**Comment by Akarys42** [comment]
> After going through the `int eval` on bot, I think i can work on this issue. Thanks!

We should be porting the code from our closed source project Black Knight to both of our bot, I believe @SebastiaanZ is working on it. Thanks for your interest in this issue though!

**Comment by scragly** [comment]
Resolved by #673
