### ISSUE TITLE
Remove Member Intent Reliant Features From Lovefest

### ISSUE THREAD

**Issue by HassanAbouelela** [python-discord/sir-lancebot#574]
## Description

After discord introduced the intents  system, sir-lancebot no longer has access to the list of members for a role. This has led to a weird situation with some of the commands in the lovefest cog, as they relied on fetching members for a given role.

## Steps to Reproduce

(Make sure your bot does not have the members intent enabled)
1. Sign up for the lovefest role.
2. Try to use one of the commands that rely on fetching members, such as `.bemyvalentine` with no arguments.

## Actual Behaviour

The member fetch now returns an empty list, making the intended purpose fail, or returns a list with very few members, causing them to be bombarded by pings.

## Possible Solutions

[Functions that rely on member intents](https://discordpy.readthedocs.io/en/latest/api.html#discord.Intents.members) being enabled should be removed from the lovefest cog.

(If you find other features that suffer from similar bugs, open a separate issue for them.)

## Would you like to implement a fix?

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [ ] I'd like to implement the bug fix
- [x] Anyone can implement the bug fix

**Comment by ChrisLovering** [comment]
I'd like to give this one a go. I'll take a look through the cog tonight and come up with a few solutions that I think will work and get some feedback on them here.

**Comment by Shivansh-007** [comment]
Can i work on this? (Well actually am already working and opened a PR, but commented for getting assigned to this to avoid confusion)
