### ISSUE TITLE
Automatic linking issues catches a error when message sent to it on DMs.

### ISSUE THREAD

**Issue by Shivansh-007** [python-discord/sir-lancebot#576]
## Description
The Bot should skip when a message is sent to it on DMs since it is checking for the category and the DMChannel has no category.
```py
    message.channel.category.id in WHITELISTED_CATEGORIES
AttributeError: 'DMChannel' object has no attribute 'category'
```

## Steps to Reproduce
Send a DM message to your test bot, and check your terminal.

##  Behaviour
Should ignore the message which isn't being done currently,

## Possible Solutions
```py
if isinstance(message.channel, discord.DMChannel):
            # This command is only Server specific
            return
```

## Would you like to implement a fix?

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [ ] I'd like to implement the bug fix
- [x] Anyone can implement the bug fix

**Comment by ChrisLovering** [comment]
I'd like to work on this. There's a few other places that don't behave well when the ctx is from a DMChannel, I'll sort those at the same time.
