### ISSUE TITLE
Stackoverflow command

### ISSUE THREAD

**Issue by Vthechamp22** [python-discord/sir-lancebot#579]
## Description
Implement a `.stackoverflow` or `.so` command which takes a search query and lists the top (5?) results. This command would be limited only to `#sir-lancebot-commands`. The command structure would be very simple, just `.stackoverflow <search query>`

## Reasoning
This would help quickly getting solutions to problems that are not apt to use a help-channel, or questions which aren't python related. It would also reduce a little stress on the help channels.

## Proposed Implementation
Use the [Stackoverflow API](https://api.stackexchange.com/docs) and fetch the top results.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by RohanJnr** [comment]
A few suggestions:
- Add paginated response for many results (maybe 5 pages, 5 results on each page or maybe a bit less pages).
- Order results in descending order of views or another parameter which would suit.
- I don't like the idea of this being restricted to only sir-lancebot channel, I think even voice channels, help channels, python and general/adv channels should have access to this command as it could prove to be quite useful.
- After the feature is merged, we could use caching if we are seeing common questions(I doubt if this is required but just a possibility).

**Comment by Shivansh-007** [comment]
1. I don't think 5 pages are needed, we should get only say the top 10, since after that, the questions are non relevant ones.
2. Agree with this.
3. On every question people would just run the command, and I am not in the favour of that, voice channels and bot commands channels are fine, and ots, but I am not in favour about the others.
4. It is quiet fast right now, so caching isn't really needed.
5. Agree with this.

**Comment by Akarys42** [comment]
We had a discussion with the other core devs about this command the other day, and we want it to be restricted to #sir-lancebotplayground to avoid RTFM behaviors.

Caching sounds a bit overkill, although I wouldn't mind a non persistent one as long as we put a limit on the amount of entries. 
We shouldn't show unanswered questions, I agree.
