### ISSUE TITLE
Block commands from working in DMs

### ISSUE THREAD

**Issue by ChrisLovering** [python-discord/sir-lancebot#581]
## Description

Quite a few commands don't quite work when being invoked from a DM. https://github.com/python-discord/sir-lancebot/pull/577 was a quick fix to resolve some cases that raised errors.

However, as a long term fix, we should remove the ability to run commands within DMs completely, and point our users towards the bot-commands channels.

## Reasoning

Some people may try to invoke commands from DMing the bot. To stay on top of moderation, and to help with debugging, we want to keep these commands within the server.

## Proposed Implementation

Port over the [Security cog](https://github.com/python-discord/bot/blob/master/bot/exts/filters/security.py) from bot

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by Akarys42** [comment]
While we should make sure that the bot doesn’t go down in flames when a command is being invoked through DMs, I don’t think we should actually allow it. Keeping everything in the server is useful for both moderation and debugging, and I’d prefer if we can keep everything there (except for cogs that requires the use of a private channel, such as the battleship game).

**Comment by ChrisLovering** [comment]
So should we change the requirement from make it work, to always tell the user to go to bot commands channel?

**Comment by Akarys42** [comment]
> So should we change the requirement from make it work, to always tell the user to go to bot commands channel? If so, I think something generic could be done, rather than at the cog level

I think so, if everyone agrees to that.

**Comment by ChrisLovering** [comment]
Yea, I agree with the moderation and debugging points, I hadn't thought of it like that. I'll update the issue and get further feedback.

**Comment by ChrisLovering** [comment]
So, we already have this handler here https://github.com/python-discord/sir-lancebot/blob/3ad829d98f1de30f08d26fe592b8a89701301983/bot/exts/evergreen/error_handler.py#L85-L87 which catches the case where a command decorated with the `commands.in_guild()` check fails. 

The question is, do we want to enforce this across all commands, or do we want to just make sure this check is added to commands as needed.

**Comment by HassanAbouelela** [comment]
Up until recently, I was under the impression commands were already blocked in DMs. They definitely are blocked in [Python](https://github.com/python-discord/bot/blob/1c2b384915f4a7ba070c95c86126746bae2f7279/bot/exts/filters/security.py#L16). I think they should be globally blocked here as well. Are there commands that explicitly need DMs open?

**Comment by Akarys42** [comment]
On top of my head, minesweeper, aoc join, battleship and bemyvalentine secret will need to use DMs. Other commands shouldn't work inside DMs.

**Comment by HassanAbouelela** [comment]
Bemyvalentine secret was already transferred to server only, aoc already runs in the server, and battleship is already guild only. I'd have to check minesweeper, but I don't see a reason for it to not be on the server.

**Comment by Shivansh-007** [comment]
So basically, we need to stop anyone from starting a command in DMs, since for `aoc join` it would just send the message, for `minesweeper` it would take input but we shouldn't allow it to start (maybe), same for others.

**Comment by Xithrius** [comment]
What's the verdict of this issue?

**Comment by vivax3794** [comment]
> Bemyvalentine secret was already transferred to server only, aoc already runs in the server, and battleship is already guild only. I'd have to check minesweeper, but I don't see a reason for it to not be on the server.

minesweeper works **only** in dms atm, which with dms not being allowed breaks it currently, but I see no reason to not allow it on the server (I dont remember the orginal reason I made it dm only) 

https://github.com/python-discord/sir-lancebot/blob/main/bot/exts/fun/minesweeper.py#L234-L236
https://github.com/python-discord/sir-lancebot/blob/main/bot/exts/fun/minesweeper.py#L155-L157

**Comment by HassanAbouelela** [comment]
I had forgotten about the existence of this issue till now, but it was more or less resolved with #953.

Allowing a command in DMs needs to be done explicitly now, and we have not done that. I’ll be closing this issue.

We did kind of break minesweeper because it uses a command in DMs instead of just a message like battleship. We could either do what we do in battleship and have it listen to messages not commands, or we move it onto the server and delete the invocation to reduce spam.
