### ISSUE TITLE
8bitify GIF support

### ISSUE THREAD

**Issue by ChrisLovering** [python-discord/sir-lancebot#584]
## Description

Extend the 8bitify command to work with GIF profile pictures too. The output should be the full animated gif, but 8bitified.

## Reasoning

As nitro users can have GIFs as their profile picture, we should have the ability to 8bitify their whole avatar!

## Proposed Implementation

Same input & output as the current implementation, but make it work with GIFs

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by ChrisLovering** [comment]
To kick off the discussion, I know the current 8bitify command can take a few seconds to run, I'm not sure how much more this would add to CPU load. It could also be open to abuse by users with long GIFs. The implementer should take this into consideration if we decide to approve this.

**Comment by Akarys42** [comment]
Hey Chris! As our resource constraints are fairly low right now, and we would have to moderate the gif content, that's not something we are interested in right now.

I am going to close this issue for now, thanks for suggesting this!
