### ISSUE TITLE
Improve xkcd command

### ISSUE THREAD

**Issue by MrKomodoDragon** [python-discord/sir-lancebot#588]
## Description
The current xkcd command doesn’t have the description, or a link to the comic.

## Reasoning
It would help provide more info about the comic.

## Proposed Implementation
Use the ‘alt’ key in the json page and use the URL var we use to make the requests.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by Xithrius** [comment]
You can go ahead and do it.

**Comment by MrKomodoDragon** [comment]
Ok, will do! :D
