### ISSUE TITLE
Use aiofiles for all file interactions

### ISSUE THREAD

**Issue by ChrisLovering** [python-discord/sir-lancebot#591]
## Description

Currently, when interacting from files we use the normal method of:
```py
with open('filename.extension') as f:
    ...
```
This way of interacting with files is blocking. We should switch to a non-blocking method of handling files, both when reading and writing.

## Reasoning

Most file interactions happen on startup, so doing this will improve bot start times. It is also possible that we do this in some places during the command, so this will mean those commands will no longer block the whole bot process while reading from the file.

## Proposed Implementation

[aiofiles](https://pypi.org/project/aiofiles/) is a good option for doing this.

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by anand2312** [comment]
I can do this, could you give me some pointers as to where the file interactions happen? I'm rather new and am not familiar with the codebase.

**Comment by ChrisLovering** [comment]
Yea, once one of the core dev's sign this off, you could do a code base search for `with open(` and that should show you all the places.

**Comment by ChrisLovering** [comment]
The files we are loading on startup by the bot are so small that this extra dependency isn't really worth benefit, if there is one.

Discussed this in dev-contrib and people agreed. Closing this issue for now.
