### ISSUE TITLE
Remove question about the Nile

### ISSUE THREAD

**Issue by swfarnsworth** [python-discord/sir-lancebot#592]
https://github.com/python-discord/sir-lancebot/blob/13620a6461a78e43e8b16b9ad35691ff30622332/bot/resources/evergreen/trivia_quiz.json#L194

There's no way to definitively say if the Nile river or Amazon river is larger than the other. While the Amazon indisputably discharges more water, I believe there's some debate about where the Amazon definitively starts, and thus there's no way to say which is longer.

Because this question is ambiguous, it should be removed.

**Comment by MrKomodoDragon** [comment]
Could we possibly add the thing about the dispute in the info part?

**Comment by swfarnsworth** [comment]
@MrKomodoDragon That's fine if we change the question to be one that has a definitive answer.

**Comment by Arez1337** [comment]
Hey Guys, 
i am completely new to open source but an intermediate in python. I would like to take over this request if that is ok for you. 

Best Regards, 
Arez1337

**Comment by swfarnsworth** [comment]
@Arez1337 we actively encourage you to do so. Let us know in the `#dev-contrib` channel if you have any questions.

**Comment by Arez1337** [comment]
Ok, I requested a pull for my updated repository with the removed question https://github.com/python-discord/sir-lancebot/pull/598
