### ISSUE TITLE
Add Subsection Command for WTFPython

### ISSUE THREAD

**Issue by HassanAbouelela** [python-discord/sir-lancebot#602]
While discussing python-discord/meta#63, a suggestion that came up was to add a command to get a direct link to subsections of the python gotchas list. This can be used to quickly direct people towards relevant sections of this resource.

A possible implementation would fuzzy match the headers on the page, and send the link to the relevant sections.

**Comment by Shivansh-007** [comment]
I would like to work on this.

**Comment by Akarys42** [comment]
Thanks you @Shivansh-007, assigned !

**Comment by MrKomodoDragon** [comment]
Would this possibly go along with the PR i made about python facts?

**Comment by Shivansh-007** [comment]
Should I make use of the line pagination here, since some examples are really big. For example the [walrus operator example](https://github.com/satwikkansal/wtfpython/blob/master/wtfpython-pypi/content.md#-strings-can-be-tricky-sometimes).

**Comment by MrKomodoDragon** [comment]
@Shivansh-007 just an idea, could we add it as a subcommand for the .pyfacts command PR #596 ?

**Comment by Shivansh-007** [comment]
Ahh I am not in favour of that, this should be kept separate.
