### ISSUE TITLE
Startup Channel Check Bug

### ISSUE THREAD

**Issue by HassanAbouelela** [python-discord/sir-lancebot#606]
## Description
#482 Was merged a couple hours ago, and in it, the following change was introduced:
https://github.com/python-discord/sir-lancebot/blob/53af90f92258905c2bfc4c2db2341dfd1fdc0124/bot/bot.py#L74-L82

This logs an error for every single channel we have into sentry.

## Steps to Reproduce

Startup the bot.

## Expected Behaviour

It should only log missing channels.

## Actual Behaviour

All channels are logged as missing.

## Possible Solutions

So this bug is due to the check on line 81:
https://github.com/python-discord/sir-lancebot/blob/53af90f92258905c2bfc4c2db2341dfd1fdc0124/bot/bot.py#L81

All channels is a set of channel objects. Channel ID is an int, so it'll always return false. We should instead compare it to a set of IDs.

## Additional Details

While you're at it, could you please kaizen in a change to ignore this check on dev environments? A lot of these channels can't be set without directly modifying the constants, so invetiably someone will change constants to suppress it, and inventiably it'll be committed and we'll have to clean it up.

## Would you like to implement a fix?

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [ ] I'd like to implement the bug fix
- [x] Anyone can implement the bug fix

**Comment by Shivansh-007** [comment]
I would like to work on this.

**Comment by HassanAbouelela** [comment]
Thanks, you've been assigned.
