### ISSUE TITLE
HTTP Status Code 418 not recognized by .http_status command

### ISSUE THREAD

**Issue by sam-heller** [python-discord/sir-lancebot#608]
## Description
The .http_status .status and .httpstatus commands do not recognize HTTP status code 418 (I am a Teapot) as described in [RFC-2324 : Hyper Text Coffee Pot Control Protocol (HTCPCP/1.0)
](https://tools.ietf.org/html/rfc2324)

> 2.3.2 418 I'm a teapot
>   Any attempt to brew coffee with a teapot should result in the error
>   code "418 I'm a teapot". The resulting entity body MAY be short and
>   stout.

## Steps to Reproduce
Input any of the following commands in the sir-lancebot-playground channel
```
.httpstatus dog 418
.httpstatus cat 418

.status cat 418
.status dog 418

.http_status cat 418
.http_status dog 418
```

## Expected Behaviour
The relevant image from either https://http.cat/418 
![http-cat](https://user-images.githubusercontent.com/410320/109709539-a3d00180-7b6a-11eb-9cf6-5c6067986ecb.jpeg)
or https://httpstatusdogs.com/418-im-a-teapot

![418-dogs](https://user-images.githubusercontent.com/410320/109709551-a7638880-7b6a-11eb-94cf-096fa5e89636.jpg)
Should be displayed

## Actual Behaviour
An error message is displayed indicating that the status code 418 does not exist:
![Screen Shot 2021-03-02 at 3 10 55 PM](https://user-images.githubusercontent.com/410320/109709674-c4985700-7b6a-11eb-9cbd-77ee213d0834.png)

## Known Impacted Platforms

- [X] Web
- [X] Desktop
- [x] Android App
- [x] iOS App

## Possible Solutions

Support for HTTP Status Code 418 Is currently only available in [Python 3.9](https://docs.python.org/3.9/library/http.html). 

![Screen Shot 2021-03-02 at 3 29 43 PM](https://user-images.githubusercontent.com/410320/109710870-3624d500-7b6c-11eb-875c-feb3d30188e6.png)

![Screen Shot 2021-03-02 at 3 30 04 PM](https://user-images.githubusercontent.com/410320/109710878-391fc580-7b6c-11eb-981a-91d0f721ef5a.png)

 Implement manual workaround for this status code until default interpreter is upgraded to 3.9
## Additional Details

Relevant Python Bug : https://bugs.python.org/issue39507

## Would you like to implement a fix?

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [X] I'd like to implement the bug fix
- [x] Anyone can implement the bug fix

**Comment by Den4200** [comment]
This has been discussed a couple of times in the past. I believe we came to a general consensus that we don't need to use the `http` module to check the status code. Instead, we can just send a request to the site and if the status code returned is invalid, display a 404 dog/cat.

**Comment by Xithrius** [comment]
According to issue https://github.com/python-discord/sir-lancebot/issues/428, we'll probably be waiting until we can upgrade to 3.9 without any worries.

**Comment by Den4200** [comment]
Nevertheless, I think it'd be quite amusing for a 404 status dog/cat to appear for invalid status codes. I don't see any reason not to fix this now and remove our dependency on the `http` module either.

**Comment by Shivansh-007** [comment]
Another way is to use regex and get all the status codes.

**Comment by ChrisLovering** [comment]
I concur with @Den4200 I think we should remove the http module check and just call the status sites directly. Then rely on them sending a 404/302 and dealing with that.

**Comment by HassanAbouelela** [comment]
I've approved it now,  and assigned you. I think you'd be best off following Den's suggestion yeah.

**Comment by sam-heller** [comment]
PR is up, please do your worst! I'll take brutality over pushing dodgy code any day of the week.
