### ISSUE TITLE
Full support for Gitpod

### ISSUE THREAD

**Issue by Kronifer** [python-discord/sir-lancebot#611]
## Description
Similar to the issue open for supporting GitHub CodeSpaces. When you try to use Gitpod for sir-lancebot, you have to install lots of things manually.

## Reasoning
Quicker development times online as there is no need to manually install dependencies.

## Proposed Implementation
Creating a .gitpod.yml file, described [here](https://www.gitpod.io/docs/configuration/)

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by HassanAbouelela** [comment]
Gonna leave my two cents here:

I don't have anything against gitpod, and wouldn't mind us adding this. What I do have a problem with, however, is if this will "open the floodgates" so to speak. Will this lead to more editor specific changes? If so, which editors do we accommodate?

I'm not going to shoot this down immediately, because it seems cool and helpful, but I also won't approve it until we get more opinions.

**Comment by Kronifer** [comment]
I don't think so, there aren't many browser dev environments used besides these two @HassanAbouelela

**Comment by Xithrius** [comment]
I think this falls under the same reasoning of if https://github.com/python-discord/sir-lancebot/issues/451 should be kept open as well. Codespaces are now paid for, so not many users are going to have this as an advantage.

My point is: should we implement codespaces at all? @HassanAbouelela @Kronifer please give me your opinions.

**Comment by Kronifer** [comment]
I think either way works. It would be nice to have dependencies installed right off the bat, but at the same time it isn't hard to install them

**Comment by HassanAbouelela** [comment]
I don't mind adding support for gitpod, I just ask we maintain a high standard for what we add.

Gitpod is a large service, with many users, so it's okay to add. Smaller services are a dime a dozen, and don't make as much sense to support.

**Comment by Kronifer** [comment]
@Xithrius, is this approved and could I be assigned?

**Comment by HassanAbouelela** [comment]
Yes & yes

**Comment by jchristgit** [comment]
@Kronifer should we document the gitpot support in the README, so people know where to quickly start working on the bot?

**Comment by Kronifer** [comment]
@jchristgit I'll do that once I get home

**Comment by jchristgit** [comment]
Thank you 😌
