### ISSUE TITLE
Codeblock rendering inconsistency on Android client.

### ISSUE THREAD

**Issue by scragly** [python-discord/sir-lancebot#615]
## Description

In Discord's markdown formatting, it has been mentioned in the past that codeblocks should have their triple backticks on their own lines. For the vast majority of time, this could be ignored, however recently the Android Discord client renders the two codeblocks differently now, with those without the dedicated lines for the backticks resulting in inline code blocks being rendered instead.

![image](https://user-images.githubusercontent.com/29337040/110314953-44835d00-8054-11eb-9e4f-1c3dfd4355c8.png)

### Shows as inline codeblock
<pre>
```this is some text```
</pre>

### Shows as normal codeblock
<pre>
```
this is some text
```
</pre>

Embeds are impacted also, but the difference is marginally noticeable, with slight differences in text padding and the faint codeblock outline missing from the inline ones.

### Inline Rendered
![image](https://user-images.githubusercontent.com/29337040/110315316-cffcee00-8054-11eb-915c-02cc2742acbf.png)

### Full Codeblock Rendered
![image](https://user-images.githubusercontent.com/29337040/110315401-ec992600-8054-11eb-9e76-7ada883141e7.png)

## Steps to Reproduce
Send the the above examples in a channel and view the resulting codeblocks in the Android Discord client.

## Expected Behaviour
As we are using triple backticks explicitly, we'd expect to get a full codeblock rendered.

## Actual Behaviour
We don't.

## Known Impacted Platforms

- [ ] Web
- [ ] Desktop
- [x] Android App
- [ ] iOS App

The others are confirmed as working as we expect them to.

## Possible Solutions
We should go over the bot and adjust any offending message output to place the backticks on their own line.

## Would you like to implement a fix?

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [ ] I'd like to implement the bug fix
- [x] Anyone can implement the bug fix

**Comment by Xithrius** [comment]
For people on android, does this bug still exist?

**Comment by wookie184** [comment]
Can confirm the described behaviour still happens, I can go through and fix these cases. Should be as simple as adding in some `\n`s where they are missing
