### ISSUE TITLE
Incorrect Zodiac Dates

### ISSUE THREAD

**Issue by TizzySaurus** [python-discord/sir-lancebot#620]
## Description
The stored start/end dates of zodiac signs are mostly incorrect, resulting in dates given on the `.zodiac` command being incorrect, as well as the wrong zodiac sign being given in certain scenarios for the `.zodiac date` command.

## Steps to Reproduce
Perform the `.zodiac` command (e.g. `.zodiac scorpio` / `.zodiac date 22 november`)

## Expected Behaviour
The correct dates / zodiac sign should be shown

## Actual Behaviour
Incorrect date / sign are shown:
 
- Should have end date as november 22:
![zodiac scorpio](https://user-images.githubusercontent.com/47674925/110550020-d8bff380-812a-11eb-9deb-fe19d7a9b1aa.png)

- Should show Scorpio:
![zodiac date 22 november](https://user-images.githubusercontent.com/47674925/110549899-aa421880-812a-11eb-9ae5-2bfa7f9da876.png)

## Known Impacted Platforms

- [x] Web
- [x] Desktop
- [x] Android App
- [x] iOS App

## Possible Solutions

Correct the dates in [the JSON file](https://github.com/python-discord/sir-lancebot/blob/1df233eb6e5061f0ed6127d158f9414e2b7749a3/bot/resources/valentines/zodiac_explanation.json) storing information on the different zodiac signs.

## Would you like to implement a fix?
***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [x] I'd like to implement the bug fix
- [ ] Anyone can implement the bug fix

**Comment by Raghav-Gupta24** [comment]
Greetings @TrizzySaurus, I have checked out a couple websites (attaching link for the same) and according to them, the date entered here are correct.

https://www.britannica.com/topic/zodiac
https://www.cosmopolitan.com/uk/entertainment/horoscopes-monthly/a29383721/star-sign-dates/

**Comment by Xithrius** [comment]
I have checked more websites, and the dates do indeed seem correct.
