### ISSUE TITLE
Battleship game ends abruptly if given bad input

### ISSUE THREAD

**Issue by bast0006** [python-discord/sir-lancebot#622]
## Description
Entering `I9ASDF` causes the .battleship game to error and end. 

## Steps to Reproduce
Start a game, enter a valid target, then add more to the message before sending it. Any text will do.

## Expected Behaviour
The bot to respond with a red X like it does for non-matching input (such as `AAAA`)

## Actual Behaviour
The game ends abruptly with `An error occurred. Game failed`

## Possible Solutions/Details
The core issue lies on this line: 
https://github.com/python-discord/sir-lancebot/blob/3454a88a43bec5d0959495c99b28ed80e96f12fb/bot/exts/evergreen/battleship.py#L262 and this line https://github.com/python-discord/sir-lancebot/blob/3454a88a43bec5d0959495c99b28ed80e96f12fb/bot/exts/evergreen/battleship.py#L230
Specifically, re.Match.string returns the entire text given to match against, and we're using re.match not re.fullmatch. Therefore, any message that contains a match is returned in entirety, rather than the match itself (which could be a portion of the message). 

We should probably use re.fullmatch instead. 

## Would you like to implement a fix?

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [ ] I'd like to implement the bug fix
- [x] Anyone can implement the bug fix

**Comment by rijusougata13** [comment]
i think  this line ```self.match = re.fullmatch("([A-J]|[a-j]) ?((10)|[1-9])", message.content.strip()) ``` will solve this issue @bast0006
