### ISSUE TITLE
Using group commands without specifying a subcommand sends the default help command.

### ISSUE THREAD

**Issue by ToxicKidz** [python-discord/sir-lancebot#624]
## Description
Whenever someone uses a group command without providing a subcommand, it sends the default help command instead of the one we already have.:

## Steps to Reproduce
If I just do `.group_name`, it sends the default help command.

## Expected Behaviour
It should use our help command, so it should look like this:
![image](https://user-images.githubusercontent.com/78174417/110805693-55e48900-824f-11eb-9fb7-ca80b11251c2.png)

## Actual Behaviour
It sends this:
![image](https://user-images.githubusercontent.com/78174417/110804922-9db6e080-824e-11eb-9e92-fffcfe3b9f09.png)

## Known Impacted Platforms

- [x] Web
- [x] Desktop
- [x] Android App
- [x] iOS App

## Possible Solutions
We are currently using [Context.send_help](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.Context.send_help), but our help command isn't a [commands.HelpCommand](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#helpcommand) so it sends the default one. Instead, we should invoke the help command instead using [Context.invoke](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.Context.invoke) to invoke our help command.

## Would you like to implement a fix?

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [x] I'd like to implement the bug fix
- [ ] Anyone can implement the bug fix

**Comment by Xithrius** [comment]
Dew it.
