### ISSUE TITLE
Feature: ".github repo" command

### ISSUE THREAD

**Issue by ToxicKidz** [python-discord/sir-lancebot#629]
## Description
This will make `.github` a group command.
A `.github repo` command that shows you information about a repository in github. A search subcommand that searches repositories for that specific term. This changes the current `.github` to `.github user`.
## Reasoning

I think it would be cool to see info about a repository in discord instead of having to find it myself on github, and to be able to show it to someone else.

## Proposed Implementation

Using the github api to get info about that specific repository.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by MrKomodoDragon** [comment]
Quick note, we already have a `.github` command for user info. My idea is, we could make it as a subcommand like `.github user`

**Comment by ToxicKidz** [comment]
Oh never noticed, and yeah, I agree it should be `.github repo <reponame>` and `.github user <username>`.

**Comment by PureFunctor** [comment]
Sounds good, feel free to work on this feature
