### ISSUE TITLE
Allow automatic linking of issues everywhere 

### ISSUE THREAD

**Issue by Akarys42** [python-discord/sir-lancebot#630]
We have been limiting the channels where automatic linking issues can be used in (See #566).

Since we haven't seen any potential issue with it, we can allow it everywhere to avoid updating it every two days or missing some channels.

If you have any concern with this, feel free to leave a comment!

**Comment by gustavwilliam** [comment]
Sounds like a good idea. I’ve been missing it in quite a few channels.

If, for some reason, it turns out to have been a bad idea, it should be fairly simple to revert.

**Comment by SebastiaanZ** [comment]
This seems like a major change in the scope of where we allow a feature. Is there some discussion surrounding the decision somewhere?

**Comment by Akarys42** [comment]
> This seems like a major change in the scope of where we allow a feature. Is there some discussion surrounding the decision somewhere?

It has been discussed in #dev-core, in #organisation and the issue was left open for a week. Everyone seemed on board with the idea.
