### ISSUE TITLE
over-used easter topics in .topic command of sir-lancebot

### ISSUE THREAD

**Issue by AnkithAbhayan** [python-discord/sir-lancebot#634]
## Description
I don't know whether this is a feature or a bug since I didnt read the source code; but the `.topic` command has been spilling out a lot of topics related to Easter. I don't blame the topics (its actually pretty good), its about how frequently the same topics are being sent by the bot. I know this is a one-time-thing where topics are more likely to be about a specific celebration (in this case Easter) but.... the same topics being sent SMH. (I've been told that random module isnt really random?)

## Reasoning
Every long conversation in any of the off-topic channels lead to an awkward silence. I'm an avid user (and so are many other people) of this topic command. And a diverse and vast collection of topics could (Would) really help us break the ice. The "regulars" or the more active people of this server will come to a point where they've answered all topics of that command. This hasn't been helpful given the frequency of Easter topics being sent (which almost everyone has byhearted at this point). This also jeopardizes the start of long and fruitful conversations. 

## Proposed Implementation
I propose either of the two following implementations.
1) Add more easter topics to the list.
2) Decrease the frequency of Easter topics being sent.

## Additional Details
Just.... goto any off topic channel and use the `.topic` command 3 times.
I guarantee you, any one topic will repeat twice.
the following is someone who agrees with me :DD
![someone who agrees with my point](https://user-images.githubusercontent.com/69845955/112022161-06a82d80-8b58-11eb-82a4-d9eed7eded7a.png)

## Would you like to implement this yourself?
- [ ] I'd like to implement this feature myself
- [X] Anyone can implement this feature

**Comment by Akarys42** [comment]
I’d personally be for eviscerating all the Easter related questions, what do you think?

**Comment by AnkithAbhayan** [comment]
yeah that would work as well.

**Comment by AnkithAbhayan** [comment]
Or... just remove all pre-existing Easter topics. And add 5-7 new topics (related to Easter of course) and keep them till Easter ends. (afaik its 4th of April?)

**Comment by ChrisLovering** [comment]
Another approach could be to store an optional month against each topic. Then on cog load, we only load the topics that don't have a month, or are from the current month.

**Comment by Xithrius** [comment]
@AnkithAbhayan does this problem still occur? We've added a bunch of new topics for offtopic channels. The order in which topics are selected is randomized, which can be seen [here](<https://github.com/python-discord/sir-lancebot/blob/main/bot/exts/evergreen/conversationstarters.py#L29-L32>).

The current list for offtopic topics can be seen [here](<https://github.com/python-discord/sir-lancebot/blob/main/bot/resources/evergreen/starter.yaml>), which contains a total of 49 topics.

**Comment by AnkithAbhayan** [comment]
@Xithrius No it doesn't. Ever since the new topics got added and after April, it just didn't repeat that often.
(I almost forgot that this issue was open lol)
I'll guess I'll close this issue?

**Comment by Xithrius** [comment]
@AnkithAbhayan Thank you for the update. I will now obliterate this issue.
