### ISSUE TITLE
Unhandled HTTP responses in Issues cog.

### ISSUE THREAD

**Issue by kosayoda** [python-discord/sir-lancebot#643]
The current implementation of `fetch_issues` only handles responses `404` and `403`, while assuming everything else is valid.

The [issue endpoint](https://docs.github.com/en/rest/reference/issues#get-an-issue) called in the method returns other HTTP responses, all of which should be handled properly:

- [`301 Moved Permanently`](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#http-redirects) responses should be treated as `404`, ie. the issue does not exist. Reasoning behind it is the fact that most issues moved are from public to private repositories.
- `410 Gone` responses should return a suitable message about the status of the issue.

To further improve stability, the method should also only proceed with a `200 OK` response, and generate a suitable error message if any other response is found.

Kaizen Fix: Whoever implements this issue should also set the `Accept` header to the recommended `application/vnd.github.v3+json`.

**Comment by Brodevil** [comment]
I want to work on this

**Comment by HassanAbouelela** [comment]
Thanks, you've been assigned.
