### ISSUE TITLE
Slash Commands

### ISSUE THREAD

**Issue by NeilShah2026** [python-discord/sir-lancebot#646]
## Description
Add Slash Commands To The Discord Bot With The Most Used Commands

## Reasoning
This Would Make Using Common Commands Easy And Accessible

- [ ] I'd like to implement this feature myself
- [ x] Anyone can implement this feature

**Comment by Akarys42** [comment]
Hello @NeilShah2026, thanks for your interest in our project.

As Discord.py doesn’t provide any slash command support at the moment and your issue doesn’t suggest any other way to achieve this, I am going to close this for now.

Please reach out in the `#dev-contrib` in our [Discord server](https://discord.gg/Python) before opening such major issues.

Thank you,
- Akarys
