### ISSUE TITLE
Add internal evaluation to sir-lancebot

### ISSUE THREAD

**Issue by mbaruh** [python-discord/sir-lancebot#653]
## Description
Admins should be able to run evaluations on sir-lancebot at runtime.

## Proposed Implementation
The implementation can be similar to the one in the bot, but it's possible the code is outdated or over-complicated, so alternative suggestions are fine.

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by Akarys42** [comment]
We should be using @SebastiaanZ's implementation on Black Knight for that.
