### ISSUE TITLE
Bonk! Bonk!

### ISSUE THREAD

**Issue by Shivansh-007** [python-discord/sir-lancebot#655]
## Description
Add a `.bonk <userid/username/mention>` command,  which when invoked would send gif of mentioned member being "bonked" by Master Yoda. Example:

> .bonk 386599446571384843
>
> ![Bonk](https://cdn.discordapp.com/attachments/793570459945926717/828086090828873728/bonk_386599446571384843_2021-04-04_01-58.gif)

## Reasoning
It would be a fun command to have around on the bot.

## Proposed Implementation

![Screenshot from 2021-04-04 07-34-06](https://user-images.githubusercontent.com/69356296/113496529-2eb06d00-9518-11eb-8e5f-80cbe1657504.png)

## Additional Details
Here is the GIF raw version:

![Raw GIF](https://raw.githubusercontent.com/ShakyaMajumdar/gurkbot/07bbf939ebdc180957debb1f33850cafb52f18bb/bot/resources/images/yodabonk.gif)

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by Akarys42** [comment]
Thanks for the issue! This is something we are not currently interested in as it may lead to some poor interactions between the users, and porting cogs from other bots isn’t really fun.
