### ISSUE TITLE
Use a grey :PRDraft: emoji for the .pr command if the PR is a draft

### ISSUE THREAD

**Issue by ToxicKidz** [python-discord/sir-lancebot#661]
## Description

Currently, the `.issue` | `.pr` command uses a green open pull request emoji when showing open pull requests. Although, when pull requests are drafts in Github, then the colour of the sign will be grey. For example, #623 is a draft PR, and doing `.pr 623` currently looks like this:
![green-pr-emoji](https://user-images.githubusercontent.com/78174417/113887071-2dd54080-978f-11eb-97eb-cec7c054941e.png)

However, it really should look like this: 
![grey-pr-emoji](https://user-images.githubusercontent.com/78174417/113886850-fd8da200-978e-11eb-8bb9-da46f9246f3e.png)

## Reasoning

I think it would make more sense when it is a draft pr that it should be grey instead of green.

## Proposed Implementation

After having a :PRDraft: emoji, check if `json_data["draft"]` is `True`, and if it is, use the :PRDraft: emoji.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by Kronifer** [comment]
Seems like a good idea
