### ISSUE TITLE
Remove/edit a topic which is impossible to answer.

### ISSUE THREAD

**Issue by onerandomusername** [python-discord/sir-lancebot#664]
## Description

There is never anyone to the right. Remove that line from the topic command.

## Reasoning

Every time this topic comes up, people tend to hate it or make fun of it.

## Proposed Implementation

Remove the topic from [/bot/resources/evergreen/starter.yaml#L9](https://github.com/python-discord/sir-lancebot/blob/d76ec41d0d19099488f09677dce50aeae16967b8/bot/resources/evergreen/starter.yaml#L9)

## Would you like to implement this yourself?

- [x ] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by jb3** [comment]
Approved.
