### ISSUE TITLE
Authenticate all Github Requests

### ISSUE THREAD

**Issue by onerandomusername** [python-discord/sir-lancebot#670]
## Description

Some of the requests to the github api aren't authenticated, specifically in the [github cog](https://github.com/python-discord/sir-lancebot/blob/main/bot/exts/evergreen/githubinfo.py#L29-L34)

## Proposed Implementation

I have two different ideas here. The one and simple idea would be to copy code from the [issues cog](https://github.com/python-discord/sir-lancebot/blob/main/bot/exts/evergreen/issues.py) that does authenticate requests, but the other idea would be to make github requests a utility function since there's two cogs that request issues and make them share the method.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by Xithrius** [comment]
> the other idea would be to make github requests a utility function since there's two cogs that request issues and make them share the method.

@onerandomusername There will probably be some commands in the near future that will need authentication, so I think we should go with this method.

Would you like to go ahead and put this together?

**Comment by Xithrius** [comment]
@D0rs4n you can go ahead and take this once that PR is merged. Should be done sometime soon.

**Comment by ToxicKidz** [comment]
This seems to be completed in #778.
