### ISSUE TITLE
Rework The PR Template

### ISSUE THREAD

**Issue by HassanAbouelela** [python-discord/sir-lancebot#685]
## Description

The PR template has a lot going for it. I like the fields it has, and the descriptions written there for each one are quite adequate, yet, we still end up with a lot of PRs that either don't use the template and fail to provide information in any other way, or fail to fill in one or more fields that contain very important information. This applies to staff, core-devs, and non-staff contributors.

I won't list specific examples here as to not call anyone out, but I have seen:
- PRs with 2 or 3 word descriptions, that have popped out of nowhere, and are difficult to handle due to the missing context.
- PRs that fail to fill in the reason field, or fill it in incorrectly (see the gist linked below). I touched on it in [discord](https://discord.com/channels/267624335836053506/429409067623251969/824619053678067753), but that didn't go anywhere.
- PRs that are opened without issues, and cite the only reason behind the existence of the PR as being "discussed on discord" or something similar, with no links.

## Reasoning

Sir-lancebot is a project intended to be a gateway to open source contributions and is meant to make them as easy as possible. When someone opens a PR that meets one of the problems listed above, we are usually unable to review it because that missing context is important. We might end up with a lot of back and forth trying to extract those details, which is not fun for reviewers and contributors.

The intention of these changes is to create a standardized, easy-to-follow format, and enforce it in our guidelines.

## Proposed Implementation

I propose the following changes (do not make comments on the gist, keep them here):
[Gist](https://gist.githubusercontent.com/HassanAbouelela/0ca74e258caf57c07dd6f5e545e33803/raw/21ffe48383f59df84350848fd89289691d57f8a9/pull_request_template.md)

Update 1: Better explanation on when it is okay to make a PR without an issue. [Discussion](https://discord.com/channels/267624335836053506/411200599653351425/832591634952618004).
Update 2: Expand on what it means for an issue to be approved. [Discussion](https://discord.com/channels/267624335836053506/411200599653351425/832598212811554838).
Update 3: Rewrite the issues section to be shorter, and to the point. Discussion below.
Update 4: Final update - dropped the reasoning field.

Along with: 
- Adding a requirement to fill out the PR template to the [contributing guidelines](https://pythondiscord.com/pages/contributing/contributing-guidelines/).
- Making the contributing guidelines easier to find on the site. Currently, the sir-lancebot getting started guides has a link to the contributing file on github, which just redirects to the contributing guide on the site.

## Would you like to implement this yourself?

Not really relevant, this will be more of a discussion anyways.

**Comment by HassanAbouelela** [comment]
Update 1: Better explanation on when it is okay to make a PR without an issue.

**Comment by HassanAbouelela** [comment]
Update 2: Expand on what it means for an issue to be approved. [Discussion](https://discord.com/channels/267624335836053506/411200599653351425/832598212811554838)

**Comment by MarkKoz** [comment]
> Pull requests need to have related issues. Opening a pull request without an issue requires an explicit core-dev approval beforehand.

Could be shorter

> Pull requests must have a corresponding issue unless explicitly given permission from a core dev.

_Corresponding issue_ denote a stronger relationship than _related_ issue, though maybe the word is too "fancy". _Must_ has a stronger connotation than _needs to_.

**Comment by MarkKoz** [comment]
"Corresponding" could also be "equivalent" or "matching" I suppose.

**Comment by HassanAbouelela** [comment]
I agree with shortening that part. I think mentioning core dev approval in there is important, what do you think of:
> Opening a pull request without an issue requires explicit core dev approval.
(mostly dropping the first sentence)

I've rewritten that whole section to be more to the point (implicitly addresses your second comment):
Original
> This field is mandatory. List relevant issue tickets here.
All changes require explicit Core Developer approval (for issues, those are given using the "status: approved" tag). Pull requests need to have related issues. Opening a pull request without an issue requires an explicit core dev approval beforehand.

Updated:
> Linking an issue approved by a Core Developer is mandatory. Approved issues have the `approved` tag. Issues can be skipped with explicit core dev approval, but you have to link the discussion.

**Comment by dawnofmidnight** [comment]
> Opening a pull request without an issue requires an explicit core-dev approval beforehand.

I think it would be nice to add that if it was discussed in Discord and you were told not to open an issue, you must provide links to the conversation. 

It's not uncommon that admins and owners say that you can open a pr, so I think that making sure you provide links is something worth pointing out.

**Comment by HassanAbouelela** [comment]
That part is already in the original gist as
> Opening a pull request without an issue requires an explicit core dev approval beforehand.

It is also included in the rewritten comment.

**Comment by HassanAbouelela** [comment]
Update 4: Dropped the reasoning field.

This has been prompted by internal discussions [here](https://discord.com/channels/267624335836053506/411200599653351425/832710804541276190) and [here](https://github.com/python-discord/organisation/issues/268).

The gist of it is: In theory, it's great, but it often does not work (perhaps that was the old wording, perhaps people just don't understand it). It also is not necessary most of the time, and where it is necessary, the author could choose to add their own field.

This is the final update for now, it has almost been a week, so I will PR all the changes suggested to the repo. The other changes will have to wait till the wiki freeze is over, but provided no one adds any comments about them, I will be actioning those changes ASAP as well.

**Comment by HassanAbouelela** [comment]
Actual final update: removed screenshots and additional details section, for the same reason as reasoning.

**Comment by Shivansh-007** [comment]
I think we should keep screenshots, it helps reviewers see how the output looks, like the other day, there was a suggestion by Alec on consistent spacing. But once he saw the screenshots of the error embed, he was convinced with the embed.

We could not make it compulsory, but yeah it is a really good field.

**Comment by HassanAbouelela** [comment]
I don't agree that we should have it when most of the time most people won't use it. Screenshots may be useful when deciding what looks best, but I still expect reviewers to actually test out the features they are approving (because when they don't, we end up with broken code. ask me how I know).

There is also something to be said about keeping the template concise and limited to what is absolutely required, something I hope to address in the other templates once we're done here.
