### ISSUE TITLE
splitify - new command similar to 8bitify (command name could be changed)

### ISSUE THREAD

**Issue by vincepy** [python-discord/sir-lancebot#687]
hello id like to add a new feature to lancebot similar to 8bitify. my idea is to take user's profile image, split it in x pieces, randomize those pieces and stitch it back up. ill show an example below.

original:
![image](https://user-images.githubusercontent.com/20439493/115882892-1fe91600-a445-11eb-9629-3e997bf7c4b9.png)
modified:
![image](https://user-images.githubusercontent.com/20439493/115882930-27102400-a445-11eb-8346-e14f8e4e1673.png)

in the example there were 25 splits. i was also thinking of allowing users to specify the splits themselves using the command. if anyone's interested in this idea, let me know. p.s. i already have the whole code for this, i would just need to make it work as a discord command.

**Comment by Akarys42** [comment]
This looks good to me! Do you think you can also make the number of squares customisable too?

**Comment by vincepy** [comment]
> This looks good to me! Do you think you can also make the number of squares customisable too?

by splits, i meant the squares, so yes.

**Comment by ChrisLovering** [comment]
I'd suggest that we wait until #597 is merged for this issue.

**Comment by ToxicKidz** [comment]
Since #597 was merged, I am willing to implement this.

**Comment by ChrisLovering** [comment]
Go for it 👍
