### ISSUE TITLE
Bookmark messages using the message reference (replying)

### ISSUE THREAD

**Issue by vcokltfre** [python-discord/sir-lancebot#689]
## Description
The ability to use the bookmark command without a message link argument to bookmark a message by replying to it. Like this:
![image](https://user-images.githubusercontent.com/16879430/115239467-ae445b80-a116-11eb-8fc1-c22a5e12ada1.png)
(I already have the code since I was curious, but I need to make an issue so everything is done by the book)

## Reasoning
It's just a small QoL change that means people wouldn't need to copy the message link to bookmark the message, which is especially useful on Mobile/Android specifically since copying a message link is a pain because you have to go to the menu > share > copy link to get it.

## Proposed Implementation
Implementation is done by making the target_message argument optional, and then if it's unset trying to use the message.reference. To use the reference it tries to fetch the referenced message from the message cache, and if that's None it fetches it from the API.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by ChrisLovering** [comment]
I'd suggest waiting until https://github.com/python-discord/sir-lancebot/pull/645 is merged, and integrating your code with the changes there.

**Comment by vcokltfre** [comment]
Will do, mind pinging me on Discord when that's done :P
