### ISSUE TITLE
Spookify shows different embed header than profile picture spookified

### ISSUE THREAD

**Issue by laundmo** [python-discord/sir-lancebot#690]
## Description
when running spookify with a id, it shows the other users pfp and name in the embed header, and the own profile pic spookified.

## Steps to Reproduce
The header should match the spookified image

## Expected Behaviour
The other persons pfp should be spookified, or the header should match the 

## Actual Behaviour
![image](https://user-images.githubusercontent.com/24855949/115249815-464b4080-a129-11eb-8f4e-b981262408a9.png)

## Would you like to implement a fix?

- [ ] I'd like to implement the bug fix
- [x] Anyone can implement the bug fix

**Comment by ToxicKidz** [comment]
This is already fixed in #597, however, I don't know how long it will take to get merged.
