### ISSUE TITLE
Add `.catify`

### ISSUE THREAD

**Issue by Kronifer** [python-discord/sir-lancebot#691]
## Description

Would intersplice args and add ᓚᘏᗢ between them

## Reasoning

Because ᓚᘏᗢ

## Proposed Implementation

Kind of like .uwu

## Would you like to implement this yourself?

- [x
] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by janine9vn** [comment]
To clarify, this would take an arbitrary string and add in the cat unicode at various points inside the string?

**Comment by Kronifer** [comment]
Was talking in dev-contrib, was thinking maybe would add the cat to the end of a user's nickname

**Comment by dawnofmidnight** [comment]
I like it where it's stuck between words since it can be used more than once.

**Comment by hypergamer80** [comment]
this is magnificent. for proposed implementation, see dev squid's meme func

**Comment by Kronifer** [comment]
Hmm,  maybe those interested could vote and I'll implement one of them

**Comment by dawnofmidnight** [comment]
Poll in ot0?

**Comment by Shivansh-007** [comment]
I would have moved this into the user's nickname instead, as this is were it is getting used mostly. For example, when i do `.catify`, my nickname should be changed to `Shivansh-007 ᘡᘏᗢ`. 

Another feature I would like to have is, a list of different cats, from which it would be randomly chosen and put into the user's nickname.

**Comment by Shivansh-007** [comment]
> You can do it so if it's just `.catify` with no arguments, it uses the invoker's username, but if there is text after it, it'll catify the text.

Yeah, that sounds better, but how would catify text work, adding cats after each word would not look that great, the cat are a bittt long.

**Comment by AbooMinister25** [comment]
We have somewhat of a catify function in ot0

**Comment by dawnofmidnight** [comment]
Not every word. They could be randomly interspersed throughout the message

**Comment by janine9vn** [comment]
@Kronifer you are assigned! Y'all can have fun discussing the implementation details.

**Comment by AbooMinister25** [comment]
Yeah, it also replaces all the words that have "cat" in them with the ᓚᘏᗢ
