### ISSUE TITLE
Catification

### ISSUE THREAD

**Issue by hypergamer80** [python-discord/sir-lancebot#692]
## Description
We would like to see an addition to the Sir Lancebot commands: `.catify`. This would insert random ᓚᘏᗢ's into a message sent by the invoker of the command.

## Reasoning
This would be useful since it enhances the ᓚᘏᗢ cult.

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x ] Anyone can implement this feature

**Comment by dawnofmidnight** [comment]
#691 is the same thing/

**Comment by Kronifer** [comment]
Yeah I kinda beat you to it

**Comment by janine9vn** [comment]
I'm going to close this as it's a duplicate of #691. We can move discussion there.

**Comment by hypergamer80** [comment]
got it.
