### ISSUE TITLE
Adapt selective trace logging from bot

### ISSUE THREAD

**Issue by Numerlor** [python-discord/sir-lancebot#706]
## Description
Implement selective trace logging from the python-discord/bot#1529 PR, enabling whitelisting or blacklisting certain loggers to emit trace logs instead of always emitting all trace logs with the debug mode.

## Reasoning
Discussed in python-discord/bot#1502

## Proposed Implementation

A new entry for the trace loggers will need to be added to the `Client` config, grabbing its value from the `BOT_TRACE_LOGGERS` 
env var.
The `_set_trace_loggers` function can be copied over from the bot code and called in lancebot's init (possibly with some considerations to differences between the logging setup of the two bots). The default debug levels will have to be changed from trace to debug.

lancebot also sets some levels on the individual handlers, I don't think the difference between them and the root logger is useful as it only affects non debug environments and can be removed, but this may need to be discussed

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [X] Anyone can implement this feature

**Comment by Xithrius** [comment]
@ToxicKidz is this being done, or should I make this up for grabs?
