### ISSUE TITLE
Move the .issue/.pr command into the .github group

### ISSUE THREAD

**Issue by ToxicKidz** [python-discord/sir-lancebot#711]
## Description

The `.issue` command should be moved to the `.github` group, so it would show in the `Github` cog, and the invocation could be `.gh pr`. 

## Reasoning

It makes more sense for it to be in the github group, since this command deals with github, just like `.gh repo` and `.gh user`. We could also use [root aliases](https://github.com/python-discord/sir-lancebot/blob/main/bot/command.py#L8-L10) if there would be any confusion with the change.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by Xithrius** [comment]
So in the end, would we have `.github repo`, `.github user`, `.github issue`, and `.github pr`?

**Comment by KatsumiKougen** [comment]
Oh, of course we would. The thing is, you would really need some _help_ if you want to implement it by yourself.

**Comment by Xithrius** [comment]
@KatsumiKougen 
> Oh, of course we would.

What is this in response to?
> The thing is, you would really need some *help* if you want to implement it by yourself.

I'm not so sure, this would probably be a relatively simple PR to implement.

**Comment by Xithrius** [comment]
Either way, I approve of this occurring.
