### ISSUE TITLE
Add "Math" and "Science" category in .quiz

### ISSUE THREAD

**Issue by Objectivitix** [python-discord/sir-lancebot#719]
## Description
Since the .quiz command currently only has the "General" category which is pretty much only geography and history questions, we propose to add "Math" and "Science", 30 (or more) questions each which would be randomly picked.

## Reasoning
Because it only has "General", and we NEED MORE!

## Would you like to implement this yourself?

- [ x] I'd like to implement this feature with the cat dev team
- [ ] Anyone can implement this feature

**Comment by Objectivitix** [comment]
https://docs.google.com/document/d/1qIbapQUMLD40s5yzrqXZ7n0-6p1z3azpz1O_rPOWTv4

list of math questions, subject to change

**Comment by janine9vn** [comment]
Sounds good! I think the Math and Science categories would go well in this server.

**Comment by Evorage0** [comment]
How about a programming category as well, since its a programming server? I wouldn't say python specific questions, more general knowledge of programming mixed in with some actual programming techniques.

**Comment by Objectivitix** [comment]
that's an incredible idea!!

**Comment by Kronifer** [comment]
McPoggers

**Comment by Objectivitix** [comment]
update: currently have 30 questions in math, 10 questions in science, and 2 in cs. more coming

**Comment by Objectivitix** [comment]
update: currently have 30 questions in math, 30 questions in science, and 16 in cs/python. also did a revamp of the original code so it's compatible with image urls, multiple possible answers, etc.

**Comment by Objectivitix** [comment]
PR'ed
