### ISSUE TITLE
`.snakes` command bug

### ISSUE THREAD

**Issue by ATOMICMAN007** [python-discord/sir-lancebot#723]
## Description

When giving argument `python` in subcommand `get` of command `snakes`, bot returns Wikipedia page of Python programming language instead of returning result related to python snake.

## Steps to Reproduce

Type `.snakes get python`

## Expected Behaviour

An embed which contains information about Python snake retrieved from Wikipedia.
(Not including link of most suitable Wikipedia page but can be found by using a search engine with keywords `python genus Wikipedia`)

## Actual Behaviour

![Screenshot of embed in sir-lancebot-playground   ##channel](https://user-images.githubusercontent.com/71210312/117256141-ea422500-ae67-11eb-9da2-6d81c3b770f7.png)

## Known Impacted Platforms

- [ ] Web
- [ ] Desktop
- [x] Android App
- [ ] iOS App

## Would you like to implement a fix?

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [ ] I'd like to implement the bug fix
- [x] Anyone can implement the bug fix

**Comment by anand2312** [comment]
[This looks like it has been done intentionally](https://github.com/python-discord/sir-lancebot/blob/05ba3de5c99b30a8eba393da1460fae255373457/bot/exts/evergreen/snakes/_converter.py#L27) 😉

**Comment by ATOMICMAN007** [comment]
> [This looks like it has been done intentionally](https://github.com/python-discord/sir-lancebot/blob/05ba3de5c99b30a8eba393da1460fae255373457/bot/exts/evergreen/snakes/_converter.py#L27) 😉 

Ok! 😂
