### ISSUE TITLE
Issue/PR hyperlink embed upgrade

### ISSUE THREAD

**Issue by doublevcodes** [python-discord/sir-lancebot#743]
### What this issue solves

This issue aims to solve two things:

- The format in which issues and pull requests are displayed in the embed that the bot automatically sends.
- The order in which the issues and pull requests are sent. This wasn't part of the original issue but I figure if this is correctly implemented then this could be fixed too.

### Current implementation

Upon mentioning an issue or pull requests in a message such as `sir-lancebot#69` or `bot#420`, the issue/PRs are displayed in an embed in a random order without knowing which issue/PR is which. This is not a problem when a single issue/PR is mentioned but with anymore it becomes hard to figure out which is which quickly. Here is an example:

![image](https://user-images.githubusercontent.com/54081925/118415034-e43a1880-b69f-11eb-83ad-7133e331a9fd.jpeg)

It is unclear which pull request is `site#474` and which is `site#477`.

Currently the [code](https://github.com/python-discord/sir-lancebot/blob/a5d138ef76fec71b2d737e24889c7de494fdbc0d/bot/exts/evergreen/issues.py#L246) uses a `set` and so the order is not preserved and we can't link a URL back to the issue or pull request without doing some fancy URL stuff.

### Proposed implementation

[This line](https://github.com/python-discord/sir-lancebot/blob/a5d138ef76fec71b2d737e24889c7de494fdbc0d/bot/exts/evergreen/issues.py#L246) should change from 
```py
issues = set(issues)
```
to
```py
issues = list(dict.fromkeys(issues))
```
And on [this line](https://github.com/python-discord/sir-lancebot/blob/main/bot/exts/evergreen/issues.py) we could simply just change the format of the string as it is added onto the embed to include the issue/PR number.

### Proposed Implementation 2

This implementation involves the [`more_itertools`](https://more-itertools.readthedocs.io/en/stable/) library. Specifically, the `more_itertools.unique_everseen` function which would mean the previous change would instead need to be to:
```py
issues = list(more_itertools.unique_everseen(issues))
```
This comes with the advantage of `more_itertools` being used in other parts of Sir Lancebot.

### End result
Going with either implementation, we would like to reach an embed that looks more like this, namely, it includes the issue/PR number in the hyperlink. Example:

![3DC12400-A012-4CD2-B6DA-A8249850D016](https://user-images.githubusercontent.com/54081925/118415907-e6eb3c80-b6a4-11eb-9abf-2bfd05147a11.png)
## Reasoning
I think this would be useful as it prevents community members from clicking on each hyperlink and checking if they managed to somehow click the correct link. Otherwise, going back and trying again. It just saves time and effort.

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [X] Anyone can implement this feature

**Comment by ChrisLovering** [comment]
Looks good to me, consider this approved. FWIW I prefer the second implementation proposal

**Comment by D0rs4n** [comment]
Hi! I would like to give it a try! 👍

**Comment by Xithrius** [comment]
@D0rs4n Is this currently being worked on?

**Comment by D0rs4n** [comment]
Yes, it is. Unfortunately, I'm waiting for the same [PR(merge issues into GithubInfo cog)](https://github.com/python-discord/sir-lancebot/pull/778) to be merged. That PR was also gonna introduce minor bug fixes in the `.issue` command, but it was removed.

**Comment by Xithrius** [comment]
Ah yes, we're just waiting on Toxic to fix things up and we should be good.

**Comment by D0rs4n** [comment]
OK, I'll push my PR**s** right after it is merged! 👍

**Comment by Xithrius** [comment]
Very cool.
