### ISSUE TITLE
Question missing a possible correct answer in `trivia_quiz.py`

### ISSUE THREAD

**Issue by Objectivitix** [python-discord/sir-lancebot#747]
## Description
The following math question with ID of 228 should have one more possible correct answer in the database.

## Steps to Reproduce
1. input the command `.quiz math 30`.
2. wait for it to reach that question (randomly generated, might take a while)
3. input the answer "centisecond".

It won't recognize it as a correct answer.

## Expected Behaviour
It should recognize it as a correct answer.

## Actual Behaviour
It doesn't.
![image](https://user-images.githubusercontent.com/79152594/118878548-0dd48900-b8c6-11eb-967a-43b08252d6f4.png)

## Known Impacted Platforms

- [x] Web
- [x] Desktop
- [x] Android App
- [x] iOS App

## Possible Solutions
Just add "centisecond" after the answers in question 228 in the json

## Would you like to implement a fix?

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [x] I'd like to implement the bug fix
- [ ] Anyone can implement the bug fix

**Comment by soham4abc** [comment]
Is this issue not yet approved. I did make a pull request for this one
