### ISSUE TITLE
Add a .reverse command

### ISSUE THREAD

**Issue by Kronifer** [python-discord/sir-lancebot#749]
## Description

Add a .reverse command that reverses a submitted string.

## Reasoning

Idk, as a joke I guess, could go with fun.py.

## Proposed Implementation

Basically, something like this 
```py
@commands.command()
async def reverse(self, ctx: commands.Context, *, text: str = "reverse time"):
    text = text[::-1]
    await ctx.send(f"> {text}")
``` 

But if no args are given, we could reverse the users profile picture and send it in an embed.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by JakeM0001** [comment]
I like the idea, I wouldn't have it send the message in the ">". But other than that it would fit right into fun.py.

**Comment by Xithrius** [comment]
@Kronifer You can go ahead and implement this if you'd like.

**Comment by Kronifer** [comment]
Not hard, sure

**Comment by Xithrius** [comment]
Very cool.
