### ISSUE TITLE
Add "cs" and "python" categories to the `.quiz` command

### ISSUE THREAD

**Issue by Objectivitix** [python-discord/sir-lancebot#753]
## Description
This is an extension of PR #726. It was planned to also add these two categories in that PR, but we didn't get enough quiz entries on "cs" and "python" and thus it couldn't be implemented. But now, thanks to lak, we got 30 questions each, which is enough!

## Reasoning
I believe this would be beneficial to our community because they're programming, computer science and Python questions. These questions are very related to our server.

## Proposed Implementation
Since all the backend code work was done in 726, I simply need to add them to the JSON.

## Would you like to implement this yourself?
- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by Akarys42** [comment]
I shall approve this issue

**Comment by Objectivitix** [comment]
THANK YOU AKARYS! WOOHOO

**Comment by Objectivitix** [comment]
Database has been completely copied to the JSON. Next step is to test, then PR Time™️

**Comment by Objectivitix** [comment]
All questions tested. PR Time™️ tmr

**Comment by wookie184** [comment]
Seems like this can be closed
