### ISSUE TITLE
ascii command

### ISSUE THREAD

**Issue by NovaTohsaka** [python-discord/sir-lancebot#754]
## Description
A command to convert the text args (passed to the command by a member) into an ascii art. 

## Reasoning
Well, just a fun command! People may find it fun using. 

## Proposed Implementation
Implementation will require an installation of third-party lib `pyfiglet`.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by Brodevil** [comment]
I don't know that this Idea is good or not 
But I Guess using pyfiglet this can be done easily

**Comment by NovaTohsaka** [comment]
> I don't know that this Idea is good or not

Me neither but this is how a basic output will look like if this helps. (Not final product.)
![abc](https://user-images.githubusercontent.com/84652009/119249957-779cad80-bbba-11eb-902f-11a800ba5bbb.png)

**Comment by HassanAbouelela** [comment]
I'm not convinced this'll lead to anything more than spam. People can already make ascii art outside of discord and paste in, and as a mod, 99% of that is spam, usually disruptive, and probably leads to some sort of infraction.

**Comment by NovaTohsaka** [comment]
> I'm not convinced this'll lead to anything more than spam. People can already make ascii art outside of discord and paste in, and as a mod, 99% of that is spam, usually disruptive, and probably leads to some sort of infraction.

yeah, understandable.
