### ISSUE TITLE
Inconsistency: "Dangling Comma" on multiline data structures and function calls

### ISSUE THREAD

**Issue by Objectivitix** [python-discord/sir-lancebot#762]
## Description
There is a project-wide inconsistency within Sir Lancebot's code. For multiline data structures and function calls such as
```py
foo = [
    "yeet",
    "cat",
    "lololol"
]
```
, some people think we should add a trailing/"dangling" comma at the last line while others don't.

In the code, there are instances where the dangling comma is used and instances where it is not. This can be misleading for new people wanting to contribute (such as me, last time I was discussing with ToxicKidz and Kronifer on this problem, I thought dangling commas were good practice).

Here are my thoughts on why these end-trailing commas are beneficial:
1. Some argue that such a miniscule change won't affect readability and instead simply adds extra stuff, but I think that it makes code more symmetrical and pleasant on the eyes (all lines will have the same format).
2. Easy extendability: if one needs to add one more entry, this will prevent them from forgetting to add a comma before newlining.
3. There are multiple articles on the Internet giving even more reasons, such as easy copy-paste code manipulation.

## Screenshots
[battleship.py, multiline data structure, dangling comma](https://user-images.githubusercontent.com/79152594/120651283-ffa17380-c454-11eb-98d9-b0626865faee.png)
[battleship.py, function parameters, no dangling comma](https://user-images.githubusercontent.com/79152594/120651504-3f685b00-c455-11eb-8e95-37aa6e6c6c83.png)
[scarymovie.py, multiline data structure, no dangling comma](https://user-images.githubusercontent.com/79152594/120651639-6161dd80-c455-11eb-8df1-f78de9535e99.png)
[scarymovie.py, function call, no dangling comma](https://user-images.githubusercontent.com/79152594/120651777-80f90600-c455-11eb-9bea-ad0381c5e215.png)
[_internal_eval.py, multiline data structure, dangling comma](https://user-images.githubusercontent.com/79152594/120652228-f1078c00-c455-11eb-9c5b-6cc09d4c864b.png)
[_internal_eval.py, function call, no dangling comma](https://user-images.githubusercontent.com/79152594/120652424-27dda200-c456-11eb-8ae5-49a66f702a48.png)

You get the idea; it's everywhere. Note that the use of **NO** dangling comma is more popular... however my thoughts still stand.

## Possible Solutions
Vote and choose on one way: either delete all dangling commas or add them to ones without dangling commas. IMO it would also be a good idea to enforce the result - either delete or add - in the lint, and add it to our style guide.

## Would you like to implement a fix?

- [ ] I'd like to implement the bug fix
- [x] Anyone can implement the bug fix

**Comment by Kronifer** [comment]
number 2 can just be avoided by not being stupid

**Comment by Kronifer** [comment]
copy-pasting code for an open source contribution is frowned upon unless you wrote it somewhere else

**Comment by Objectivitix** [comment]
@Kronifer for number 2, everyone make mistakes. For number 3, I mean this kind of copy-paste https://medium.com/@nikgraf/why-you-should-enforce-dangling-commas-for-multiline-statements-d034c98e36f8

**Comment by janine9vn** [comment]
So there shouldn't need to be a discussion about this nor should we have to go back and update our codebase.
Dangling commas should be the standard, see [PEP8](https://www.python.org/dev/peps/pep-0008/#when-to-use-trailing-commas). It also ensures the git blame is accurate if someone adds another option to an already existing list.

Our style guideline falls back to PEP8 for this, so there really isn't a need for a discussion about this.

**Comment by Objectivitix** [comment]
@janine9vn currently it's not the standard. Should we do a project-wide refactoring?

**Comment by janine9vn** [comment]
No. Adding trailing commas isn't critical enough to warrant a project-wide refactoring. Those types of PRs are generally bad ideas and hell to review. While we try to maintain a standard this is still Sir Lancebot, which is a project designed for new people to learn how to contribute to open source projects. It's not critical that we follow the style guideline 100%, but when noticed we should try to follow it and make sure the code follows it.

**Comment by Objectivitix** [comment]
@janine9vn got it. Thank you!

**Comment by Objectivitix** [comment]
@janine9vn
> While we try to maintain a standard this is still Sir Lancebot, which is a project designed for new people to learn how to contribute to open source projects. It's not critical that we follow the style guideline 100%

I noticed the same kind of inconsistency in our main `bot` project as well... would that be not worth a refactoring either? I'm sure this can be automated with some more Python Magic :tm:

**Comment by jb3** [comment]
No, it's not worth refactoring on any of our projects.

Minor modifications like this can be amended as and when the code is touched, if we have automated PRs with hundreds of lines changed then it just results in conflicts that someone has to work out. It's the same thing as typehints, we're not going to retroactively upgrade them to 3.9 style (`dict[str, str]` vs. `typing.Dict[str, str]`) because it doesn't bring us anything, it just adds extra labour for the poor soul who has to ensure that no conflicts crop up.

**Comment by Objectivitix** [comment]
@jb3 alright. Thank you for explaining this, I didn't realize that this kind of refactoring can arise conflicts.
