### ISSUE TITLE
Handle Tic-Tac-Toe draw results.

### ISSUE THREAD

**Issue by kosayoda** [python-discord/sir-lancebot#771]
## Description
![image](https://user-images.githubusercontent.com/41782385/120993916-93a56f00-c7b6-11eb-8638-89cfabba4e43.png)

The `!ttt history show` command displays the past state of a game in an embed. Currently, the embed does not account for draws, and instead assumes that every game has a winner and a loser.

The embed should display a draw condition similar to how the `!ttt history` command itself does it.

## Would you like to implement a fix?

- [ ] I'd like to implement the bug fix
- [X] Anyone can implement the bug fix

**Comment by CasualCoder99** [comment]
I'm absolutely a beginner to open source but good with python. I figure I can solve this bug if assigned to this issue.

**Comment by kosayoda** [comment]
@CasualCoder99 Go ahead!
