### ISSUE TITLE
add topic to py_topics

### ISSUE THREAD

**Issue by swordysrepo** [python-discord/sir-lancebot#775]
## Description

looking to add "  Which recently discovered Python module has changed your general use of Python?" 
as a question to the #python-general channel

## Reasoning

i see it's a great topic to have a discussion about . I've just picked up sql alchemy and i've seen it makes a great difference in how i use python . i first heard about it in voice chat on the discord

## Proposed Implementation

add "  Which recently discovered Python module has changed your general use of Python?"  to py_topics.yaml 

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by wookie184** [comment]
Sounds like a good question. Since @Xithrius already has #792 open and it's a simple addition, it may be easier for him to just add it to that, unless you wanted to do it yourself?

**Comment by Xithrius** [comment]
Added.
