### ISSUE TITLE
Colour command to display colours in various formats

### ISSUE THREAD

**Issue by vcokltfre** [python-discord/sir-lancebot#776]
## Description
A command, `.colour` that would allow people to input a given colour and Lance will show the actual colour in an embed/image.
- `.colour hex <hex>`
- `.colour rgb <r> <g> <b>`
- `.colour hsl <h> <s> <l>`
- `.colour cmyk <c> <m> <y> <k>`

## Reasoning
Especially with things like the pixels event, and in cases like Discord embeds, it would be nice to be able to see what a specific colour is, as well as being essentially able to convert colours.

## Proposed Implementation
The commands would result in a common embed format which would contain the colour as the thumbnail image and embed colour and would show the colour value in each of the other formats.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by ChrisLovering** [comment]
It seems like something like this already exists https://github.com/python-discord/sir-lancebot/issues/677

**Comment by vcokltfre** [comment]
How does this always happen aaaaa i look and it doesn't exist and I make an issue and then it does
