### ISSUE TITLE
Rickroll Avatar

### ISSUE THREAD

**Issue by 12944qwerty** [python-discord/sir-lancebot#783]
## Description
An Avatar modifier that will return a gif of your Avatar, but turns into a rickroll

## Reasoning
Just a fun trick when someone asks for your profile and if you have nitro and want it. Also, it's just a fun command lmao.

## Proposed Implementation
Don't have it yet. I can't seem to find the person who's pfp looks like this lmao (or any recording). I can make one though if needed. ~~Don't want to do unnecessary work if this gets rejected.~~

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by 12944qwerty** [comment]
Ah, found it! ![Rick roll pfp](https://cdn.discordapp.com/avatars/652979428456136704/a_51e3bbc6143378d2397e9d36c28d5323.gif?size=256)

**Comment by Xithrius** [comment]
I'm worried about how much computational power this would take.

@HassanAbouelela random poke, what do you think about this?

**Comment by Xithrius** [comment]
Due to the concern of how long a animated avatar could be, this can cause large amounts of resources to be used up.

Maybe another feature can be created with rickrolling? If so, please make another issue.
