### ISSUE TITLE
Wrong title in love calc when 0% love

### ISSUE THREAD

**Issue by OculusMode** [python-discord/sir-lancebot#784]
## Description
In love calculator when love is found 0% it does not show "There's no real connection between you two" like in [json file](https://github.com/python-discord/sir-lancebot/blob/main/bot/resources/valentines/love_matches.json).

## Steps to Reproduce
Found it while getting love as 0%

## Expected Behaviour
It should be "There's no real connection between you two" as per json(I did try to check if it was sarcasm for 0% but that's not the case)

## Actual Behaviour

![image](https://user-images.githubusercontent.com/37273899/124795151-62fb5580-df6d-11eb-8fd5-ac7da218e461.png)
![image](https://user-images.githubusercontent.com/37273899/124795233-727a9e80-df6d-11eb-9f4b-69c627a56762.png)

## Known Impacted Platforms
- [x] Web
- [x] Desktop
- [x] Android App
- [x] iOS App

## Possible Solutions
Something should be wrong here:
```
        m = hashlib.sha256(who.encode() + whom.encode())
        # Mod 101 for [0, 100]
        love_percent = sum(m.digest()) % 101

        # We need the -1 due to how bisect returns the point
        # see the documentation for further detail
        # https://docs.python.org/3/library/bisect.html#bisect.bisect
        index = bisect.bisect(LOVE_DATA, (love_percent,)) - 1
```
in [file](https://github.com/python-discord/sir-lancebot/blob/main/bot/exts/valentines/lovecalculator.py)

## Would you like to implement a fix?

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [ ] I'd like to implement the bug fix
- [x] Anyone can implement the bug fix

**Comment by Akarys42** [comment]
While this truly is a bug, I think it is quite fun and it is a known hidden fact of our bot, I would actually vote to not fix it.

**Comment by OculusMode** [comment]
haha yeah, @Akarys42 I actually thought that this may be a sarcastic intended `feature` too, but looking at code, it's indeed bug.
But +1 to not fixing the bug lol(or maybe fixing the bug and changing the value of 0% as in json for current funny output.)

**Comment by Xithrius** [comment]
> While this truly is a bug, I think it is quite fun and it is a known hidden fact of our bot, I would actually vote to not fix it.

This be a bug. I approve of this issue being fixed.
