### ISSUE TITLE
.epoch command

### ISSUE THREAD

**Issue by janine9vn** [python-discord/sir-lancebot#787]
## Description
Discord's timestamp feature will be rolling out to all platforms soon... ish ... probably. This timestamp takes an epoch timestamp to use in a rich/dynamic updating field. More information about this can be found [here](https://discord.com/developers/docs/reference#message-formatting-timestamp-styles). I am not ~~Xith~~ a bot, therefore I don't know specific epoch times off the top of my head.

This command would take a simple datetime or a duration and then Lancebot would reply with the equivalent epoch time.

## Proposed Implementation
- Ideally this command should take a simple datetime. Something like 5/6/2021 14:00. A decision will have to be made if that's going to be American or Rest-Of-The-World format though. It will also have to make some assumptions about the seconds and microseconds and whatnot.
- It should take into account which TZ the command was invoked in and not use the bot's local time.
- It would be neat if it also took a duration! Like if I passed it 40M, it would give me the epoch time for 40 minutes from now.
- Lancebot should reply in a non-embed so mobile users can easily copy and paste the provided result.
- Obvious error checks for times before epoch and whatnot. 

## Would you like to implement this yourself?
Anyone can implement this feature! I am fairly busy and probably won't have time for this until December at best.

**Comment by ChrisLovering** [comment]
We can't get the timezone of the user calling the command, I propose we use the same time/duration converter we have in Python.

This converter accepts durations and ISO date times.

**Comment by VikranthMaster** [comment]
@ChrisLovering  Did u found anything ?

**Comment by VikranthMaster** [comment]
I want to implement this

**Comment by ChrisLovering** [comment]
This is the converter I was referring to, that we use in Python.
https://github.com/python-discord/bot/blob/133a1349ee52cc774c3c991a0753fd12f478a010/bot/converters.py#L570

It's a union of https://github.com/python-discord/bot/blob/133a1349ee52cc774c3c991a0753fd12f478a010/bot/converters.py#L317-L332 and https://github.com/python-discord/bot/blob/133a1349ee52cc774c3c991a0753fd12f478a010/bot/converters.py#L372-L411.

Here's a simple example of where it's used https://github.com/python-discord/bot/blob/133a1349ee52cc774c3c991a0753fd12f478a010/bot/exts/moderation/stream.py#L95-L150

**Comment by ChrisLovering** [comment]
> I would like to implement this

Sure! Once it's finished planning and accepted, we can assign it to you.

**Comment by VikranthMaster** [comment]
> > I would like to implement this
> 
> Sure! Once it's finished planning and accepted, we can assign it to you.

Cool thanks ^^

**Comment by Xithrius** [comment]
@VikranthMaster I think the planning stage is done, would you like to implement this?

**Comment by VikranthMaster** [comment]
@Xithrius I thought u guys implemented it already

**Comment by Xithrius** [comment]
Have we? Let me check.

**Comment by Xithrius** [comment]
@VikranthMaster We have not.

**Comment by doublevcodes** [comment]
> We can't get the timezone of the user calling the command, I propose we use the same time/duration converter we have in Python.
> 
> 
> 
> This converter accepts durations and ISO date times (Timezone naive) . It may also be in lancebot already, but I can't check right now. 

I think `discord.Message.created_at` is tz aware, is it not?

**Comment by ChrisLovering** [comment]
> > We can't get the timezone of the user calling the command, I propose we use the same time/duration converter we have in Python.
> > This converter accepts durations and ISO date times (Timezone naive) . It may also be in lancebot already, but I can't check right now.
> 
> I think `discord.Message.created_at` is tz aware, is it not?

It is tz-aware yes, but that just means that it includes the tzinfo that it's UTC, it does not include the timezone of the invoker.

**Comment by doublevcodes** [comment]
> > > We can't get the timezone of the user calling the command, I propose we use the same time/duration converter we have in Python.
> 
> > > This converter accepts durations and ISO date times (Timezone naive) . It may also be in lancebot already, but I can't check right now.
> 
> > 
> 
> > I think `discord.Message.created_at` is tz aware, is it not?
> 
> 
> 
> It is tz-aware yes, but that just means that it includes the tzinfo that it's UTC, it does not include the timezone of the invoker.

Ah ok thanks, I misunderstood. I obviously need to go change some code I've written. 😅

**Comment by VikranthMaster** [comment]
@Xithrius No offense would love to Implement but my exams are going on currently..so..sorry 😔

**Comment by Xithrius** [comment]
@VikranthMaster Good luck with your exams!

**Comment by VikranthMaster** [comment]
> @VikranthMaster Good luck with your exams! I'll assign this to you now, just be sure to focus on that education!

Thanks :) I will :)

**Comment by janine9vn** [comment]
Thinking about this, I think it would be nice if this command accepted some sort of indication of tz. So it would have a converter and accept both:
- Timezone (i.e. EST, EDT, IST)
- UTC offset

For timezones, since some of them can be ambiguous, if there's more than one option that fits this, you can use the Discord Button components to have the user select the correct timezone. 

I believe this all can be accomplished with the help of arrow.

**Comment by doublevcodes** [comment]
> I believe this all can be accomplished with the help of arrow.
What do you mean by "arrow" specifically?

**Comment by Xithrius** [comment]
@doublevcodes https://pypi.org/project/arrow/

**Comment by lxnn** [comment]
@VikranthMaster are you still working on this? How's it coming along?

**Comment by KittyBorgX** [comment]
Hey, sorry for the late update but i may not be able to work on this as i'll be away for a month :(

**Comment by Sn4u** [comment]
I'm quite interested, could I take your place? Are you still working on this @mathstrains21?

**Comment by mathstrains21** [comment]
Hi!

We haven't actually done any work on it yet! Could you message me on
discord please? (mathstrains19#2057)

**Comment by Sn4u** [comment]
I had an idea to implement a drop-down where you can select different timestamp styles to be used with discord. I've inserted a screenshot below. Is this something we would want?
![image](https://user-images.githubusercontent.com/35849006/143723786-7906d54d-4f0d-4270-ad0f-28f6d0464091.png)
