### ISSUE TITLE
Display more useful information in .issue command

### ISSUE THREAD

**Issue by vcokltfre** [python-discord/sir-lancebot#788]
## Description
Since introducing inline issue resolving, i.e. `quackstack#9`, the .issue command has been essentially useless - it contains the same information but with confusing syntax. I propose that we make the command show more detailed information about a single issue or PR. This information would include author info, creation date, and issue tags.

## Reasoning
The command is, currently, essentially useless. This would mean that we could make use of the command again for better information which is unfeasible to show in the inline resolver's embed.

## Proposed Implementation
In terms of technical detail, it would essentially just use an extra few fields from the GitHub API data. As for user-facing detail, the embed's colour would be the colour of the 'thing' the issue/PR was, for example an open PR would be green, a closed issue red. Looking something like this:
![image](https://user-images.githubusercontent.com/16879430/126282667-4438935b-ec28-499c-baef-c061ca9448aa.png)

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by ChrisLovering** [comment]
I'm tempted to delete the `.issue` command entirely.

As you said it doesn't get used often, in favour of the on_message listener. I don't think adding more info to the embed is worth the time and maintenance, since you can get the most information by just clicking on the link to github.

**Comment by dawnofmidnight** [comment]
I'm in favor of what Chris said as well. Plus, the default meta image that GitHub shows is already really nice and provides the information in a clean, readable manner.

**Comment by Akarys42** [comment]
I don't see myself using a command or even automatically linking anymore instead of the new preview embeds, to be honest. I vote for removing the command.

**Comment by doublevcodes** [comment]
I think removal of the command seems better as well

**Comment by ChrisLovering** [comment]
We have decided to delete this commend entirely in #778
