### ISSUE TITLE
Pokemon Game

### ISSUE THREAD

**Issue by VikranthMaster** [python-discord/sir-lancebot#789]
**PokemonGame**
It would be fun if we add more games..making it intresting

**Reasoning**
Overall would be really fun to play with and later i will add some more features to it

**Proposed Implementation**
Got this idea from watching pokemon 😅..would like to implement this "who is that pokemon" from classic pokemon series..add then later people can view the stats to it

I would like to implement this feature myself

**Comment by JacobMonck** [comment]
Can you give some more information on what the commands would be?

**Comment by VikranthMaster** [comment]
> Can you give some more information on what the commands would be?

well was thinking like in a particular channel when a person messages, at random a Pokemon appears then when they guess the Pokemon name correctly they will be added to their pokedex..in future I will add battles and gym

**Comment by Kronifer** [comment]
I dont think this fits the theme of the server

**Comment by VikranthMaster** [comment]
> I dont think this fits the theme of the server
its just a extra game that's all for sir Lanceot

**Comment by JacobMonck** [comment]
Yeah, this doesn't really fit our server too well. It's a great idea but I don't think it suits our server.

**Comment by VikranthMaster** [comment]
> Yeah, this doesn't really fit our server too well. It's a great idea but I don't think it suits our server.

at least we can try right?

**Comment by bsoyka** [comment]
> at least we can try right?

There's really no point in trying something that wouldn't fit or be used in our server. You're always welcome to make your own bot for your own server, but if multiple staff have said it wouldn't fit here, there's really no reason to make this for Python Discord.

**Comment by VikranthMaster** [comment]
> > at least we can try right?
> 
> There's really no point in trying something that wouldn't fit or be used in our server. You're always welcome to make your own bot for your own server, but if multiple staff have said it wouldn't fit here, there's really no reason to make this for Python Discord.

alright
