### ISSUE TITLE
Allow bookmark command  `.bm` by users in help channels

### ISSUE THREAD

**Issue by minalike** [python-discord/sir-lancebot#811]
## Description

The proposal is to allow users to run the bookmark `.bm` command in help channels. Currently the command can be run in some other channels such as off-topic, but it is not allowed in the help channels. 

## Reasoning

Sometimes I wish to bookmark a particularly helpful response I receive in a help channel without having to go to #bot-commands or #sir-lancebot-playground. It would be very nice for users to be able to run `.bm` within their current help channel.

## Proposed Implementation

Whitelist `.bm` command in channels under the help category. 

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by ChrisLovering** [comment]
Seems like a good idea to me. With the recent changes to the bookmark command, the ability to react to an embed to receive a bookmark, I don't feel like it would be too spammy either.

Whoever looks into implementing this can take a look at the issue command `bot.exts.evergreen.issues` to see how it does it. Specifically the `whitelist_override` decorator.

**Comment by Xithrius** [comment]
I've approved this, anyone can take this up.
