### ISSUE TITLE
Uwuification unsatisfactory.

### ISSUE THREAD

**Issue by gitautas** [python-discord/sir-lancebot#812]
## Description and reasoning

The current uwuification algorithm is very simple and frankly unsatisfactory, as there have been many recent advances in the field of uwuification I believe that Sir Lancebot would be greatly improved by the addition of a more feature-rich uwugorithm.

## Proposed Implementation

I personally have written a more advanced [uwuifier](https://github.com/gitautas/slowo) in python that does not depend on any external libraries and am willing to implement it into Sir Lancebot.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by HassanAbouelela** [comment]
Hey! Congrats on finishing your project!

I’m not personally in favor of this idea. There are costs to implementing any feature, which most people don’t consider. The most obvious costs are implementation, and review, but the more expensive ones are maintenance.

I really don’t care all that much about this command, and I don’t think it’s worth investing effort into making it some super generator that will replace all generators (TM).

If the current implementation is unsatisfactory, let’s remove it.

**Comment by gitautas** [comment]
That's a valid concern, I personally believe that it's a fine feature, also with things like this, once they're up and running, maintenance isn't a real burden since there are no additional dependencies and there would be a single call to a black box which alters a string, not exactly a towering monolith of complexity. I'd personally be more interested in seeing the project grow, not regress in terms of features. 

Either way, not my call.

**Comment by JacobMonck** [comment]
I have to agree with Scale on this one, I think it will take way too much time and effort for just one command that only a few people will use. I don't see a problem with the current implementation honestly.

**Comment by MrHemlock** [comment]
> If the current implementation is unsatisfactory, let’s remove it.

I disagree with this.  Lancebot is, at its whole, a fun bot.  If people want to improve on existing things, more power to them.  

I've read the code for the implementation @gitautas wrote up.  Since it uses all built-ins and execution/processing time is minimal, there is very little strain on the system itself.  @gitautas Has also mentioned (in voice chat) that they are more than willing to make it native to Lancebot instead of having it as an external dependency.

Again, looking over the code they have, the only effort or work I foresee on our part is review.  Implementation goes through @gitautas, maintenance is always a concern for anything, but this is much less labor intensive than other issues we've accepted in the past.

**Comment by gitautas** [comment]
@lemonsaurus currently the insertion of emojis and the stuttering are handled by a weighted RNG, which by default sets both values to 20%, meaning the every fifth word is stuttered and every fifth space has an emoji or word inserted, this can be tuned to the desires of either the staff, or the user by passing additional arguments.

**Comment by lxnn** [comment]
I, for one, am glad that we can remain on the cutting-edge in this vitally important area. All too often, the most advanced uwugorithms are locked up in the ivory towers of academia, where they are unable to fulfil the enormous potential they have to enrich the lives of ordinary people. Thank you, @gitautas, humbly.

**Comment by lemonsaurus** [comment]
I don't have a problem with this idea, I'll leave it to you guys to find the right "intensity" for our use.
