### ISSUE TITLE
Improve the error message when .bm fails to convert a message id

### ISSUE THREAD

**Issue by ChrisLovering** [python-discord/sir-lancebot#819]
## Description

I propose that we change the error message given to users when they run the bookmark command and it fails to find the message they specified.

## Reasoning

Users sometimes assume that just giving a message ID to the bookmark command is enough to bookmark a message, even if it's in another channel.

However, if the message they are trying to bookmark is in another channel the command will fail since it cannot find the message they are referring to.

See [here](https://canary.discord.com/channels/267624335836053506/607247579608121354/880463302319304754) for an example

## Proposed Implementation

Change this error message to include information about having to include the channel id, or give a full link, if the message they want to bookmark is in another channel.
https://github.com/python-discord/sir-lancebot/blob/8cac7f077b14265783ae558fff65cbcd2bef00d6/bot/exts/evergreen/bookmark.py#L99

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by KittyBorgX** [comment]
My username : KIttyBorgX [ even in discord ]

**Comment by KittyBorgX** [comment]
Before i commit, does this sound good ? - `You must provide a message id from this channel or copy the link of a message in a different channel for bookmarking `

**Comment by ChrisLovering** [comment]
Copying the docstring from Discord.py could be good too.
```
    The lookup strategy for message ID is as follows (in order):

    1. Lookup by "{channel ID}-{message ID}" (retrieved by shift-clicking on "Copy ID")
    2. Lookup by message ID (the message **must** be in the context channel)
    3. Lookup by message URL
``` I suggested opening a PR and getting feedback during review :)

**Comment by KittyBorgX** [comment]
Sure!

**Comment by KittyBorgX** [comment]
@ChrisLovering is it possible to transfer this from my name to someone else? I've been a bit busy with school and exams 🥲

**Comment by ChrisLovering** [comment]
Sure! I'll PR something now.
