### ISSUE TITLE
Add Mastermind game command

### ISSUE THREAD

**Issue by DMFriends** [python-discord/sir-lancebot#823]
## Description

For those who don't know what Mastermind is, it is a 2 player game, where 1 of the players is the "codemaker" and the other is the "codebreaker". The codemaker thinks of a combination (code) that consists of 4 different colors. Then, the codebreaker tries to guess the codemaker's code.
Here is a complete list of rules: https://magisterrex.files.wordpress.com/2014/07/mastermindrules.pdf
**Please note that these rules are for the actual board game. This is obviously a computer version of the game, so not all parts of the rules will apply.**
The bot will be the codemaker. 

## Reasoning

I think it is a very fun game that many community members will love! I have played it with my family and friends and they all love it very much! 

## Proposed Implementation

I want to add a new cog for Sir Lancebot to run this game, with the command `.mastermind`
Alias: `.mstrmd`

## Would you like to implement this yourself?
 

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by ChrisLovering** [comment]
As wookie said, we already have this game in the bot, just under a different theme.

Please feel free to take a look at the snake antidote game source and see how it compares to your planned implementation. You could always see if you'd do it differently or if there are improvements to be made.

Alternatively, you can wait a few days for the discord.py 2.0 PR to be merged, and re-write snake antidote with buttons!
