### ISSUE TITLE
Bookmark command makes the bot DM a user without reacting to the pin

### ISSUE THREAD

**Issue by KittyBorgX** [python-discord/sir-lancebot#825]
## Description
On running the bookmark command, the bot asks the user to react if they want the bookmark to be sent but the bot sends the bookmark to the user even if the user doesn't react

## Steps to Reproduce
1. Go to #sir-lancebot-playground
2. Bookmark any message with the .bm command
3. DO not react with the push pin 
4. Observe how the bot sends the message to you regardless

## Expected Behaviour
The bot should send the message only when the user reacts with the push pin emoji 

## Actual Behaviour

The bot sends the message to you even if you didnt react

## Known Impacted Platforms

- [x] Web
- [x] Desktop
- [ ] Android App
- [x] iOS App

## Possible Solutions

Send the message on react or delete the message of reacting altogether

## Would you like to implement a fix?

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [x] I'd like to implement the bug fix
- [ ] Anyone can implement the bug fix

**Comment by Xithrius** [comment]
This is intended. If you active the bookmark command, it will send you the link. 

The reaction is for anyone else that wants to also bookmark that same message.

**Comment by KittyBorgX** [comment]
Oh alright
