### ISSUE TITLE
Duplicate bookmark prevention 

### ISSUE THREAD

**Issue by KittyBorgX** [python-discord/sir-lancebot#826]
## Description

When a user has already bookmarked a message, we check if the same message is already bookmarked and warn the user regarding the same

## Reasoning
This feature would help detect duplicate bookmarks 

## Proposed Implementation
No ideas as if now :)

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by ChrisLovering** [comment]
I'm not quite following what it is you're trying to describe here.

If you're referring to someone book marking a message, then removing their reaction and reacting again, we already check for this, and it does not re-send the bookmark.

https://github.com/python-discord/sir-lancebot/blob/0da256ca8986700e9c288f26b9db9c8e0f842465/bot/exts/evergreen/bookmark.py#L121-L122

**Comment by KittyBorgX** [comment]
oh weird, the bot dm'ed me twice, must be a one time glitch. Thanks for letting me know chris, ill limit and edit the issue to only the second part

**Comment by ventaquil** [comment]
The bot doesn't remove the reaction (even after bookmark was sent and we react again and again), is it okay too?

**Comment by KittyBorgX** [comment]
Yep, thats the issue currently
