### ISSUE TITLE
Real Python command lists more than articles

### ISSUE THREAD

**Issue by Bluenix2** [python-discord/sir-lancebot#828]
## Description
When using the Real Python command and inspecting the links, you'll find that some links are courses, lessons, or quizes.

## Steps to Reproduce
Use the `.rp` command with `concurrency` as search words.

## Expected Behaviour
The point of the Real Python command is to provide articles, it should only bring up articles per its purpose.

## Actual Behaviour
Currently you may receive other medias that Real Python produces, which is unwanted.

## Possible Solutions
The fix may be pretty easy, we should be filtering out any articles where the URL is `BASE/courses/*`, `BASE/quizzes/*`, `BASE/lessons/*`.

In my opinion I don't think we should be pulling more articles, as the further down we go the less accurate the search will be.

All articles are under the `BASE/*` URL so it should be easy to only exclude the non-article content.
## Would you like to implement a fix?

- [ ] I'd like to implement the bug fix
- [x] Anyone can implement the bug fix

**Comment by ChrisLovering** [comment]
They RealPython search API has a `kind` query parameter. It would be  acase of setting this query param to `article` to just get articles.
