### ISSUE TITLE
Add Hangman game command

### ISSUE THREAD

**Issue by DMFriends** [python-discord/sir-lancebot#836]
## Description

I created a Hangman game in Python and would like to add it to Sir Lancebot via a new cog.

## Reasoning

I think Hangman is a game I am sure many people will want to play!

## Proposed Implementation

I would like to add a new cog to Sir Lancebot with the command `.hangman`

The user will be given a set of underscores, line by line, which indicates the word that the computer (bot) has chosen. The user has to input their guess, which can be any (lowercase) letter in the alphabet. The user will have 12 tries. After each guess, the bot will tell the user if they guessed the letter correctly or not. If the user does _not_ guess the letter correctly, the bot will say that you have 1 less try left after each guess. If the user _does_ guess it correctly, the bot will replace the underscore that has that letter in the correct spot with that letter, if that makes sense.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by ChrisLovering** [comment]
Could you please fill out the `Proposed Implementation` section with how you propose to implement this game?

**Comment by DMFriends** [comment]
@ChrisLovering Didn't I do that?
"I would like to add a new cog to Sir Lancebot with the command `.hangman`"

**Comment by ChrisLovering** [comment]
Yes, but could you explain how you propose it would work? Does the user get shown an image? does it use text, emojis, buttons, all of the above?

Actually describe what it is you plan to implement.

**Comment by DMFriends** [comment]
@ChrisLovering Done. Let me know if you need anything else

**Comment by ChrisLovering** [comment]
I've just found this issue https://github.com/python-discord/sir-lancebot/issues/599 that has quite a bit more defined about it, did you want to take over that issue instead? As it's currently up for grabs?

**Comment by DMFriends** [comment]
Ok, will take a look
