### ISSUE TITLE
Restructure Lancebot's exts/ folder

### ISSUE THREAD

**Issue by janine9vn** [python-discord/sir-lancebot#841]
## Description
Sir-Lancebot, way back in the day, was created around seasons. We'd have things associated with Christmas, Easter, Valentine's Day, and then year-round things that we put under the "Evergreen" folder. With the growth of our community, Sir Lancebot has since outgrown this structure.

I'd like to re-organize Lancebot to be more general and less revolving around seasons.

## Reasoning
I think restructuring it to not be focused around seasons will make Lance's structure easier to understand for first-time contributors. I think the restructure I propose will make it easier to find things as well. Our `Evergreen` folder is quite large and can be a bit daunting to navigate.

## Proposed Implementation
This is my proposed general folder structure:
```
exts/
--adventofcode/
--holidays
    --hanukkah.py
    --easter/
    --valentines/
    --halloween/
    --pride/
--games/
    --all of our infinite games I'm not going to list out
--practical/ (this name is subject to change pending discussion)
    --wikipedia
    --wolfram
    --realpython
    --pythonfacts
--esoteric_challenges/
--trivia/
    --trivia_quiz
    --trivia_night
```
This is by no means an exhaustive list, but hopefully you get an understanding of the proposed structure changes.

## Additional Details
We currently have a `utils` folder. This will be renamed to `core` and then the `practical` folder listed above will be renamed to `utilities`. This is currently pending core-dev discussions.

This will probably significantly affect all current open PRs since it's changing the structure of things.

## Would you like to implement this yourself?
- [X] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

(If someone feels super strongly about this I'm also happy to pass it along, but I'm hoping to get this done and tested this weekend)

**Comment by Objectivitix** [comment]
Wow, super cool :D Lancy getting a restructure!

**Comment by D0rs4n** [comment]
That looks really nice. However, (that's just a suggestion.)  since Sir Lancebot is now on discord.py 2.0 I  believe it would be really great if somehow you could integrate the concept of views into the structure. That's still in the future, but as a concept I could imagine something like `generic_views` that are used all around the code, and are useful in many contexts, and "local" views that are specific to a Cog or topic.
(However no views have been created, and they won't be created in an instant I still think it'd be helpful to indicate them.)

**Comment by ChrisLovering** [comment]
I imagine generic views would go into the utils folder, similar to other helpers functions/classes, and cog-specific views would be near the cog itself.
