### ISSUE TITLE
Add Madlibs game

### ISSUE THREAD

**Issue by DMFriends** [python-discord/sir-lancebot#847]
## Description

I would like to create a Madlibs game command for Sir Lancebot.

## Reasoning

Most often than not, the output of the game (the story with the blanks filled in) will sound really funny and/or silly, so I'm sure many people will want to play it!

## Proposed Implementation

The command for this game will be `.madlibs`

When the command, `.madlibs`, is run, the bot will ask the user to enter a word that fits a random part of speech (e.g. noun, adjective, verb, plural noun, etc.). The user will simply send a message with any word that fits the given part of speech.

In the API, the computer (bot in this case) chooses a random number of user inputs to use for the game and a random story. This is what I would like my program to do as well.

Once the user has finished entering all the input prompts, the bot should send a message with the completed story using the words that the user entered.

As part of the implementation, I will be using this Madlibs API: https://madlibz.herokuapp.com/api

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by Kronifer** [comment]
Could you explain how you will get words from the user?

**Comment by DMFriends** [comment]
@Kronifer By simply asking the user to send a message with the word they want to use

**Comment by ChrisLovering** [comment]
This sounds like a good idea and can be quite fun.

If you wanted to as part of this, we could also add a profanity filter to sir lance, so that users can't get lance to parrot bad words. This is optional though, as we already have other similar commands that don't do this.

**Comment by DMFriends** [comment]
Thanks @ChrisLovering ! Yeah, that's a good idea, I will add the profanity filter as well.
