### ISSUE TITLE
Adding a challenge command

### ISSUE THREAD

**Issue by Shom770** [python-discord/sir-lancebot#848]
## Description

The `.challenge` command would pull a random kata (challenge) from codewars.com, and the user can filter with either the query or the kyu (difficulty), 1 being the hardest, 8 being the easiest, along with the programming language the kata is in.

## Reasoning

`codewars.com` is a popular website for coding challenges, which many people use. A lot of people including myself want to be challenged sometimes but aren't sure what to do, and sometimes people also hit 'code blocks'. This command would provide a random challenge from codewars.com, or kata as codewars calls it, so said person can be inspired to try the challenge provided. This command can be considered analogous to the `stackoverflow` and `realpython` commands, though different in the sense that it focuses on giving ideas rather than either sending the user to a helpful question that solves their problem or articles that help increase the understanding of the topic the user wants to learn.

## Proposed Implementation

**.challenge without any parameters, where the language parameter will default to python, and a random difficulty is chosen**
![image](https://user-images.githubusercontent.com/82843611/132108470-757f94b2-77b1-4c86-87af-7360c130cae3.png)
**.challenge with a difficulty parameter, looking for a random kata in that difficulty**
![image](https://user-images.githubusercontent.com/82843611/132108671-6eb4a387-d78f-41de-9925-ed9976f5b4d7.png)
**.challenge with a query parameter**
![image](https://user-images.githubusercontent.com/82843611/132108697-ae7d7a68-53fd-463b-9cff-c494de958482.png)
**.challenge with a query AND difficulty parameter, splitted by the dilimiter ','**
![image](https://user-images.githubusercontent.com/82843611/132108705-df9209f5-9241-4f61-a6d6-53c511aea2b7.png)
**.challenge with an invalid query**
![image](https://user-images.githubusercontent.com/82843611/132108715-7ba204a1-7afe-4381-8dcd-85266c552ebd.png)

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by janine9vn** [comment]
Are you planning on using the codewars API?
I've looked at it previously and I'm curious how you're going to search for katas or select random ones because as far as I know it only returns challenges that you specifically query for.

**Comment by Shom770** [comment]
> Are you planning on using the codewars API?
> I've looked at it previously and I'm curious how you're going to search for katas or select random ones because as far as I know it only returns challenges that you specifically query for.

I'm using bs4 to get the kata ID, coupled with the codewars API to get information about the kata itself

**Comment by ChrisLovering** [comment]
Sounds good to me, approved.
Codewars robots.txt has a blanket allow, and no where in the terms does it disallow automation.
