### ISSUE TITLE
Add coloredlogs

### ISSUE THREAD

**Issue by Numerlor** [python-discord/sir-lancebot#854]
We have been using coloredlogs on bot for a while now which makes the logs more readable. There initially were some issues on windows but those seem to have been taken care of now.
The same configuration as the bot uses can be used for consistency.

I can take care of this along with #706 if @ToxicKidz is not working on that issue

**Comment by Akarys42** [comment]
I believe we need to specify colorama as a win32 only dependency to make sure it is supported on any terminal. That sounds good to me though!

**Comment by Numerlor** [comment]
Alright, I'll start working on it
