### ISSUE TITLE
`.hanukkah` should not be timelocked to December

### ISSUE THREAD

**Issue by janine9vn** [python-discord/sir-lancebot#862]
## Description
Currently, the `.hanukkah` command is locked to only be usable in December. This is uh... not correct as Hanukkah can drift into November as well. 

## Possible Solutions
The `@in_month()` decorator can be expanded to include November as well as December.

## Would you like to implement a fix?
- [ ] I'd like to implement the bug fix
- [X] Anyone can implement the bug fix

**Comment by NIRDERIi** [comment]
Wow I am a jew and I didn't know it can be drifted to November as well. Anyways, yeah. Any chance you can point me to the commands source directory?

**Comment by wookie184** [comment]
> 
> 
> Wow I am a jew and I didn't know it can be drifted to November as well. Anyways, yeah. Any chance you can point me to the hanukkah command source directory?

The current check is here:
 https://github.com/python-discord/sir-lancebot/blob/edb80b90186b7ebfcce8b3dae55fedb62a77b912/bot/exts/holidays/hanukkah/hanukkah_embed.py#L40
Would you like to PR this change, @NIRDERIi?

**Comment by NIRDERIi** [comment]
Basically al needed to change is just doing: `@in_month(Month.DECEMBER, Month.NOVEMBER)` right?

**Comment by wookie184** [comment]
> Basically al needed to change is just doing: `@in_month(Month.DECEMBER, Month.NOVEMBER)` right?

Yeah that looks like it should work (although you could put November before December because it comes first :))

**Comment by NIRDERIi** [comment]
I would love to do the PR, tho I am not good with github so I am afraid I might be doing it wrong or it might take too much time.

**Comment by wookie184** [comment]
> I would love to do the PR, tho I am not good with github so I am afraid I might be doing it wrong or it might take too much time.

There's no rush at all for this to be done (still two months until November, and even then it wouldn't be urgent...), and there's no need to worry about doing something wrong- everything is fixable and you can ask on the server if you have any questions.

This is a pretty good issue for a first PR if you haven't done one before, so I'd say you should give it a go if you want to. If not, that's also fine :D

**Comment by NIRDERIi** [comment]
I did a PR once, but all I remember is forking the project, editing, and then somehow opening a PR. And after that Akarys did something with my fork and the repo.
