### ISSUE TITLE
Switch to a Discord.py fork

### ISSUE THREAD

**Issue by Kronifer** [python-discord/sir-lancebot#865]
## Description

Consider switching to a discord.py fork, such as nextcord, which will be maintained for the foreseeable future.

## Reasoning

We won't miss out on new features of discords API, and therell be more support in the long term.

## Proposed Implementation

Switch to nextcord. It's more or less a drop in replacement. Switch up a few imports and we're good.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by onerandomusername** [comment]
There's no reason to switch this early.
See https://canary.discord.com/channels/267624335836053506/635950537262759947/881484956495392768 for a statement from Zig.

Also that fork in particular is not the best, IMO. 

Good summary here: 

![image](https://user-images.githubusercontent.com/71233171/132655602-9a8784c8-41d3-4e69-8a33-ca7b9cf9b32f.png)
![image](https://user-images.githubusercontent.com/71233171/132655654-4e1465ef-be06-4365-ad1e-f60151f0e890.png)

**Comment by Xithrius** [comment]
I don't think we should switch to a fork unless we absolutely need to. dpy 2.0 seems to be doing well atm.

**Comment by onerandomusername** [comment]
I've only found a few bugs anyhow, neither of which should affect pydis
right now.

**Comment by Xithrius** [comment]
If this is considered, it will be done in the future. For now, there is no need to switch.

Thanks for bringing this up.
