### ISSUE TITLE
Fix the DDDG game board

### ISSUE THREAD

**Issue by camcaswell** [python-discord/sir-lancebot#866]
## Description
Editing an embed with an image causes the image to appear in the message as well. The original DDDG implementation used a workaround that immediately broke when we moved to discord.py 2.0. J9 then put in a temporary fix in the re-organization PR by editing the message text instead of the embed text. This fixes the image bug but places the text over the board, doesn't look as good, and is currently overwriting old text.

## Proposed Solution
As far as I can tell, there is no way to get around the image bug anymore. I want to split the initial message in two: one for the board that will not be edited, and one for the claimed flights that we can edit without the image bug.

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [x] I'd like to implement the bug fix
- [ ] Anyone can implement the bug fix

**Comment by wookie184** [comment]
Sounds fine to me.
