### ISSUE TITLE
Add a per-channel cooldown for .topic

### ISSUE THREAD

**Issue by janine9vn** [python-discord/sir-lancebot#868]
## Description & Reasoning
The `.topic` command provides conversation starters for our channels. It's very useful for getting things back on topic or to bring up a new thing to talk about. However, I've noticed that some people will just use this command as a rapid-fire answer mechanism, so they end up using `.topic` several times in as many minutes. 

That's not really the intent of this command and is quite spammy, especially in already fast moving channels like python-general. I propose adding some sort of cooldown to the command to allow people to actually discuss the topic rather than fire one-word answers and get the next topic.

## Proposed Implementation
Add the appropriate cooldown decorator, making it per-channel.

## Would you like to implement this yourself?
- [ ] I'd like to implement this feature myself
- [X] Anyone can implement this feature

**Comment by janine9vn** [comment]
People have brought up the issue of if the users don't like the current topic, how can they get a new one?

The proposed solution there is to add a reaction to re-run the topic to pick a new one.

**Comment by D0rs4n** [comment]
> People have brought up the issue of if the users don't like the current topic, how can they get a new one?
> 
> The proposed solution there is to add a reaction to re-run the topic to pick a new one.

It could also be solved, by adding a countdown button, and when it reaches the desired amount of votes it picks new one.(Timeout should be configured accordingly)
(Just to make use of the new dpy. 2 features 👍 )
