### ISSUE TITLE
Unwanted error handling in command suggestions.

### ISSUE THREAD

**Issue by Qwerty-133** [python-discord/sir-lancebot#870]
## Description

The bot sometimes sends you error messages when you type invalid commands.

## Steps to Reproduce
Type `...and` or `.cand` or so on in a channel, and you'll be met with an embed by the bot saying "Command can only be used in October." This happens because the command handler tries suggesting the `candy` command but its checks raise a check failure, and the check failure is passed to the error handler again which is handled by it by posting that october embed.

## Expected Behaviour

The bot shouldn't send any message at all.

## Possible Solutions

157b19b5b99d5ab0ea5f62bb8231765916bf90d8 should fix it.

## Would you like to implement a fix?

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [X] I'd like to implement the bug fix
- [ ] Anyone can implement the bug fix

**Comment by parth-verma7** [comment]
@Qwerty-133  Actually this has already been fixed. Please have a look.

**Comment by wookie184** [comment]
Yeah, looks like it was fixed by https://github.com/python-discord/sir-lancebot/pull/1096, thanks
