### ISSUE TITLE
suggestion: button paginator

### ISSUE THREAD

**Issue by onerandomusername** [python-discord/sir-lancebot#883]
## Description

Now that sir-lancebot is on dpy2 v2, lance can use buttons.

I'd like to see a button paginator on lance, rather than reactions.

## Reasoning

Honestly, there's not much of an internal benefit, except for not having to listen for reactions 😄 

## Proposed Implementation

Basically, would change the external interface to this:
![image](https://user-images.githubusercontent.com/71233171/134792563-b4f396a7-9d89-4e6c-a249-181d85d748cc.png)

Here's an apples to apples comparison of buttons to emojis:
PC:
![image](https://user-images.githubusercontent.com/71233171/134792581-d5890ac5-f7de-4fe0-b352-2528c5802782.png)
Android:
![image](https://user-images.githubusercontent.com/71233171/134792594-c1fedf90-0f2a-48a4-b4aa-54d21bdd02fb.png)

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature
^ anyone can implement this, I have an implementation for my bot which I can link if anyone wants inspiration, I'm just too busy to port it myself.

**Comment by shtlrs** [comment]
We've discussed this internally before, and I remember us not really liking the looks of the buttons.

In any case, the paginator is now a bot-core component, so I'll close this issue here.
