### ISSUE TITLE
should the avatar commands support per-server pfps or not?

### ISSUE THREAD

**Issue by onerandomusername** [python-discord/sir-lancebot#887]
## Description

Currently, avatar commands use the user's avatar, and not the guild specific avatar.

## Steps to Reproduce

run any avatar command

## Expected Behaviour

the displayed avatar is used to make the images.

## Actual Behaviour

the user's global avatar is used to make the images.

## Known Impacted Platforms

- [x] Web
- [x] Desktop
- [x] Android App
- [x] iOS App

## Possible Solutions

Change to the documented display_avatar() method in discord.py 2.

## Would you like to implement a fix?

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [x] I'd like to implement the bug fix
- [ ] Anyone can implement the bug fix

**Comment by HassanAbouelela** [comment]
Approved and assigned.

**Comment by onerandomusername** [comment]
This was resolved with https://github.com/python-discord/sir-lancebot/commit/ffda1f7069065fd4ce2b2fe781fbcb5793406f99
