### ISSUE TITLE
issue on .topic reaction

### ISSUE THREAD

**Issue by Nipa-Code** [python-discord/sir-lancebot#894]
## Description
When bot adds reaction  to `.topic` , and then user tries reacting happens on it. If moderator reacts to reaction, then it works.

## Steps to Reproduce

1. Use ``.topic`` without any mod role
2. Click the reaction
3. Nothing happens

## Expected Behaviour

On reaction bot should refresh the `topic`. 

## Actual Behaviour

When non moderator reacts to message the bot does not refresh anything. 

## Known Impacted Platforms

- [ ] Web
- [x] Desktop
- [x] Android App
- [ ] iOS App

## Would you like to implement a fix?

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [ ] I'd like to implement the bug fix
- [x] Anyone can implement the bug fix

**Comment by Nipa-Code** [comment]
@TizzySaurus has said he'd like to work on this

**Comment by ChrisLovering** [comment]
While you're doing this, could you also have the bot remove the user's reactions after it's refreshed the topic?
