### ISSUE TITLE
Python Trivia Night Command(s)

### ISSUE THREAD

**Issue by janine9vn** [python-discord/sir-lancebot#903]
## Description
One of the events I'm planning to host in 2022 is a Python Trivia Night! People will gather in a stage channel and we'll be asking Python Trivia questions for people to answer. To help with participation and running the event, I'd like to have a cog/extension with a set of commands to help facilitate this.

## Proposed Implementation
I'd like a new set of commands under `.trivianight` or `.triviaevent`.

`.trivianight load` will accept a json file of appropriately formatted questions, options for users to select, and the final answer.
`.trivianight start` will start the trivia event. For this, it will initialize a scoreboard and clear any old scoreboards that may be hanging around.
`.trivianight next` will pick an unanswered question from the question bank, post it in a configured channel, and provide multiple choice buttons for users to select. Users will be able to press the buttons to select their answer and should be allowed to change their answer once. Any subsequent changes aren't allowed and the interaction should fail. After a certain period of time or with a command (`.trivianight pause` or `.trivianight next`) the buttons will be removed and the correct answer will be revealed.
`.trivianight stop` will end the trivia event and produce the final scoreboard results. I'd like to keep track of questions attempted, questions answered correctly, and average time to answer a question. 
`.trivianight #` will select that specific question whether or not it's been answered to be answered again.

## Additional Details
- This should use Discord buttons!
- If an interaction fails, it should be an ephemeral message to just the user.
- Bonus points if there's some validation on the provided question json, but not necessary.

## Would you like to implement this yourself?
- [ ] I'd like to implement this feature myself
- [X] Anyone can implement this feature

I'm fine with anyone implementing this, but I'd like to get this fully functional by mid-December and it will most likely require a fair amount of iteration and changes. So keep that in mind if you'd like to work on this.

**Comment by Shom770** [comment]
I'd be down to work on this! I'm not sure if this would require any database experience though because I've only worked with MongoDB and I don't know how any other databases work (like redis and what not)
