### ISSUE TITLE
un bookmark command

### ISSUE THREAD

**Issue by Nipa-Code** [python-discord/sir-lancebot#918]
## Description
There would be a way to remove a bookmark. This would be useful while mistakenly creating a bookmark or if you have many of bookmarks and don't want to have them there anymore. 
## Reasoning

If you happen to create a bookmark for a wrong message, you could delete that bookmark. Or if you just have a old bookmark that you don't anymore need. It would keep the bookmarks clear.

## Proposed Implementation

Possibly creating a tag for each bookmark, as example `#4321`. With that you could do `.unbm 4321` or `.unbm #4321`

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by ChrisLovering** [comment]
I think instead of checking it matches the bookmark structure, we can make it so that it can only be ran in DMs. Less room for error that way.

**Comment by ChrisLovering** [comment]
The other option is that we store messageIDs of the messages in DMs, and add a reaction. We then have a listener for RawReactionActionEvent which checks if that message ID is in redis, and deletes the message and removes it from redis.
