### ISSUE TITLE
Replace reactions in the `bookmark` command with buttons.

### ISSUE THREAD

**Issue by InvisibleOS** [python-discord/sir-lancebot#932]
## Description
Right now, bookmarking messages as someone who is not the command invoker requires adding a reaction. I believe that the system can be made much more better using buttons as it greatly improves the UI and makes it a bit more simpler.

## Reasoning
While using interactions, we now have an option to make any error only visible to the interaction author by making the error message ephemeral. This would mean that the error message will not be publicly visible and a confirmation message that is only visible to the interaction author can be sent as well.

## Proposed Implementation
![image](https://user-images.githubusercontent.com/76255686/139523053-2dd7b5cb-8d7f-49a3-a05b-caed23971f5b.png)

## Additional Details
We can even make use of the link buttons and attach them to the bookmarked message. When clicked, they would redirect the user to the message. Adding a button for it would make the embed solely limited to the message content and a `View Message` link button would improve the UI as well as make navigation to the message a bit more easier.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by onerandomusername** [comment]
I'd like to see this happen too.

**Comment by Akarys42** [comment]
I'd also add that this is a good time to edit the feedback message instead of deleting it after the timeout, so you have a trace of the invocation and not just nothing

**Comment by D0rs4n** [comment]
Approved, and assigned! 
Good luck!

**Comment by InvisibleOS** [comment]
I am extremely sorry to say but I currently have exams for a month due to which I will not be able to work on this. I had posted this sometime back when I had time but currently, my exams are right around the corner which is why I will not be able to work on this right now.

This can either be assigned to someone else or I can work on it from the 7th of January - whichever works (my exams end on the Jan 7th)

**Comment by onerandomusername** [comment]
I'm not sure what the priority is for this feature, but I don't think it's too high. Unless someone else comes along wanting to implement it, this will still be here in January.

**Comment by D0rs4n** [comment]
I'll add the `up for grabs` label, unless someone else takes it, you can go ahead and implement it in January.
Good luck with your exams!

**Comment by InvisibleOS** [comment]
Thank you very much!

**Comment by Diabolical5777** [comment]
Can I request to be assigned?

**Comment by Xithrius** [comment]
@Diabolical5777 Yes.

**Comment by Diabolical5777** [comment]
Just to confirm, the suggestion is simply to replace the current reaction for others receiving the bookmark to a button, right?

**Comment by Xithrius** [comment]
Yes.

**Comment by Diabolical5777** [comment]
For the implementation of the button, I would ideally add the multiple arguments to the init of the view class and call the button with the arguments how it's being called currently, right?

**Comment by wookie184** [comment]
> For the implementation of the button, I would ideally add the multiple arguments to the init of the view class and call the button with the arguments how it's being called currently, right?

Yes, I think that sounds right. There are some examples of discord.py views with buttons here if that helps: https://github.com/python-discord/sir-robin/blob/e90d24072baf2dc57acd455e8a9d7e5d40457d46/bot/exts/code_jams/_views.py

**Comment by Diabolical5777** [comment]
![image](https://user-images.githubusercontent.com/84365102/185363935-8851eb69-3210-4c3e-bae6-8831a26789ef.png)
Is using a button to be redirected to the bookmarked message in the user's DM's a good idea?
