### ISSUE TITLE
possible error/bug at `.wiki` command

### ISSUE THREAD

**Issue by Nipa-Code** [python-discord/sir-lancebot#933]
## Description

There might be a bug/error when reacting to `.wiki` commands trashcan, I was able to remove the message by clicking trashcan even when I was not the one running the command. 

## Steps to Reproduce

If this is not how it should act there might be a error in check. Maybe adding a check to function to `.wiki` command (if this is not how it should act). It would be nice to be limited, so it would not be clicked to annoy others or be pressed mistakenly to remove the message.

## Expected Behaviour

I would expect the bot to remove the message only if command author presses the trashcan reaction. 

## Actual Behaviour

Instead anyone seems to be able to remove the message when trashcan is pressed.

## Known Impacted Platforms

- [ ] Web
- [x] Desktop
- [ ] Android App
- [ ] iOS App

## Possible Solutions

Checking if there is a check function to see who click the trashcan and see if they are the one who ran the command. So adding the check in there.

## Would you like to implement a fix?

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [x] I'd like to implement the bug fix
- [ ] Anyone can implement the bug fix

**Comment by HassanAbouelela** [comment]
Thanks for the report. The paginator takes a `restrict_to_user` argument:
https://github.com/python-discord/sir-lancebot/blob/ba4b0e498191195d773c031fcfdaef862bd472b8/bot/utils/pagination.py#L91-L95

which can be used for this exact purpose. I think we should use it here.

**Comment by Nipa-Code** [comment]
I see, that would be really nice to have on commands that have the trashcan reaction, especially the ones with more than a bit of content eg. `.wiki` command.
