### ISSUE TITLE
.rp improvement 

### ISSUE THREAD

**Issue by Nipa-Code** [python-discord/sir-lancebot#940]
## Description

The `.rp` command currently gives 5 results by default but what if you wanted to get only 1-4? There should be a option to get amount you want by still keeping the max 5 as default. If no amount provided default value, 5, will be returned.

## Reasoning

Getting only specific amount of results if you don't want to see more, and could possibly be good to limit results if wanted.
## Proposed Implementation

Currently I don't have any in code implementations, but some sort of limit would be added in there.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by ChrisLovering** [comment]
This sounds good. I think an optional int argument before the query would work, since I doubt people will be starting their queries with numbers.
