### ISSUE TITLE
View Your Score in Candy Command

### ISSUE THREAD

**Issue by Shivansh-007** [python-discord/sir-lancebot#947]
## Description
Currently, there is no way to view your (the member who invoked the command) score, I suggest adding another line to the resulting embed which tells the user their own candy score. 

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [X] Anyone can implement this feature

**Comment by katimoth** [comment]
I'd like to work on this issue. Is there anyone else currently working on this?

**Comment by evgriff** [comment]
![Screen Shot 2021-11-30 at 2 01 10 PM](https://user-images.githubusercontent.com/44847470/144110901-cf67139f-7a1c-44b5-b538-765d3c50ec0f.png)

I'm working on this with @katimoth right now - here is what we have this feature looking like right now. Any suggestions?

**Comment by evgriff** [comment]
Ready to start a PR, could I be assigned?
