### ISSUE TITLE
aoc buff: remove the leaderboard command, and make it an updating message

### ISSUE THREAD

**Issue by onerandomusername** [python-discord/sir-lancebot#966]
## Description

Too many people are trying to get the leaderboard rapidly. Since it only updates once every 30 minutes, a channel of #aoc-leaderboard would be nice while the game is afoot. This would automatically update every 30 minutes, as the leaderboard currently does. The current aoc lb command would link to the #aoc-leaderboard channel, maybe showing the user where they currently are, but linking to the channel to view the full lb.
## Reasoning

![image](https://user-images.githubusercontent.com/71233171/144550687-b4a39cd5-79a7-4be4-a10d-92c02981ad3f.png)

![image](https://user-images.githubusercontent.com/71233171/144550664-7e3e7622-6a0b-47c4-9fc8-38bcd8312e90.png)

## Proposed Implementation

Special channel which will feature the leaderboard, updating every 30 minutes

## Would you like to implement this yourself?

I do not care, if I can get to it tomorrow I will attempt to implement it myself, but if someone else has an idea for it, they can go for it as well.
- [ ] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by bsoyka** [comment]
A very similar idea (a pinned message) has been brought up [briefly](https://discord.com/channels/267624335836053506/897932607545823342/915957815481360394) on Discord already, and Kat's decision was that we want to reduce calls to the AoC servers as much as possible, so we're only refreshing the leaderboard when it's requested. (cc: @janine9vn)

I'm open to discussing potential solutions to this, but I don't think there's a good way to do this without making unnecessary calls to AoC.

**Comment by onerandomusername** [comment]
> A very similar idea (a pinned message) has been brought up [briefly](https://discord.com/channels/267624335836053506/897932607545823342/915957815481360394) on Discord already, and Kat's decision was that we want to reduce calls to the AoC servers as much as possible, so we're only refreshing the leaderboard when it's requested. (cc: @janine9vn)
> 
> I'm open to discussing potential solutions to this, but I don't think there's a good way to do this without making unnecessary calls to AoC.

Hmmmm, depending on the complexity, we could use a button on the leaderboard message, and edit the message to make the button enabled or disabled depending on if we want to act on it, eg make a request to aoc to update the lb.

this would mean that every 30 minutes, we would be able to make a request to aoc, and anyone could press the button to trigger it, which would edit the message with the new lb and disabling the button at the same time.

after 30 minutes, the button would be silently re-enabled, and someone could press it at that time. 

Additionally, we would be able to use discord timestamps, to show a helpful message in the lb command of how long until the lb can be refreshed again.

**Comment by onerandomusername** [comment]
> Additionally, we would be able to use discord timestamps, to show a helpful message in the lb command of how long until the lb can be refreshed again.

This may be worth a second and different issue, given that this can be implemented regardless of the rest of this pr.

**Comment by bsoyka** [comment]
Personally I think the buttons are a great idea, although I think we should still keep the command around for the self-placement feature. (Should be straightforward to keep the same cooldown for API requests, looks like that's in another function already.)

I'll wait for Kat's input here as our events lead.

**Comment by onerandomusername** [comment]
Yeah, but i also think we can shrink the full embed down, keep that function, but not the other part of the function.

Actually, when #964 gets merged, the default of the leaderboard command could be the user's user if they've linked it.

**Comment by Shivansh-007** [comment]
> Personally I think the buttons are a great idea, although I think we should still keep the command around for the self-placement feature. 

We can use buttons and ephemeral replies to display the user's score.

**Comment by onerandomusername** [comment]
...That's true, with the above pr, a user will link it, and we will be able to have the lb in a command, then send an ephermal with the score of a user.

However, the lb command as @bsoyka mentioned should probably continue to exist.

**Comment by janine9vn** [comment]
We will definitely not have a leaderboard that refreshes automatically every 30 minutes. As it stand now we're already pushing the limits of the refresh rate with 30 minutes considering we're requesting 7 leaderboards everytime. The 30 minute cooldown is an absolute minimum, meaning we would expect there to be longer intervals throughout the day where we don't make the request.

Additionally, having a standalone channel with a message for the leaderboard places even more emphasis on the leaderboard and scoring aspect of Advent of Code, which is not what I'm after and not what I want. The point of Advent of Code is not to get a good placement on the leaderboard, it's to challenge yourself and do something fun with programming. While the leaderboard placement it is a motivator for some people, it's not something that is the *sole* motivator or what I want people to focus on. So I don't think having a permanent leaderboard message in a standalone channel is a beneficial thing to solve what I believe is honestly a non-problem.

The leaderboard embed as it stands tells you it refreshes every 30 minutes and what time it was last updated (and that time is localized).

**Comment by ChrisLovering** [comment]
While we won't be implementing this exactly as stated, we do have plans for an improved leaderboard next year.

Where we serve a webpage that has the joined up PyDis leaderboard, in an AoC style.

Since this will serve as the static leaderboard as described in this issue, I think we can leader this command alone.
