### ISSUE TITLE
Add more topics to topic starters

### ISSUE THREAD

**Issue by Objectivitix** [python-discord/sir-lancebot#986]
## Description
This issue proposes to add more topics (number currently undecided, perhaps a few dozen) to our two `.yaml` files containing topic starters.

## Reasoning
I've seen quite some people complaining about how the topics aren't fresh anymore and have appeared several times already. This is due to our limited quantity of them. I believe adding more topics can benefit the community, especially when sometimes we need to get a derailed conversation back on topic.

## Proposed Implementation
Simply adding more topics to the two `.yaml` files in `bot/resources/utilities`. Perhaps in the future, when there are a lot of topics, we can even categorize them using parameters in the `.topic` command (which is another matter deserving its own issue when we get there).

## Would you like to implement this yourself?
- [x] I'd like to implement this feature myself with collaborators to brainstorm topics
- [ ] Anyone can implement this feature

**Comment by Xithrius** [comment]
We do go through the topic suggestions that are linked when you fire the command every once in a while.

I believe that it's time I should go through them again. Thank you for bringing this up.

**Comment by onerandomusername** [comment]
> We do go through the topic suggestions that are linked when you fire the command every once in a while.
> 
> I believe that it's time I should go through them again. Thank you for bringing this up.
> 
> After I'm done going through the suggested topics, I'll create a PR for the new listing. I'll leave it up for a bit so I can get a good amount of suggestions.
> 
> If you have a bunch of topics in mind, feel free to put them in a comment within this issue.

There was a discussion on discord about whether this is even the best way to add topics, but I'd like to see your input. https://canary.discord.com/channels/267624335836053506/429409067623251969/922543842530582609

**Comment by Xithrius** [comment]
I currently don't have ideas for implementations of the current way we go through suggestions.

**Comment by wookie184** [comment]
If you have a bunch of ideas i'd say feel free to open a PR @Objectivitix, not sure what xith was planning though (was it that form thing we have you were going to look through @Xithrius?). If you both have some to add it might be easier to chuck them all in one PR.

**Comment by Xithrius** [comment]
@wookie184 Sorry for the late reply. Yes, the plan was just sift through the form.
